/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MapsSuggestions.framework/MapsSuggestions
 */

@interface MapsSuggestionsFlightUpdater : NSObject {
    <MapsSuggestionsFlightRequester> * _flightRequester;
    <MapsSuggestionsNetworkRequester> * _networkRequester;
    struct Queue { 
        NSObject<OS_dispatch_queue> *_innerQueue; 
        NSString *_name; 
    }  _queue;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (bool)_getGateMapItemForFlightEntry:(id)arg1 handler:(id /* block */)arg2;
- (bool)_getTerminalMapItemForFlightEntry:(id)arg1 handler:(id /* block */)arg2;
- (void)_updateFlightsForEntry:(id)arg1 handler:(id /* block */)arg2;
- (bool)_updateGateIfNeededForEntry:(id)arg1 handler:(id /* block */)arg2;
- (id)initWithFlightRequester:(id)arg1 networkRequester:(id)arg2;
- (bool)updateFlightsForEntry:(id)arg1 handler:(id /* block */)arg2;

@end
