/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUAppleMusicLoginItem : HUAppleMusicItem

- (id)_subclass_updateWithOptions:(id)arg1;

@end
