/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUAppleMusicAccountItemManager : HFItemManager {
    HUAppleMusicAccountModule * _module;
    bool  _shouldDisableUpdates;
}

@property (nonatomic, readonly) HUAppleMusicAccountModule *module;
@property (nonatomic) bool shouldDisableUpdates;

- (void).cxx_destruct;
- (id)_buildItemProvidersForHome:(id)arg1;
- (id)_buildSectionsWithDisplayedItems:(id)arg1;
- (void)_moduleStateDidChangeFrom:(unsigned long long)arg1 to:(unsigned long long)arg2;
- (id)initWithMediaProfileContainer:(id)arg1 delegate:(id)arg2;
- (id)module;
- (void)setShouldDisableUpdates:(bool)arg1;
- (bool)shouldDisableUpdates;

@end
