/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUCameraStreamAndRecordStateInfoProvider : HFStaticItemProvider

- (id)initWithDisplayStyle:(unsigned long long)arg1;

@end
