/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUClipScrubberDataSource : NSObject <HFCameraPlaybackEngineObserver, UICollectionViewDataSource> {
    UICollectionView * _clipCollectionView;
    NSArray * _clips;
    HMCameraClip * _currentClip;
    NSDate * _currentDate;
    unsigned long long  _currentTimelineState;
    unsigned long long  _displayMode;
    bool  _editing;
    double  _lastGestureScale;
    long long  _lastSelectedClipIndex;
    unsigned long long  _mostRecentClipIndex;
    HFCameraPlaybackEngine * _playbackEngine;
    HUClipScrubberSelectionView * _selectionView;
    bool  _selectionViewHidden;
    double  _startingPinchDeltaX;
    HUClipScrubberTimeController * _timeController;
}

@property (nonatomic) UICollectionView *clipCollectionView;
@property (nonatomic, readonly) NSArray *clips;
@property (nonatomic) HMCameraClip *currentClip;
@property (nonatomic, retain) NSDate *currentDate;
@property (nonatomic) unsigned long long currentTimelineState;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) unsigned long long displayMode;
@property (getter=isEditing, nonatomic) bool editing;
@property (readonly) unsigned long long hash;
@property (nonatomic) double lastGestureScale;
@property (nonatomic) long long lastSelectedClipIndex;
@property (nonatomic, readonly) unsigned long long mostRecentClipIndex;
@property (nonatomic) HFCameraPlaybackEngine *playbackEngine;
@property (nonatomic, retain) HUClipScrubberSelectionView *selectionView;
@property (nonatomic) bool selectionViewHidden;
@property (nonatomic) double startingPinchDeltaX;
@property (readonly) Class superclass;
@property (nonatomic, retain) HUClipScrubberTimeController *timeController;

- (void).cxx_destruct;
- (id)_indexPathsForClip:(id)arg1;
- (bool)_isZoomingIn:(double)arg1;
- (void)_updateClipCollectionView;
- (void)beginTimeScaleTrackingForPinchGesture:(id)arg1;
- (void)changeTimeScaleForPinchGesture:(id)arg1;
- (id)clipCollectionView;
- (id)clips;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)currentClip;
- (id)currentDate;
- (unsigned long long)currentTimelineState;
- (unsigned long long)displayMode;
- (id)initWithClips:(id)arg1;
- (bool)isClipLocatedAtIndexPath:(id)arg1;
- (bool)isEditing;
- (double)lastGestureScale;
- (long long)lastSelectedClipIndex;
- (unsigned long long)mostRecentClipIndex;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (double)offsetForClip:(id)arg1;
- (id)playbackEngine;
- (void)playbackEngine:(id)arg1 didRemoveClips:(id)arg2;
- (void)playbackEngine:(id)arg1 didUpdateClips:(id)arg2;
- (void)reloadClips:(id)arg1;
- (double)scrubbingResolutionForClip:(id)arg1;
- (id)selectedDateFromCell:(id)arg1 atCurrentOffset:(double)arg2;
- (id)selectedDateFromCell:(id)arg1 atOffset:(double)arg2;
- (id)selectionView;
- (bool)selectionViewHidden;
- (void)setClipCollectionView:(id)arg1;
- (void)setCurrentClip:(id)arg1;
- (void)setCurrentDate:(id)arg1;
- (void)setCurrentTimelineState:(unsigned long long)arg1;
- (void)setDisplayMode:(unsigned long long)arg1;
- (void)setEditing:(bool)arg1;
- (void)setLastGestureScale:(double)arg1;
- (void)setLastSelectedClipIndex:(long long)arg1;
- (void)setPlaybackEngine:(id)arg1;
- (void)setSelectionView:(id)arg1;
- (void)setSelectionViewHidden:(bool)arg1;
- (void)setStartingPinchDeltaX:(double)arg1;
- (void)setTimeController:(id)arg1;
- (id)startDateFromCell:(id)arg1;
- (double)startingPinchDeltaX;
- (id)timeController;
- (void)toggleSelectionStateForItemAtIndexPath:(id)arg1;
- (void)updateMostRecentClipIndex;
- (void)updateSelectionViewIfNeeded;
- (void)updateToClipAtIndexPath:(id)arg1;

@end
