/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUHomeFeatureOnboardingUtilities : NSObject

+ (id)_checkIdentifyVoicePrerequisitesForHome:(id)arg1;
+ (bool)_checkIdentifyVoicePrerequisitesSimpleForHome:(id)arg1;
+ (bool)_userHasSaidYesToShowTVViewingProfilesIn:(id)arg1;
+ (id)analyzeHomeAssistantDevicesForSupportedMultiUserLanguages:(id)arg1 home:(id)arg2;
+ (bool)atLeastOneHomePodHasLanguageSettingsForHome:(id)arg1;
+ (id)checkVoiceProfileAvailabiltyForLanguage:(id)arg1;
+ (id)createPersonalIdentityDeviceLanguageMismatchList:(id)arg1;
+ (bool)currentUserHasUnfinishedFeatureOnboardingForHome:(id)arg1;
+ (id)fetchSupportedMultiUserLanguages:(id*)arg1;
+ (void)fetchSupportedMultiUserLanguagesWithCompletion:(id /* block */)arg1;
+ (id)groupedFeaturesForOnboardingFlowKeyPaths:(id)arg1;
+ (bool)hasUserSaidYesToVoiceIdentificationInResults:(id)arg1;
+ (bool)home:(id)arg1 canShowIdentifyVoiceOnboardingWithUsageOptions:(id)arg2;
+ (unsigned long long)home:(id)arg1 checkForMultiUserDeviceUpgradeRequirements:(id)arg2;
+ (unsigned long long)home:(id)arg1 checkForOwnerUpgradeRequirementsFromResults:(id)arg2;
+ (id)home:(id)arg1 createMultiUserLanguageToHomePodsMapping:(id)arg2;
+ (bool)home:(id)arg1 hasSomeHomePodsOnSupportedMultiUserLanguages:(id)arg2;
+ (id)home:(id)arg1 onboardAllFeaturesFromPresentingViewController:(id)arg2 usageOptions:(id)arg3;
+ (id)home:(id)arg1 onboardFeaturesForKeyPaths:(id)arg2 presentingViewController:(id)arg3 usageOptions:(id)arg4;
+ (id)home:(id)arg1 onboardIdentifyVoiceFromPresentingViewController:(id)arg2 usageOptions:(id)arg3;
+ (id)home:(id)arg1 processHomeFeatureOnboarderResults:(id)arg2;
+ (bool)home:(id)arg1 voiceRecognitionIsSupportedForCurrentUserOnHomePod:(id)arg2;
+ (bool)isDeviceUsingASupportedMultiUserSiriLanguage:(id)arg1;
+ (void)presentAlertConfirmingTurningOfVoiceRecognitionFrom:(id)arg1;
+ (void)presentAlertConfirmingTurningOffPersonalRequestsFrom:(id)arg1;
+ (id)processLanguageAndMediaProfileInfo:(id)arg1;

@end
