/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUNearbyAccessoriesViewController : HUServiceGridViewController {
    HMAccessory * _currentAccessory;
    <HUNearbyAccessoriesViewControllerDelegate> * _nearbyAccessoriesDelegate;
    bool  _supportsQuickControls;
    NSArray * _userInfoConstraints;
    UILabel * _userInfoDescription;
    UILabel * _userInfoHeading;
}

@property (nonatomic, retain) HMAccessory *currentAccessory;
@property (nonatomic, readonly) HUNearbyAccessoriesItemManager *itemManager;
@property (nonatomic) <HUNearbyAccessoriesViewControllerDelegate> *nearbyAccessoriesDelegate;
@property (nonatomic) bool supportsQuickControls;
@property (nonatomic, retain) NSArray *userInfoConstraints;
@property (nonatomic, retain) UILabel *userInfoDescription;
@property (nonatomic, retain) UILabel *userInfoHeading;

- (void).cxx_destruct;
- (void)configureCell:(id)arg1 forItem:(id)arg2;
- (id)currentAccessory;
- (void)doneButtonPressed:(id)arg1;
- (id)initWithSourceItem:(id)arg1 supportsQuickControls:(bool)arg2;
- (void)itemManager:(id)arg1 didUpdateResultsForSourceItem:(id)arg2;
- (id)layoutOptionsForSection:(long long)arg1;
- (id)nearbyAccessoriesDelegate;
- (bool)presentationCoordinator:(id)arg1 shouldBeginPresentationWithContext:(id)arg2;
- (bool)presentationCoordinatorShouldProvideCancellationFeedback:(id)arg1;
- (void)setCurrentAccessory:(id)arg1;
- (void)setNearbyAccessoriesDelegate:(id)arg1;
- (void)setSupportsQuickControls:(bool)arg1;
- (void)setUserInfoConstraints:(id)arg1;
- (void)setUserInfoDescription:(id)arg1;
- (void)setUserInfoHeading:(id)arg1;
- (bool)supportsQuickControls;
- (void)updateViewConstraints;
- (id)userInfoConstraints;
- (id)userInfoDescription;
- (id)userInfoHeading;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;

@end
