/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUSmartDetectionSettingsItem : HFItem {
    NSSet * _cameraProfiles;
    unsigned long long  _motionDetectionType;
    unsigned long long  _settingsContext;
}

@property (nonatomic, readonly, copy) NSSet *cameraProfiles;
@property (nonatomic, readonly) unsigned long long motionDetectionType;
@property (nonatomic, readonly) unsigned long long settingsContext;

- (void).cxx_destruct;
- (id)_subclass_updateWithOptions:(id)arg1;
- (id)cameraProfiles;
- (id)initWithDetectionType:(unsigned long long)arg1 cameraProfiles:(id)arg2 settingsContext:(unsigned long long)arg3;
- (unsigned long long)motionDetectionType;
- (unsigned long long)settingsContext;

@end
