/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PDCloudStoreService : PDXPCService <PDCloudStoreServiceExportedInterface> {
    PDCloudStoreNotificationCoordinator * _cloudStoreNotificationCoordinator;
    PKEntitlementWhitelist * _whitelist;
}

@property (nonatomic, retain) PDCloudStoreNotificationCoordinator *cloudStoreNotificationCoordinator;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)allItemsOfItemType:(unsigned long long)arg1 storeLocally:(bool)arg2 completion:(id /* block */)arg3;
- (void)checkTLKsMissingWithCompletion:(id /* block */)arg1;
- (id)cloudStoreNotificationCoordinator;
- (void)cloudStoreStatusForContainer:(id)arg1 completion:(id /* block */)arg2;
- (void)copyDataFromZoneName:(id)arg1 toZoneName:(id)arg2 inContainerName:(id)arg3 passUniqueID:(id)arg4 completion:(id /* block */)arg5;
- (void)deleteZone:(id)arg1 containerName:(id)arg2 completion:(id /* block */)arg3;
- (void)fetchAndStoreRecordsForPaymentPassWithUniqueIdentifier:(id)arg1 completion:(id /* block */)arg2;
- (void)generateRandomTransactionForPassWithUniqueIdentifier:(id)arg1 completion:(id /* block */)arg2;
- (id)initWithConnection:(id)arg1;
- (void)itemOfItemType:(unsigned long long)arg1 recordName:(id)arg2 qualityOfService:(long long)arg3 completion:(id /* block */)arg4;
- (void)noteAccountDeletedWithHandler:(id /* block */)arg1;
- (void)noteCloudSyncPassesSwitchChangedWithHandler:(id /* block */)arg1;
- (void)populateEvents:(id)arg1 forAccountIdentifier:(id)arg2 completion:(id /* block */)arg3;
- (void)recreateZone:(id)arg1 completion:(id /* block */)arg2;
- (void)removeItemsWithRecordNames:(id)arg1 itemType:(unsigned long long)arg2 completion:(id /* block */)arg3;
- (void)removeRecordWithRecordName:(id)arg1 zoneName:(id)arg2 containerName:(id)arg3 completion:(id /* block */)arg4;
- (void)resetApplePayManateeViewWithCompletion:(id /* block */)arg1;
- (void)resetContainerWithIdentifier:(id)arg1 completion:(id /* block */)arg2;
- (void)setCloudStoreNotificationCoordinator:(id)arg1;
- (void)setupCloudDatabaseForContainerName:(id)arg1 completion:(id /* block */)arg2;
- (void)simulateCloudStorePushForContainerIdentifier:(id)arg1 completion:(id /* block */)arg2;
- (void)updateCloudStoreWithLocalItems:(id)arg1 recordSpecificKeys:(id)arg2 includeServerData:(bool)arg3 completion:(id /* block */)arg4;
- (void)uploadTransaction:(id)arg1 forPassWithUniqueIdentifier:(id)arg2 includeServerData:(bool)arg3 completion:(id /* block */)arg4;

@end
