/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKAppletSubcredentialAccountAttestationRequest : PKAccountAttestationRequest {
    NSData * _sharingToken;
    NSData * _subCASEResidencyAttestation;
}

@property (nonatomic, copy) NSData *sharingToken;
@property (nonatomic, copy) NSData *subCASEResidencyAttestation;

- (void).cxx_destruct;
- (id)initWithRequestData:(id)arg1;
- (void)setSharingToken:(id)arg1;
- (void)setSubCASEResidencyAttestation:(id)arg1;
- (id)sharingToken;
- (id)subCASEResidencyAttestation;

@end
