/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKBroadwayBankAccountInformation : PKBankAccountInformation

- (long long)type;
- (void)updateToLatestKeychainData;

@end
