/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKPaymentRegistrationUtilities : NSObject

+ (bool)_shouldShowAddCardFlow:(id)arg1;
+ (void)configureWebServiceIfNecessary:(id)arg1 completion:(id /* block */)arg2;
+ (void)registrationIsSupportedInCurrentRegionWithWebService:(id)arg1 completion:(id /* block */)arg2;
+ (void)shouldShowPasscodeAccessibilityOverride:(id)arg1 completion:(id /* block */)arg2;
+ (void)shouldShowWalletInBuddy:(id)arg1 completion:(id /* block */)arg2;
+ (void)shouldShowWalletInSettings:(id)arg1 completion:(id /* block */)arg2;

@end
