/* Generated by EzioChiu
   Image: /usr/lib/libapplist.dylib
 */

@interface ALApplicationList : NSObject

@property (nonatomic, readonly) NSDictionary *applications;

+ (void)initialize;
+ (id)sharedApplicationList;

- (long long)applicationCount;
- (bool)applicationWithDisplayIdentifierIsHidden:(id)arg1;
- (id)applications;
- (id)applicationsFilteredUsingPredicate:(id)arg1;
- (id)applicationsFilteredUsingPredicate:(id)arg1 onlyVisible:(bool)arg2 titleSortedIdentifiers:(id*)arg3;
- (struct CGImage { }*)copyIconOfSize:(unsigned long long)arg1 forDisplayIdentifier:(id)arg2;
- (id)description;
- (void)didReceiveMemoryWarning;
- (bool)hasCachedIconOfSize:(unsigned long long)arg1 forDisplayIdentifier:(id)arg2;
- (id)iconOfSize:(unsigned long long)arg1 forDisplayIdentifier:(id)arg2;
- (id)init;
- (void)postNotificationWithUserInfo:(id)arg1;
- (id)valueForKey:(id)arg1 forDisplayIdentifier:(id)arg2;
- (id)valueForKeyPath:(id)arg1 forDisplayIdentifier:(id)arg2;

@end
