/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.SearchAdAction : AppStoreKit.Action {
    void action;
    void searchAd;
}

@end
