/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.BasePresenter : _TtCs12_SwiftObject {
    void advertRotationData;
    void impressionsCatalogue;
    void isUpdating;
    void metricsPage;
    void metricsPipeline;
    void pageContext;
    void pageEnterGate;
    void pendingPageRender;
    void referrer;
    void storeDataProvider;
}

@end
