/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.JSPackageProvisioner : _TtCs12_SwiftObject {
    void fetcher;
}

@end
