/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.OpenAppAction : AppStoreKit.Action {
    void adamId;
    void destination;
}

@end
