/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.SearchResultsPresenter : AppStoreKit.BasePresenter {
    void facetSetsView;
    void facetValuesView;
    void facets;
    void isAutoPlayEnabled;
    void isNetworkConstrained;
    void isPreparingNextPage;
    void metricsEventTimer;
    void nextPage;
    void results;
    void searchAdsDataProvider;
    void searchEntity;
    void searchOrigin;
    void term;
    void transparencyLink;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  url;
    void view;
}

@end
