/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.EditorialSearchResult : _TtCs12_SwiftObject {
    void artworkGridType;
    void clickAction;
    void collectionAdamIds;
    void collectionAppIcons;
    void editorialArtwork;
    void editorialVideo;
    void iconArtwork;
    void impressionMetrics;
    void subtitle;
    void tagline;
    void title;
    void type;
}

@end
