/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.TopChartSegment : AppStoreKit.BasePage {
    void longName;
    void nextPage;
    void pageMetrics;
    void shelves;
    void shortName;
}

@end
