/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.ProductPageSection : _TtCs12_SwiftObject {
    void shelfId;
    void type;
}

@end
