/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.TodayCardMediaVideo : AppStoreKit.TodayCardMedia {
    void description;
    void video;
}

@end
