/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.AlertAction : AppStoreKit.Action {
    void buttonActions;
    void isCancelable;
    void message;
    void style;
}

@end
