/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ContentKit.framework/ContentKit
 */

@interface WFEvent : NSObject

+ (Class)codableEventClass;
+ (id)serializablePropertyTransformers;

- (Class)codableEventClass;
- (id)propertyNames;
- (id)serializableEvent;
- (void)track;
- (void)trackWithCount:(int)arg1;

@end
