/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ContentKit.framework/ContentKit
 */

@interface WFMPMediaLibraryFiltering : WFContentLibraryFiltering

+ (Class)objectClass;
+ (void)performCustomFilteringUsingComparisonPredicates:(id)arg1 resultHandler:(id /* block */)arg2;

@end
