/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/IMSharedUtilities.framework/IMSharedUtilities
 */

@interface IMIDSUtilities : NSObject

+ (int)verifyFromID:(id)arg1 comesFromAccount:(id)arg2;

@end
