/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/CoreSuggestionsInternals
 */

@interface SGReminderExtractionModel : NSObject {
    _PASNotificationToken * _assetUpdateToken;
    NSDictionary * _enrichments;
    NSDictionary * _inputTokenMapping;
    NSDictionary * _outputConfig;
    NSDictionary * _reminderOverrides;
    NSRegularExpression * _whitelistRegex;
}

+ (id)compileModelAtPath:(id)arg1 toCompiledPath:(id)arg2;
+ (id)currentModelName;
+ (id)currentModelURL;
+ (id)enrichTaggedCharacterRangesWithModelOutput:(id)arg1 usingInputCharacterRanges:(id)arg2;
+ (id)inputFromTaggedCharacterRanges:(id)arg1 usingTokenMapping:(id)arg2;
+ (id)loadLazyPlistWithBasename:(id)arg1;
+ (id)sharedInstance;

- (void).cxx_destruct;
- (id)_init;
- (struct _NSRange { unsigned long long x1; unsigned long long x2; })_whitelistedVerbRangeInContent:(id)arg1;
- (id)argMaxForLastOutput:(id)arg1;
- (id)argMaxForOutputIndex:(id)arg1 index:(int)arg2 shape:(id)arg3;
- (id)argMaxForSequence:(id)arg1;
- (void)dealloc;
- (id)enrichments;
- (bool)hasWhitelistedVerbInContent:(id)arg1;
- (id)loadModel;
- (id)modelInferences:(id)arg1;
- (id)reminderOverrides;
- (void)updateAll;
- (id)whitelistedVerbInContent:(id)arg1;

@end
