/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/CoreSuggestionsInternals
 */

@interface SGTopicDissector : SGPipelineDissector {
    unsigned long long  _blacklistHash;
    CKContextClient * _contextClient;
    bool  _significanceCheckEnabled;
    PPTextToTopicTransform * _transform;
}

+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)_collectHighLevelTopicsWithText:(id)arg1 bundleId:(id)arg2 addTopic:(id /* block */)arg3 weight:(double)arg4;
- (void)_collectTopicsFromContextKitWithText:(id)arg1 isPlainText:(bool)arg2 bundleId:(id)arg3 addTopic:(id /* block */)arg4 weight:(double)arg5;
- (unsigned long long)_hashForBlacklist:(id)arg1;
- (void)_registerContextBlacklistCheck;
- (void)checkBlacklist;
- (void)dissectInternal:(id)arg1 inContext:(id)arg2;
- (id)extractionsFromContextKitWithText:(id)arg1 isPlainText:(bool)arg2 bundleId:(id)arg3 weight:(double)arg4;
- (id)init;
- (id)initWithContextClient:(id)arg1 significanceCheckEnabled:(bool)arg2;
- (id)initWithSignificanceCheckEnabled:(bool)arg1;
- (id)topicsInText:(id)arg1 isPlainText:(bool)arg2 source:(id)arg3 cloudSync:(bool)arg4 algorithms:(id)arg5 weight:(double)arg6;

@end
