/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TrackingAvoidance.framework/TrackingAvoidance
 */

@interface TAVisitState : NSObject {
    NSMutableDictionary * _importantLois;
    TACircularBuffer * _interVisitMetricSnapshotBuffer;
    TAInterVisitMetricsSnapshot * _interVisitMetricsSnapshotBackup;
    NSHashTable * _observers;
    TACircularBuffer * _poiSnapshotBuffer;
    TAScanRequest * _scanRequest;
    TAVisitStateSettings * _settings;
    unsigned long long  _state;
}

@property (nonatomic, readonly) NSMutableDictionary *importantLois;
@property (nonatomic, readonly) TACircularBuffer *interVisitMetricSnapshotBuffer;
@property (nonatomic, readonly) TACircularBuffer *poiSnapshotBuffer;
@property (nonatomic, readonly) unsigned long long state;

+ (id)visitStateTypeToString:(unsigned long long)arg1;

- (void).cxx_destruct;
- (void)addObserver:(id)arg1;
- (void)closeInterVisitBackupSnapshotWithStore:(id)arg1 date:(id)arg2;
- (void)closeLatestInterVisitSnapshotWithStore:(id)arg1 date:(id)arg2;
- (void)closeVisitSnapshotWithStore:(id)arg1 visit:(id)arg2;
- (id)description;
- (unsigned long long)evaluateLatestVisitSnapshotAndRecoverIfNecessary;
- (id)getDisplayEventsWithFirstPrecedingInInterval:(id)arg1 store:(id)arg2;
- (id)importantLois;
- (void)ingestTAEvent:(id)arg1 store:(id)arg2 appendOutgoingRequestsTo:(id)arg3;
- (id)initWithSettings:(id)arg1 scanRequestSettings:(id)arg2;
- (id)interVisitMetricSnapshotBuffer;
- (void)issueInterVisitScanRequestIfNecessaryWithClosedSnapshot:(id)arg1 store:(id)arg2 andAppendOutgoingRequestsTo:(id)arg3;
- (void)issueVisitEntryScanRequestIfNecessaryWithOpenSnapshot:(id)arg1 clock:(id)arg2 andAppendOutgoingRequestsTo:(id)arg3;
- (void)labelLoiTypeForLastVisitSnapshot:(id)arg1;
- (void)notifyObserversOfMetricsHint:(unsigned long long)arg1;
- (void)notifyObserversOfStateChangeFromState:(unsigned long long)arg1 toState:(unsigned long long)arg2;
- (void)openInterVisitBackupSnapshotWithArrivalVisit:(id)arg1;
- (void)openInterVisitSnapshotWithDepartureVisit:(id)arg1;
- (void)openVisitSnapshotWithStore:(id)arg1 visit:(id)arg2 andAppendOutgoingRequestsTo:(id)arg3;
- (void)performStateTransitionDecision:(unsigned long long)arg1 store:(id)arg2 visit:(id)arg3 andAppendOutgoingRequestsTo:(id)arg4;
- (id)poiSnapshotBuffer;
- (void)purgeInterVisitSnapshotBufferWithCurrentDate:(id)arg1;
- (void)purgeVisitSnapshotBufferWithCurrentDate:(id)arg1;
- (void)purgeWithClock:(id)arg1;
- (void)removeObserver:(id)arg1;
- (void)resetInterVisitBackupSnapshot;
- (bool)setState:(unsigned long long)arg1;
- (unsigned long long)state;
- (unsigned long long)stateTransitionDecisionGivenTACLVisit:(id)arg1;
- (void)updateImportantLOIs:(id)arg1 currentDate:(id)arg2;
- (void)updateInterVisitBackupSnapshotWithStore:(id)arg1;
- (void)updateInterVisitSnapshot:(id)arg1 store:(id)arg2;
- (void)updateInterVisitSnapshotWithStore:(id)arg1;

@end
