/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ActivityAchievements.framework/ActivityAchievements
 */

@interface ACHVisibilityEnvironment : NSObject

- (id)valueForUndefinedKey:(id)arg1;

@end
