/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit
 */

@interface WFRealmDatabaseConfiguration : NSObject {
    RLMRealmConfiguration * _realmConfiguration;
}

@property (nonatomic, readonly) RLMRealmConfiguration *realmConfiguration;

+ (id)inMemoryConfiguration;
+ (id)inMemoryConfigurationWithIdentifier:(id)arg1;
+ (id)systemShortcutsConfiguration;

- (void).cxx_destruct;
- (id)realmConfiguration;

@end
