/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit
 */

@interface WFSharingSettings : NSObject

+ (id)sharingDisabledAlertWithWorkflowName:(id)arg1;
+ (bool)sharingEnabled;
+ (id)shortcutFileSharingDisabledAlert;
+ (bool)shortcutFileSharingEnabled;

@end
