/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit
 */

@interface WFTableTemplateParameter : WFParameter {
    Class  _contentItemClass;
}

@property (nonatomic, readonly, copy) id additionalRowSerializedRepresentation;
@property (nonatomic, readonly) Class contentItemClass;

- (void).cxx_destruct;
- (id)additionalRowSerializedRepresentation;
- (Class)contentItemClass;
- (id)defaultSerializedRepresentation;
- (id)defaultSupportedVariableTypes;
- (id)initWithDefinition:(id)arg1;
- (Class)singleStateClass;
- (bool)supportsImportQuestions;

@end
