/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit
 */

@interface WFTimeIntervalParameter : WFParameter

- (id)defaultSupportedVariableTypes;
- (Class)singleStateClass;

@end
