/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit
 */

@interface WFWorkflowCreationOptions : NSObject {
    bool  _deleted;
    NSString * _identifier;
    unsigned long long  _location;
    WFWorkflowRecord * _record;
}

@property (nonatomic) bool deleted;
@property (nonatomic, copy) NSString *identifier;
@property (nonatomic) unsigned long long location;
@property (nonatomic, readonly) WFWorkflowRecord *record;

- (void).cxx_destruct;
- (bool)deleted;
- (id)identifier;
- (id)init;
- (id)initWithRecord:(id)arg1;
- (unsigned long long)location;
- (id)record;
- (void)setDeleted:(bool)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setLocation:(unsigned long long)arg1;

@end
