/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit
 */

@interface WFWorkflowPickerParameter : WFEnumerationParameter {
    NSArray * _possibleStates;
}

- (void).cxx_destruct;
- (id)possibleStates;
- (Class)singleStateClass;

@end
