/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthRecordsUI.framework/HealthRecordsUI
 */

@interface HealthRecordsUI.AccountIconProvider : _TtCs12_SwiftObject {
    void brandImageManager;
    void iconCache;
    void monogramProvider;
}

@end
