/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthRecordsUI.framework/HealthRecordsUI
 */

@interface HealthRecordsUI.CategoryViewControllerManager : _TtCs12_SwiftObject {
    void activeCategoryViewController;
}

@end
