/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CloudKitDaemon.framework/CloudKitDaemon
 */

@interface CKDMarkAssetBrokenURLRequestWrapperOperation : CKDOperation {
    CKDMarkAssetBrokenURLRequest * _urlRequest;
}

@property (nonatomic, retain) CKDMarkAssetBrokenURLRequest *urlRequest;

- (void).cxx_destruct;
- (id)activityCreate;
- (void)main;
- (void)setUrlRequest:(id)arg1;
- (bool)shouldCheckAppVersion;
- (id)urlRequest;

@end
