/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKLargeTitleAccessoryView : UIView {
    UIButton * _leftAccessoryButton;
    UIButton * _rightAccessoryButton;
}

@property (nonatomic, retain) UIButton *leftAccessoryButton;
@property (nonatomic, retain) UIButton *rightAccessoryButton;

+ (id)newComposeButton;
+ (id)newOptionsButton;

- (void).cxx_destruct;
- (struct CGSize { double x1; double x2; })_intrinsicSizeWithinSize:(struct CGSize { double x1; double x2; })arg1;
- (void)layoutSubviews;
- (id)leftAccessoryButton;
- (id)rightAccessoryButton;
- (void)setLeftAccessoryButton:(id)arg1;
- (void)setRightAccessoryButton:(id)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;

@end
