/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKReviewLargeVideoAttachmentsViewController : CKReviewLargeAttachmentsViewController

- (id)attachmentClass;
- (id)navigationBarTitle;

@end
