/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKUnreadCountChatItem : CKMultilineStampChatItem

- (Class)cellClass;
- (id)loadTranscriptText;

@end
