/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/KnowledgeGraphKit.framework/KnowledgeGraphKit
 */

@interface KnowledgeGraphKit.MAMultinomialNaiveBayesClassifier : KnowledgeGraphKit.MANaiveBayesClassifier

@end
