/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/KnowledgeGraphKit.framework/KnowledgeGraphKit
 */

@interface KnowledgeGraphKit.MASparseSquareMatrixRepresentation : _TtCs12_SwiftObject {
    void matrix;
    void nodes;
}

@end
