/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/KnowledgeGraphKit.framework/KnowledgeGraphKit
 */

@interface MANode : MAElement {
    NSMutableArray * _edges;
}

- (void).cxx_destruct;
- (void)_addEdge:(id)arg1;
- (id)_anyEdgeWithOppositeNode:(id)arg1 type:(unsigned long long)arg2;
- (id)_edgesWithOppositeNode:(id)arg1 type:(unsigned long long)arg2;
- (void)_enumerateEdgesOfType:(unsigned long long)arg1 usingBlock:(id /* block */)arg2;
- (void)_enumerateEdgesWithDomains:(id)arg1 usingBlock:(id /* block */)arg2;
- (void)_enumerateEdgesWithLabel:(id)arg1 domain:(unsigned short)arg2 usingBlock:(id /* block */)arg3;
- (void)_enumerateNeighborNodesWithLabel:(id)arg1 domain:(unsigned short)arg2 usingBlock:(id /* block */)arg3;
- (bool)_hasEdgesWithOppositeNode:(id)arg1 type:(unsigned long long)arg2;
- (unsigned long long)_memoryFootprint:(id)arg1;
- (void)_removeAllPersistentStoreProperties;
- (void)_removeEdge:(id)arg1;
- (void)_removePersistentStorePropertyForKey:(id)arg1;
- (void)_setPersistentStoreProperties:(id)arg1;
- (void)_setPersistentStorePropertyValue:(id)arg1 forKey:(id)arg2;
- (id)allEdges;
- (id)anyEdgeFromNode:(id)arg1;
- (id)anyEdgeTowardNode:(id)arg1;
- (id)anyEdgeWithLabel:(id)arg1;
- (id)anyEdgeWithLabel:(id)arg1 domain:(unsigned short)arg2;
- (id)anyEdgeWithNode:(id)arg1;
- (id)anyNeighborNodeThroughEdgesWithLabel:(id)arg1;
- (id)anyNeighborNodeThroughEdgesWithLabel:(id)arg1 domain:(unsigned short)arg2;
- (id)anyNeighborNodeThroughInEdges;
- (id)anyNeighborNodeThroughInEdgesWithLabel:(id)arg1 domain:(unsigned short)arg2;
- (id)anyNeighborNodeThroughOutEdges;
- (id)anyNeighborNodeThroughOutEdgesWithLabel:(id)arg1 domain:(unsigned short)arg2;
- (id)associatedNodesForRemoval;
- (id)commonNeighborNodesThroughEdgesWithNode:(id)arg1;
- (id)commonNeighborNodesThroughInEdgesWithNode:(id)arg1;
- (id)commonNeighborNodesThroughOutEdgesWithNode:(id)arg1;
- (id)commonNeighborNodesWithNode:(id)arg1;
- (bool)conformsToNodeSchema:(id)arg1;
- (unsigned long long)countOfEdgesWithLabel:(id)arg1;
- (unsigned long long)countOfEdgesWithLabel:(id)arg1 domain:(unsigned short)arg2;
- (id)description;
- (unsigned long long)edgesCount;
- (id)edgesForLabel:(id)arg1;
- (id)edgesForLabel:(id)arg1 domain:(unsigned short)arg2;
- (id)edgesFromNode:(id)arg1;
- (id)edgesTowardNode:(id)arg1;
- (id)edgesWithNode:(id)arg1;
- (void)enumerateEdgesOfType:(unsigned long long)arg1 usingBlock:(id /* block */)arg2;
- (void)enumerateEdgesUsingBlock:(id /* block */)arg1;
- (void)enumerateEdgesWithDomains:(id)arg1 usingBlock:(id /* block */)arg2;
- (void)enumerateEdgesWithLabel:(id)arg1 domain:(unsigned short)arg2 usingBlock:(id /* block */)arg3;
- (void)enumerateEdgesWithLabel:(id)arg1 usingBlock:(id /* block */)arg2;
- (void)enumerateInEdgesUsingBlock:(id /* block */)arg1;
- (void)enumerateNeighborNodesThroughEdgesWithDomains:(id)arg1 usingBlock:(id /* block */)arg2;
- (void)enumerateNeighborNodesThroughEdgesWithLabel:(id)arg1 domain:(unsigned short)arg2 usingBlock:(id /* block */)arg3;
- (void)enumerateNeighborNodesThroughEdgesWithLabel:(id)arg1 usingBlock:(id /* block */)arg2;
- (void)enumerateNeighborNodesThroughInEdgesUsingBlock:(id /* block */)arg1;
- (void)enumerateNeighborNodesThroughOutEdgesUsingBlock:(id /* block */)arg1;
- (void)enumerateNeighborNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateNeighborNodesWithLabel:(id)arg1 domain:(unsigned short)arg2 usingBlock:(id /* block */)arg3;
- (void)enumerateOutEdgesUsingBlock:(id /* block */)arg1;
- (void)enumerateSiblingNodesThroughEdgesWithDomains:(id)arg1 usingBlock:(id /* block */)arg2;
- (void)enumerateSiblingNodesThroughEdgesWithLabel:(id)arg1 domain:(unsigned short)arg2 usingBlock:(id /* block */)arg3;
- (void)enumerateSiblingNodesThroughEdgesWithLabel:(id)arg1 usingBlock:(id /* block */)arg2;
- (bool)hasEdge:(id)arg1 isIn:(bool*)arg2;
- (bool)hasEdgeFromNode:(id)arg1;
- (bool)hasEdgeTowardNode:(id)arg1;
- (bool)hasEdgeWithLabel:(id)arg1;
- (bool)hasEdgeWithLabel:(id)arg1 domain:(unsigned short)arg2;
- (bool)hasEdgeWithNode:(id)arg1;
- (unsigned long long)inEdgesCount;
- (id)init;
- (bool)isEqualToNode:(id)arg1;
- (bool)isNode;
- (bool)isOrphan;
- (bool)isUnique;
- (id)neighborNodes;
- (id)neighborNodesThroughEdgesWithLabel:(id)arg1;
- (id)neighborNodesThroughEdgesWithLabel:(id)arg1 domain:(unsigned short)arg2;
- (id)neighborNodesThroughInEdges;
- (id)neighborNodesThroughOutEdges;
- (id)neighborNodesWithLabel:(id)arg1 domain:(unsigned short)arg2;
- (unsigned long long)outEdgesCount;
- (id)shortDescription;
- (id)shortestPathToNode:(id)arg1 directed:(bool)arg2;
- (id)siblingNodesThroughEdgesWithLabel:(id)arg1;
- (id)siblingNodesThroughEdgesWithLabel:(id)arg1 domain:(unsigned short)arg2;
- (id)visualString;
- (id)visualStringWithName:(id)arg1;
- (id)visualStringWithName:(id)arg1 andPropertyKeys:(id)arg2;

@end
