/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHCenterAppSuspendSettings : SBHCenterAppZoomSettings

- (void)setDefaultValues;

@end
