/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHUnlockSettings : SBHCenterAppSuspendSettings

+ (id)settingsControllerModule;

- (void)setDefaultValues;

@end
