/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Transparency.framework/Transparency
 */

@interface ConsistencyProofResponse_LogConsistencyResponse : GPBMessage <TransparencyVerifiable>

@property (nonatomic) int application;
@property (retain) TransparencyManagedDataStore *dataStore;
@property (nonatomic, retain) SignedLogHead *endSlh;
@property (nonatomic) bool hasEndSlh;
@property (nonatomic) bool hasStartSlh;
@property (nonatomic) int logType;
@property (nonatomic, retain) NSMutableArray *proofHashesArray;
@property (nonatomic, readonly) unsigned long long proofHashesArray_Count;
@property (retain) NSNumber *startRevision;
@property (nonatomic, retain) SignedLogHead *startSlh;
@property (retain) TransparencyConsistencyProofVerifier *verifier;

+ (id)descriptor;

- (id)dataStore;
- (void)setDataStore:(id)arg1;
- (void)setResult:(bool)arg1 treeHead:(id)arg2 error:(id)arg3;
- (void)setStartRevision:(id)arg1;
- (void)setVerifier:(id)arg1;
- (id)startRevision;
- (id)verifier;
- (bool)verifyWithError:(id*)arg1;

@end
