/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Transparency.framework/Transparency
 */

@interface GPBFloatValue : GPBMessage

@property (nonatomic) float value;

+ (id)descriptor;

@end
