/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Transparency.framework/Transparency
 */

@interface KTTreeHead : NSManagedObject

@property (nonatomic, copy) NSString *application;
@property (nonatomic, retain) NSSet *failures;
@property (nonatomic) long long logBeginTime;
@property (nonatomic, retain) NSData *logHeadHash;
@property (nonatomic) long long logType;
@property (nonatomic) double receiptTime;
@property (nonatomic) long long revision;
@property (nonatomic) long long signatureVerified;
@property (nonatomic, retain) NSData *sth;
@property (nonatomic) long long verificationResult;

+ (id)fetchRequest;

@end
