/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Transparency.framework/Transparency
 */

@interface LeavesRequest : GPBMessage

@property (nonatomic) int application;
@property (nonatomic) unsigned long long endNodePosition;
@property (nonatomic) int logType;
@property (nonatomic) unsigned long long startNodePosition;
@property (nonatomic) int version;

+ (id)descriptor;

@end
