/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Transparency.framework/Transparency
 */

@interface TransparencyResponse : NSObject {
    NSData * _data;
    NSDictionary * _metadata;
    TransparencyRequest * _request;
}

@property (retain) NSData *data;
@property (retain) NSDictionary *metadata;
@property (retain) TransparencyRequest *request;

- (void).cxx_destruct;
- (id)data;
- (id)initWithRequest:(id)arg1 responseData:(id)arg2 metadata:(id)arg3;
- (id)metadata;
- (id)request;
- (id)serverHint;
- (void)setData:(id)arg1;
- (void)setMetadata:(id)arg1;
- (void)setRequest:(id)arg1;

@end
