/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.MagazineCategoriesBlueprintLayoutBuilder : _TtCs12_SwiftObject {
    void magazineCategoryViewLayoutAttributesFactory;
}

@end
