/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.FeatureAvailability : _TtCs12_SwiftObject {
    void appConfiguration;
    void privateDataContext;
}

@end
