/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ChannelPromotedArticlesService : _TtCs12_SwiftObject {
    void headlineService;
    void tagService;
}

@end
