/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.SearchMoreViewCellProvider : _TtCs12_SwiftObject {
    void delegate;
    void imageOnSideRenderer;
    void noImageRenderer;
    void tagViewRenderer;
    void wrappedImageOnSideRenderer;
}

@end
