/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.HeadlineService : _TtCs12_SwiftObject {
    void appConfigurationManager;
    void context;
    void headlineModelFactory;
    void headlineServiceOperationQueue;
    void queryTimeRangeProvider;
    void tagService;
}

@end
