/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.SearchMoreEventHandler : _TtCs12_SwiftObject {
    void delegate;
    void interactor;
    void router;
    void searchContentType;
}

@end
