/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.SubscriptionsStartupTask : _TtCs12_SwiftObject {
    void bundlePurchasePrewarmer;
    void familySharingStatusManager;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  group;
    void manageSubscriptionsURLProvider;
}

@end
