/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface TSAppDelegate : UIResponder <UIApplicationDelegate> {
    void $__lazy_storage_$_menuManager;
    void resolver;
    void sessionObserver;
    void window;
    void windowToolbarManager;
}

@property (nonatomic, retain) UIWindow *window;

- (void).cxx_destruct;
- (bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (void)application:(id)arg1 performFetchWithCompletionHandler:(id /* block */)arg2;
- (bool)application:(id)arg1 willFinishLaunchingWithOptions:(id)arg2;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)bootstrapWithApplication:(id)arg1;
- (void)bootstrapWithContainer:(id)arg1 application:(id)arg2;
- (void)bootstrapWithWindow:(id)arg1 application:(id)arg2;
- (id)init;
- (void)setWindow:(id)arg1;
- (id)window;

@end
