/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface TSRendererAssembly : NSObject <NFAssembly>

- (id)init;
- (void)loadInRegistry:(id)arg1;

@end
