/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
 */

@interface NCNotificationManagementSuggestionContentProvider : NCNotificationManagementContentProvider <NCNotificationManagementSuggestionContentProviding> {
    bool  _auxiliaryOptionsVisible;
    unsigned long long  _numberOfOptionButtons;
    NSString * _optionsSummaryText;
    <NCNotificationManagementSuggestionDelegate> * _suggestionDelegate;
}

@property (nonatomic) bool auxiliaryOptionsVisible;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) unsigned long long numberOfOptionButtons;
@property (nonatomic, copy) NSString *optionsSummaryText;
@property (nonatomic, readonly, copy) NSString *optionsSummaryTitle;
@property (nonatomic) <NCNotificationManagementSuggestionDelegate> *suggestionDelegate;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (bool)auxiliaryOptionsVisible;
- (void)configureOptionButtons:(id)arg1;
- (id)initWithNotificationRequest:(id)arg1 bundleDisplayName:(id)arg2 managementDelegate:(id)arg3 suggestionDelegate:(id)arg4;
- (void)logSuggestionResponse:(long long)arg1;
- (unsigned long long)numberOfOptionButtons;
- (id)optionsSummaryText;
- (void)setAuxiliaryOptionsVisible:(bool)arg1;
- (void)setNumberOfOptionButtons:(unsigned long long)arg1;
- (void)setOptionsSummaryText:(id)arg1;
- (void)setSuggestionDelegate:(id)arg1;
- (id)suggestionDelegate;

@end
