/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
 */

@interface NCNotificationManagementLongLookContentProvider : NCNotificationManagementContentProvider

- (void)configureOptionButtons:(id)arg1;

@end
