/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
 */

@interface NCNotificationManagementQuietingSuggestionContentProvider : NCNotificationManagementSuggestionContentProvider

- (void)configureOptionButtons:(id)arg1;
- (void)handleKeepAction:(id)arg1;
- (id)initWithNotificationRequest:(id)arg1 bundleDisplayName:(id)arg2 managementDelegate:(id)arg3 suggestionDelegate:(id)arg4;
- (void)logSuggestionResponse:(long long)arg1;

@end
