/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SystemStatusServer.framework/SystemStatusServer
 */

@interface STStatusDomainPublisherXPCClientHandle : NSObject <STStatusDomainPublisherXPCServer> {
    NSXPCConnection * _clientXPCConnection;
    BSMutableIntegerMap * _dataByDomain;
    NSSet * _entitledDomains;
    NSObject<OS_dispatch_queue> * _internalQueue;
    <STStatusDomainPublisherServerHandle> * _serverHandle;
}

@property (nonatomic, readonly) NSXPCConnection *clientXPCConnection;
@property (nonatomic, readonly) BSMutableIntegerMap *dataByDomain;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSSet *entitledDomains;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *internalQueue;
@property (nonatomic, readonly) <STStatusDomainPublisherServerHandle> *serverHandle;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_internalQueue_dataForDomainCreatingIfNecessary:(unsigned long long)arg1;
- (id)_newEmptyDataForDomain:(unsigned long long)arg1;
- (void)_publishData:(id)arg1 forDomain:(unsigned long long)arg2;
- (void)_publishDataDiff:(id)arg1 forDomain:(unsigned long long)arg2;
- (id)clientXPCConnection;
- (id)dataByDomain;
- (id)entitledDomains;
- (id)initWithXPCConnection:(id)arg1 serverHandle:(id)arg2;
- (id)internalQueue;
- (void)publishBatteryData:(id)arg1;
- (void)publishBatteryDataDiff:(id)arg1;
- (void)publishTelephonyData:(id)arg1;
- (void)publishTelephonyDataDiff:(id)arg1;
- (void)publishVoiceControlData:(id)arg1;
- (void)publishVoiceControlDataDiff:(id)arg1;
- (void)publishWifiData:(id)arg1;
- (void)publishWifiDataDiff:(id)arg1;
- (id)serverHandle;

@end
