/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthVisualization.framework/HealthVisualization
 */

@interface HealthVisualization.AllInsightsViewController : HealthExperienceUI.DataTypeDetailViewController

- (id)initWithCoder:(id)arg1;
- (id)initWithCollectionViewLayout:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;

@end
