/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthVisualization.framework/HealthVisualization
 */

@interface HealthVisualization.DiagramDateAxisMetricsCalculator : _TtCs12_SwiftObject

@end
