/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CarPlayUIServices.framework/CarPlayUIServices
 */

@interface CRSUIMutableDashboardWidgetSceneSettings : UIMutableApplicationSceneSettings <CRSUIDashboardWidgetSceneSettings>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, copy) NSObject<OS_xpc_object> *endpoint;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic) unsigned long long widgetStyle;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)endpoint;
- (void)setEndpoint:(id)arg1;
- (void)setWidgetStyle:(unsigned long long)arg1;
- (unsigned long long)widgetStyle;

@end
