/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface POPStaticAnimatableProperty : POPAnimatableProperty {
    struct { id x1; id /* block */ x2; id /* block */ x3; double x4; } * _state;
}

- (id)name;
- (id /* block */)readBlock;
- (double)threshold;
- (id /* block */)writeBlock;

@end
