/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFActionDescriptionViewController : UIViewController <UIScrollViewDelegate, WFActionDocumentationViewDelegate, WFActionDrawerStateConfigurable, WFActionDrawerStateRepresentable> {
    UIVisualEffectView * _blurView;
    <WFActionDescriptionViewControllerDelegate> * _delegate;
    UIButton * _dismissButton;
    WFActionDocumentationView * _documentationView;
    UIScrollView * _scrollView;
    WFActionDescriptionTitleView * _titleView;
}

@property (nonatomic) WFAction *action;
@property (nonatomic) UIVisualEffectView *blurView;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <WFActionDescriptionViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) UIButton *dismissButton;
@property (nonatomic, readonly) WFActionDocumentationView *documentationView;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) UIScrollView *scrollView;
@property (nonatomic, readonly) WFActionDrawerState *state;
@property (readonly) Class superclass;
@property (nonatomic, readonly) WFActionDescriptionTitleView *titleView;

- (void).cxx_destruct;
- (id)action;
- (void)actionDocumentationViewDidSelectAddToWorkflowWithAction:(id)arg1;
- (id)blurView;
- (id)delegate;
- (id)dismissButton;
- (id)documentationView;
- (id)init;
- (bool)moveToState:(id)arg1 animated:(bool)arg2;
- (id)scrollView;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint { double x1; double x2; })arg2 targetContentOffset:(inout struct CGPoint { double x1; double x2; }*)arg3;
- (void)setAction:(id)arg1;
- (void)setBlurView:(id)arg1;
- (void)setDelegate:(id)arg1;
- (id)state;
- (id)titleView;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;

@end
