/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFCKButtonComponentConfiguration : NSObject {
    struct array<CKStateConfiguration, 8> { 
        struct CKStateConfiguration { 
            NSString *title; 
            NSAttributedString *attributedTitle; 
            UIColor *titleColor; 
            UIImage *image; 
            UIImage *backgroundImage; 
        } __elems_[8]; 
    }  _configurations;
    unsigned long long  _precomputedHash;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;

@end
