/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFContactTextView : WFPlaceholderTextView <WFTextField> {
    NSSet * _allowedVariableTypes;
    bool  _allowsTextEntry;
    NSSet * _supportedPersonProperties;
    unsigned long long  _syntaxHighlightingType;
    id /* block */  _variableBlock;
    WFVariableInputCoordinator * _variableCoordinator;
    <WFVariableProvider> * _variableProvider;
    <WFVariableUIDelegate> * _variableUIDelegate;
    bool  _variablesDisabled;
}

@property (nonatomic, copy) NSSet *allowedVariableTypes;
@property (nonatomic) bool allowsTextEntry;
@property (nonatomic, copy) NSAttributedString *attributedText;
@property (nonatomic) long long autocapitalizationType;
@property (nonatomic) long long autocorrectionType;
@property (nonatomic, copy) UIColor *backgroundColor;
@property (nonatomic, readonly) UITextPosition *beginningOfDocument;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (getter=isEditable, nonatomic) bool editable;
@property (nonatomic) bool enablesReturnKeyAutomatically;
@property (nonatomic, readonly) UITextPosition *endOfDocument;
@property (nonatomic, retain) UIFont *font;
@property (nonatomic, readonly) bool hasText;
@property (readonly) unsigned long long hash;
@property (nonatomic) <UITextInputDelegate> *inputDelegate;
@property (nonatomic, readonly) id insertDictationResultPlaceholder;
@property (nonatomic) long long keyboardAppearance;
@property (nonatomic) long long keyboardType;
@property (nonatomic, readonly) UITextRange *markedTextRange;
@property (nonatomic, copy) NSDictionary *markedTextStyle;
@property (nonatomic, copy) UITextInputPasswordRules *passwordRules;
@property (nonatomic, copy) NSString *placeholder;
@property (nonatomic) long long returnKeyType;
@property (getter=isSecureTextEntry, nonatomic) bool secureTextEntry;
@property (copy) UITextRange *selectedTextRange;
@property (nonatomic) long long selectionAffinity;
@property (nonatomic) long long smartDashesType;
@property (nonatomic) long long smartInsertDeleteType;
@property (nonatomic) long long smartQuotesType;
@property (nonatomic) long long spellCheckingType;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSSet *supportedPersonProperties;
@property (nonatomic) unsigned long long syntaxHighlightingType;
@property (nonatomic, copy) NSString *text;
@property (nonatomic) long long textAlignment;
@property (nonatomic, retain) UIColor *textColor;
@property (nonatomic, copy) NSString *textContentType;
@property (nonatomic, readonly) UIView *textInputView;
@property (nonatomic, readonly) <UITextInputTokenizer> *tokenizer;
@property (nonatomic, copy) id /* block */ variableBlock;
@property (nonatomic, retain) WFVariableInputCoordinator *variableCoordinator;
@property (nonatomic) <WFVariableProvider> *variableProvider;
@property (nonatomic) <WFVariableUIDelegate> *variableUIDelegate;
@property (nonatomic) bool variablesDisabled;

- (void).cxx_destruct;
- (id)allowedVariableTypes;
- (bool)allowsTextEntry;
- (id)attributesByAddingTintColorToAttributes:(id)arg1;
- (id)attributesForPasting;
- (bool)becomeFirstResponder;
- (void)copy:(id)arg1;
- (void)cut:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 textContainer:(id)arg2;
- (void)paste:(id)arg1;
- (void)pasteAttributedString:(id)arg1;
- (bool)resignFirstResponder;
- (void)setAllowedVariableTypes:(id)arg1;
- (void)setAllowsTextEntry:(bool)arg1;
- (void)setAttributedText:(id)arg1;
- (void)setReturnKeyType:(long long)arg1;
- (void)setSupportedPersonProperties:(id)arg1;
- (void)setSyntaxHighlightingType:(unsigned long long)arg1;
- (void)setText:(id)arg1;
- (void)setVariableBlock:(id /* block */)arg1;
- (void)setVariableCoordinator:(id)arg1;
- (void)setVariableProvider:(id)arg1;
- (void)setVariableUIDelegate:(id)arg1;
- (void)setVariablesDisabled:(bool)arg1;
- (id)supportedPersonProperties;
- (unsigned long long)syntaxHighlightingType;
- (void)textDidChange:(id)arg1;
- (void)tintColorDidChange;
- (void)updateAllowedVariableTypes;
- (void)updateDoneButtonPresence;
- (void)updateTextAttachments;
- (void)updateTextContainerInsets;
- (id /* block */)variableBlock;
- (id)variableCoordinator;
- (id)variableProvider;
- (id)variableUIDelegate;
- (bool)variablesDisabled;

@end
