/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFConfirmationHUDPresenter : NSObject

+ (void)presentWithString:(id)arg1 fromViewController:(id)arg2;

@end
