/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFDimmingOverlayComponent : CKCompositeComponent

+ (id)newWithDimmingColor:(id)arg1 dimmingAlpha:(double)arg2 dimmingEnabled:(bool)arg3 component:(id)arg4;

@end
