/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFDictionaryEditorViewController : WFListEditorViewController

@property (nonatomic, readonly) WFDictionaryEditorView *editorView;

+ (Class)editorViewClass;

@end
