/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFModuleFooterComponent : CKCompositeComponent {
    NSURL * _link;
}

@property (nonatomic, retain) NSURL *link;

+ (id)newWithText:(id)arg1;

- (void).cxx_destruct;
- (id)link;
- (void)openLink;
- (void)setLink:(id)arg1;

@end
