/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFModuleComponentController : CKComponentController {
    <NSObject> * _inputVariableState;
}

- (void).cxx_destruct;
- (void)didMount;
- (void)didUpdateComponent;
- (void)loadIconIfNecessary;
- (void)willUpdateComponent;

@end
