/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFTableSection : NSObject <WFTreeObserver> {
    Class  _cellClass;
    long long  _cellStyle;
    id /* block */  _configurationBlock;
    NSString * _footerText;
    NSString * _headerText;
    NSMutableArray * _mutableItems;
    WFTableSectionTreeNode * _node;
}

@property (nonatomic, readonly) Class cellClass;
@property (nonatomic, readonly) long long cellStyle;
@property (nonatomic, readonly) id /* block */ configurationBlock;
@property (nonatomic, readonly) WFTableDataSource *dataSource;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSString *footerText;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSString *headerText;
@property (nonatomic, retain) NSArray *items;
@property (nonatomic, readonly) NSMutableArray *mutableItems;
@property (nonatomic, readonly) WFTableSectionTreeNode *node;
@property (readonly) Class superclass;

+ (id)section;
+ (id)sectionWithCellClass:(Class)arg1 representedObjects:(id)arg2 configurationBlock:(id /* block */)arg3;
+ (id)sectionWithItems:(id)arg1;
+ (id)sectionWithStyle:(long long)arg1 representedObjects:(id)arg2 configurationBlock:(id /* block */)arg3;

- (void).cxx_destruct;
- (void)addItem:(id)arg1;
- (Class)cellClass;
- (long long)cellStyle;
- (id /* block */)configurationBlock;
- (unsigned long long)currentIndex;
- (id)dataSource;
- (id)footerText;
- (id)headerText;
- (id)initWithCellClass:(Class)arg1 cellStyle:(long long)arg2 items:(id)arg3 representedObjects:(id)arg4 configurationBlock:(id /* block */)arg5;
- (void)insertItem:(id)arg1 atIndex:(unsigned long long)arg2;
- (bool)isEqual:(id)arg1;
- (id)items;
- (id)mutableItems;
- (id)node;
- (void)performBatchUpdates:(id /* block */)arg1;
- (unsigned long long)recursiveChildrenCount;
- (void)removeItem:(id)arg1;
- (void)removeItemAtIndex:(unsigned long long)arg1;
- (void)setFooterText:(id)arg1;
- (void)setHeaderText:(id)arg1;
- (void)setItems:(id)arg1;
- (void)setRepresentedObjects:(id)arg1;
- (id)tableView;
- (void)treeNode:(id)arg1 flattenedDescendentsDidChangeFrom:(id)arg2 to:(id)arg3 changeSource:(id)arg4;
- (void)updateCellForItem:(id)arg1;

@end
