/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFUIKitAlertPresenter : NSObject

+ (void)presentAlert:(id)arg1 withUserInterface:(id)arg2;

@end
