/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFWidgetOnboardingControllerContainer : NSObject

+ (id)newWidgetOnboardingController;
+ (void)setWidgetOnboardingControllerClass:(Class)arg1;

@end
