/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFWorkflowTypesHelpViewController : UIViewController <UIScrollViewDelegate> {
    NSString * _initialWorkflowType;
    UIPageControl * _pageControl;
    UIScrollView * _scrollView;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) NSString *initialWorkflowType;
@property (nonatomic) UIPageControl *pageControl;
@property (nonatomic) UIScrollView *scrollView;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)done;
- (id)initWithInitialWorkflowType:(id)arg1;
- (id)initialWorkflowType;
- (void)loadView;
- (id)pageControl;
- (struct CGSize { double x1; double x2; })preferredContentSize;
- (void)presentTodayWidgetOnboarding;
- (id)scrollView;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setInitialWorkflowType:(id)arg1;
- (void)setPageControl:(id)arg1;
- (void)setScrollView:(id)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidLayoutSubviews;

@end
