/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleMediaServicesUIDynamic.framework/AppleMediaServicesUIDynamic
 */

@interface AppleMediaServicesUIDynamic.PageActionDefinition : _TtCs12_SwiftObject {
    void actionModelType;
    void id;
}

@end
