/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleMediaServicesUIDynamic.framework/AppleMediaServicesUIDynamic
 */

@interface AppleMediaServicesUIDynamic.ActionPluginLoader : _TtCs12_SwiftObject {
    void actionDefinitionCache;
    void pluginLoader;
}

@end
