/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Tips.framework/Tips
 */

@interface TPSDiscoverabilitySignalsContextQueries : NSObject

+ (id)contextKey;
+ (id)keyPathForDiscoverabilitySignalsDataDictionary;
+ (id)signalsIDKey;
+ (id)sourceBundleIDKey;

@end
