/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Tips.framework/Tips
 */

@interface TPSVideoCacheController : TPSDataCacheController

+ (id)sharedInstance;

- (id)newDataCache;

@end
