/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VoiceTriggerUI.framework/VoiceTriggerUI
 */

@interface VTUIEnrollmentStateView : UIView <UIScrollViewDelegate> {
    _UIBackdropView * _backdropView;
    NSLayoutConstraint * _bottomFooterConstraint;
    VTUIButton * _finishEnrollmentButton;
    NSLayoutConstraint * _imageViewHeightCapConstraint;
    UILabel * _instructionLabel;
    struct CGSize { 
        double width; 
        double height; 
    }  _originalImageSize;
    NSLayoutConstraint * _readableLeftAnchorConstraint;
    NSLayoutConstraint * _readableRightAnchorConstraint;
    UIView * _scrollContainerView;
    UIScrollView * _scrollView;
    UIImageView * _smallestDeviceImageView;
    UILabel * _subtitleLabel;
    UILabel * _titleLabel;
    bool  _usingFallbackImage;
    UIView * _videoContainerView;
    NSLayoutConstraint * _videoHeightConstraint;
    NSURL * _videoURL;
    VTVideoView * _videoView;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) VTUIButton *finishEnrollmentButton;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSURL *videoURL;

- (void).cxx_destruct;
- (long long)_backdropStyle;
- (void)_positionFooter;
- (void)_setupUI;
- (void)cleanupPaneVideo;
- (void)fadeInSubviews;
- (id)finishEnrollmentButton;
- (id)footerView;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)layoutSubviews;
- (void)preparePaneVideo;
- (void)safeAreaInsetsDidChange;
- (void)setInstructionText:(id)arg1;
- (void)setPaneVideoPlaceholderImage:(id)arg1;
- (void)setSubtitle:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)setVideoURL:(id)arg1;
- (void)startPlayingVideo;
- (void)stopPlayingVideo;
- (bool)suppressFinishButton;
- (void)traitCollectionDidChange:(id)arg1;
- (void)updateConstraints;
- (id)videoURL;

@end
