/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Vision.framework/Vision
 */

@interface VNFaceprintGeneratorRevision1 : VNFaceprintGenerator

+ (int)clusteringConfidence;
+ (struct __CVBuffer { }*)cropFaceBoundingBoxFrom:(id)arg1 cropBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2 error:(id*)arg3;
+ (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })faceBoundingBox:(id)arg1;
+ (int (*)faceDescriptorCreator;
+ (void)frontalizer;
+ (int (*)getFaceJunkClassifier;
+ (int)imageType;
+ (float)magnifiedBBoxScaleFactor;
+ (id)modelPath;
+ (unsigned long long)numberOfChannels;
+ (unsigned int)pixelFormat;

@end
