/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Vision.framework/Vision
 */

@interface VNRecognizeTextRequest : VNImageBasedRequest <VNRequestProgressProviding> {
    bool  indeterminate;
    id /* block */  progressHandler;
}

@property (nonatomic, copy) NSArray *customWords;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) bool indeterminate;
@property (nonatomic) float minimumTextHeight;
@property (nonatomic, copy) id /* block */ progressHandler;
@property (nonatomic, copy) NSArray *recognitionLanguages;
@property (nonatomic) long long recognitionLevel;
@property (readonly) Class superclass;
@property (nonatomic) bool usesLanguageCorrection;

+ (Class)configurationClass;
+ (id)supportedRecognitionLanguagesForTextRecognitionLevel:(long long)arg1 revision:(unsigned long long)arg2 error:(id*)arg3;

- (void).cxx_destruct;
- (bool)_detectTextWithRequestPerformingContext:(id)arg1 requestRevision:(unsigned long long)arg2 error:(id*)arg3;
- (void)applyConfigurationOfRequest:(id)arg1;
- (id)customWords;
- (bool)hasCancellationHook;
- (bool)indeterminate;
- (id)initWithCompletionHandler:(id /* block */)arg1;
- (bool)internalPerformRevision:(unsigned long long)arg1 inContext:(id)arg2 error:(id*)arg3;
- (float)minimumTextHeight;
- (id /* block */)progressHandler;
- (id)recognitionLanguages;
- (long long)recognitionLevel;
- (id)sequencedRequestPreviousObservationsKey;
- (void)setCustomWords:(id)arg1;
- (void)setMinimumTextHeight:(float)arg1;
- (void)setProgressHandler:(id /* block */)arg1;
- (void)setRecognitionLanguages:(id)arg1;
- (void)setRecognitionLevel:(long long)arg1;
- (void)setUsesLanguageCorrection:(bool)arg1;
- (bool)usesLanguageCorrection;
- (bool)willAcceptCachedResultsFromRequestWithConfiguration:(id)arg1;

@end
