/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Vision.framework/Vision
 */

@interface VNSceneFeaturePrint : VNSceneprint

+ (unsigned long long)confidenceTypeForRevision:(unsigned long long)arg1;

@end
