/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Memories.framework/Memories
 */

@interface VEKDownloadStage : VEKPipelineStage {
    MiroCloudDownloader * _cloudDownloader;
    int  _downloadPolicy;
    VEKResult * _stageResults;
}

@property (nonatomic, retain) MiroCloudDownloader *cloudDownloader;
@property int downloadPolicy;
@property (nonatomic, retain) VEKResult *stageResults;

- (void).cxx_destruct;
- (void)_downloadAssets:(id)arg1 withCompletionHandler:(id /* block */)arg2;
- (id)cloudDownloader;
- (int)downloadPolicy;
- (id)inputTypes;
- (id)outputTypes;
- (id)runStageWithInput:(id)arg1;
- (void)setCloudDownloader:(id)arg1;
- (void)setDownloadPolicy:(int)arg1;
- (void)setStageResults:(id)arg1;
- (bool)shouldCancelOnNonLocalAssets;
- (id)stageResults;
- (void)tellPipelineThatItShouldCancelPlease;

@end
