/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MobileTimerUI.framework/MobileTimerUI
 */

@interface MTUIChevronTableViewCell : MTUIBaseTableViewCell

- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end
