/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBDisableAppStatusBarAlphaChangesAssertion : SBBaseStatusBarChangeAssertion

- (void)dealloc;
- (id)initWithReason:(id)arg1;
- (void)invalidate;

@end
