/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBEntityRemovalDosidoSlideOutUpwardAnimationSettings : SBEntityRemovalDosidoSlideOutAnimationSettings

@end
