/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBReduceMotionSwitcherModifier : SBSwitcherModifier

- (id)handleReduceMotionChangedEvent:(id)arg1;
- (double)homeScreenScale;
- (double)wallpaperScale;

@end
