/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBReduceMotionGridSwitcherModifier : SBGridSwitcherModifier

- (double)homeScreenScale;
- (double)wallpaperScale;

@end
