/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSimpleSTARTransaction : BSTransaction {
    id /* block */  _executeBlock;
}

@property (nonatomic, copy) id /* block */ executeBlock;

+ (id)simpleTransactionWithMilestones:(id)arg1;

- (void).cxx_destruct;
- (void)_begin;
- (id /* block */)executeBlock;
- (void)setExecuteBlock:(id /* block */)arg1;

@end
