/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSpotlightTransientOverlaySpotlightViewController : SBSpotlightMultiplexingViewController

- (bool)_canShowWhileLocked;
- (unsigned long long)level;
- (unsigned long long)remoteSearchViewPresentationSource;

@end
