/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/IMDPersistence.framework/IMDPersistence
 */

@interface IMDCoreSpotlightManager : NSObject {
    NSMutableSet * _blacklistMessageGUIDs;
}

@property (nonatomic, retain) NSMutableSet *blacklistMessageGUIDs;

+ (id)chatStyleCustomKey;
+ (id)sharedInstance;

- (unsigned long long)_batchSizeForTargetBatchSize:(unsigned long long)arg1 lastIndexedRowID:(unsigned long long)arg2 lastBatch:(bool*)arg3;
- (bool)_bypassIndexVersionCheck;
- (long long)_chatCountForChats:(id)arg1;
- (id)_chatDictionaryForChatAtIndex:(unsigned long long)arg1 withChats:(id)arg2;
- (id)_chatDictionaryForChatGUID:(id)arg1;
- (struct __CFArray { }*)_copyMessagesForIndexingWithLastRowID:(unsigned long long)arg1 batchSize:(unsigned long long)arg2;
- (unsigned long long)_currentIndexVersion;
- (unsigned long long)_expectedIndexVersion;
- (void)_geocodeItems:(id)arg1;
- (void)_indexSearchableChatItems:(id)arg1;
- (void)_indexSearchableItems:(id)arg1 lastIndexedRowID:(unsigned long long)arg2 batchSize:(unsigned long long)arg3 lastBatch:(bool)arg4 completion:(id /* block */)arg5;
- (unsigned long long)_lastIndexedRowID;
- (id)_newLegacySearchableIndexesForMessages:(struct __CFArray { }*)arg1;
- (id)_newSearchableChatItemsForChats:(struct __CFArray { }*)arg1;
- (id)_newSearchableIndexesForMessages:(struct __CFArray { }*)arg1;
- (void)_sanitizeIndexesForCurrentVersionIfNeeded:(id /* block */)arg1;
- (void)_setBypassIndexVersionCheck;
- (void)_setCurrentIndexVersion:(unsigned long long)arg1;
- (void)_setLastIndexedRowID:(unsigned long long)arg1;
- (void)_setMaxIndexRowID:(unsigned long long)arg1;
- (void)_setNeedsDeferredIndexing:(bool)arg1;
- (void)_setNeedsIndexing:(bool)arg1;
- (bool)_shouldBypassForTesting;
- (bool)_shouldIndexNextBatchForBatchSize:(unsigned long long)arg1;
- (void)_updateItem:(id)arg1 withGeoMapItem:(id)arg2;
- (id)blacklistMessageGUIDs;
- (void)clearMessageGUIDFromScrutiny:(id)arg1;
- (void)dealloc;
- (void)deleteChatSearchableItemForChatGUID:(id)arg1;
- (void)indexChats;
- (void)indexNextMessageBatchIfNeeded:(unsigned long long)arg1 completion:(id /* block */)arg2;
- (long long)maxRowID;
- (id)newChatSearchableItemForChatDictionary:(id)arg1 optionalLastMessageDate:(id)arg2;
- (id)newSearchableItemsForMessage:(struct _IMDMessageRecordStruct { struct __CFRuntimeBase { unsigned long long x_1_1_1; _Atomic unsigned long long x_1_1_2; } x1; long long x2; struct __CFArray {} *x3; struct _IMDHandleRecordStruct {} *x4; struct _IMDHandleRecordStruct {} *x5; struct __CFArray {} *x6; }*)arg1 reindexing:(bool)arg2;
- (id)newSearchableItemsForMessageGUID:(id)arg1 reindexing:(bool)arg2;
- (id)searchableIndex;
- (void)setBlacklistMessageGUIDs:(id)arg1;
- (void)setMessageGUIDUnderScrutiny:(id)arg1;
- (void)setNeedsMessageReindexingWithCompletion:(id /* block */)arg1;

@end
