/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TrialServer.framework/TrialServer
 */

@interface TRIBaseArtifact : NSObject {
    NSURL * _url;
    NSData * encodedDefinition;
}

@property (retain) NSData *encodedDefinition;
@property (readonly) NSURL *url;

+ (bool)createDirectoryForUrl:(id)arg1 isDirectory:(bool)arg2;
+ (bool)fileExists:(id)arg1;
+ (bool)saveEncodedDefinition:(id)arg1 toUrl:(id)arg2;

- (void).cxx_destruct;
- (id)artifactWithBaseUrl:(id)arg1;
- (id)copyFileFromUrl:(id)arg1 to:(id)arg2 targetIsDirectory:(bool)arg3;
- (id)encodedDefinition;
- (bool)isValid;
- (bool)loadFromUrl:(id)arg1;
- (void)loadPropertiesFromDictionary:(id)arg1;
- (bool)remove;
- (bool)removeFromUrl:(id)arg1;
- (bool)removeItemAtPath:(id)arg1;
- (id)save;
- (id)savePropertiesToDictionary;
- (id)saveToUrl:(id)arg1;
- (void)setEncodedDefinition:(id)arg1;
- (id)url;

@end
