/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TrialServer.framework/TrialServer
 */

@interface TRIClientExperimentArtifact : TRIBaseArtifact {
    NSString * _encodedExperimentDefinitionSignature;
    NSString * _experimentId;
    int  _experimentPriority;
    int  _experimentState;
    int  _experimentType;
    NSDate * _modifiedDate;
    NSArray * _namespaceCompatibilityVersions;
    NSArray * _namespaces;
    int  _projectId;
    NSData * _publicCertificate;
}

@property (nonatomic, retain) NSData *encodedExperimentDefinition;
@property (nonatomic, retain) NSString *encodedExperimentDefinitionSignature;
@property (nonatomic, readonly) TRIClientExperiment *experiment;
@property (nonatomic, retain) NSString *experimentId;
@property int experimentPriority;
@property int experimentState;
@property int experimentType;
@property (nonatomic, retain) NSDate *modifiedDate;
@property (nonatomic, retain) NSArray *namespaceCompatibilityVersions;
@property (nonatomic, retain) NSArray *namespaces;
@property int projectId;
@property (nonatomic, retain) NSData *publicCertificate;

+ (id)artifactFromCloudKitResult:(id)arg1;
+ (id)artifactWithExperimentId:(id)arg1;
+ (id)loadArtifactWithExperimentId:(id)arg1;
+ (id)urlForExperimentWithId:(id)arg1;

- (void).cxx_destruct;
- (id)encodedExperimentDefinition;
- (id)encodedExperimentDefinitionSignature;
- (id)experiment;
- (id)experimentId;
- (int)experimentPriority;
- (int)experimentState;
- (int)experimentType;
- (id)init;
- (id)initWithExperimentId:(id)arg1;
- (bool)isCompatible;
- (bool)isValid;
- (void)loadPropertiesFromDictionary:(id)arg1;
- (id)modifiedDate;
- (id)namespaceCompatibilityVersions;
- (id)namespaces;
- (int)projectId;
- (id)publicCertificate;
- (id)savePropertiesToDictionary;
- (bool)saveWithDatabase:(id)arg1;
- (void)setEncodedExperimentDefinition:(id)arg1;
- (void)setEncodedExperimentDefinitionSignature:(id)arg1;
- (void)setExperimentId:(id)arg1;
- (void)setExperimentPriority:(int)arg1;
- (void)setExperimentState:(int)arg1;
- (void)setExperimentType:(int)arg1;
- (void)setModifiedDate:(id)arg1;
- (void)setNamespaceCompatibilityVersions:(id)arg1;
- (void)setNamespaces:(id)arg1;
- (void)setProjectId:(int)arg1;
- (void)setPublicCertificate:(id)arg1;
- (id)url;

@end
