/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TrialServer.framework/TrialServer
 */

@interface TRIDServer : NSObject {
    TRIClient * _client;
    TRIControlManager * _controlManager;
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    bool  _isRunning;
    TRITaskQueue * _taskQueue;
}

@property (readonly) TRIClient *client;
@property (readonly) TRIControlManager *controlManager;
@property (readonly) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (readonly) bool isRunning;
@property (readonly) TRITaskQueue *taskQueue;

+ (id)sharedServer;

- (void).cxx_destruct;
- (void)_registerFetchExperimentsActivity;
- (void)_registerPlaceholderTaskQueueActivity;
- (void)_registerPostUpgradeActivity;
- (void)_registerXpcStreamEventHandler;
- (void)_scheduleDaemonExitWithDelaySeconds:(double)arg1;
- (void)asyncStartWithMetrics:(id)arg1;
- (id)client;
- (id)controlManager;
- (void)dispatchIfUnlocked:(id /* block */)arg1;
- (id)dispatchQueue;
- (unsigned long long)getDiskUsageInBytes;
- (id)init;
- (bool)isRunning;
- (void)logMetrics:(id)arg1 stopwatch:(id)arg2;
- (bool)makeDataVaultAtPath:(id)arg1;
- (bool)shouldContinue;
- (void)start;
- (id)taskQueue;
- (void)updateSystemInfo;

@end
