/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpeechRecognitionCommandAndControl.framework/SpeechRecognitionCommandAndControl
 */

@interface CACApplicationUtilities : NSObject

+ (id)installedApplications;
+ (void)launchApplicationWithIdentifier:(id)arg1;
+ (id)runningApplications;
+ (id)targetApplications;

@end
