/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface ENSDKResourceLoader : NSObject

+ (id)pathToResourceNamed:(id)arg1 extension:(id)arg2;

@end
