/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFEvernoteCreateAction : WFAction

- (void)runAsynchronouslyWithInput:(id)arg1;

@end
