/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFGetDistanceUnitPickerParameter : WFEnumerationParameter

- (id)defaultSerializedRepresentation;

@end
