/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFGetDictionaryValueAction : WFAction

+ (bool)outputIsExemptFromTaintTrackingInheritance;

- (void)runAsynchronouslyWithInput:(id)arg1;
- (void)setOutputWithValue:(id)arg1 preferredDictionaryType:(id)arg2 contentSource:(id)arg3;

@end
