/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFQuickLookAction : WFAction <QLPreviewControllerPrivateDelegate>

@property (nonatomic, retain) WFContentCollection *dataSource;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) QLPreviewController *previewController;
@property (readonly) Class superclass;

// Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit

- (void)initializeParameters;

// Image: /System/Library/PrivateFrameworks/ActionKitUI.framework/ActionKitUI

- (id)dataSource;
- (id)previewController;
- (bool)previewController:(id)arg1 canShareItem:(id)arg2;
- (void)previewControllerDidDismiss:(id)arg1;
- (void)runWithUIKitUserInterface:(id)arg1 input:(id)arg2;
- (void)setDataSource:(id)arg1;
- (void)setPreviewController:(id)arg1;

@end
