/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFShowWebPageAction : WFAction <SFSafariViewControllerDelegate, WFWebViewControllerDelegate>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

// Image: /System/Library/PrivateFrameworks/ActionKitUI.framework/ActionKitUI

- (void)runWithUIKitUserInterface:(id)arg1 input:(id)arg2;
- (void)safariViewControllerDidFinish:(id)arg1;
- (void)webViewControllerDidFinish:(id)arg1;

@end
