/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFSlackPostAction : WFAction

- (void)initializeParameters;
- (void)runAsynchronouslyWithInput:(id)arg1;

@end
