/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFWeatherAttributionAccessResource : WFAccessResource

- (unsigned long long)globalLevelStatus;
- (id)icon;
- (id)name;
- (unsigned long long)workflowLevelStatus;

@end
