/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MaterialKit.framework/MaterialKit
 */

@interface MTVisualStyling : NSObject {
    MTCoreMaterialVisualStyling * _coreMaterialVisualStyling;
}

@property (nonatomic, readonly) double alpha;
@property (nonatomic, readonly, copy) UIColor *color;
@property (nonatomic, readonly) CAFilter *composedFilter;
@property (getter=_coreMaterialVisualStyling, nonatomic, retain) MTCoreMaterialVisualStyling *coreMaterialVisualStyling;
@property (nonatomic, readonly, copy) NSString *visualStyleName;
@property (nonatomic, readonly, copy) NSString *visualStyleSetName;

- (void).cxx_destruct;
- (id)_coreMaterialVisualStyling;
- (id)_layerConfig;
- (double)alpha;
- (id)color;
- (id)composedFilter;
- (id)initWithCoreMaterialVisualStyling:(id)arg1;
- (void)setCoreMaterialVisualStyling:(id)arg1;
- (id)visualEffect;
- (id)visualStyleName;
- (id)visualStyleSetName;

@end
