/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SiriActivation.framework/SiriActivation
 */

@interface SASHeater : NSObject {
    NSTimer * _defrostTimer;
    <SASHeaterDelegate> * _delegate;
    bool  _predictedRecordRouteIsZLL;
    NSTimer * _preheatTimer;
    double  _preparationStartTime;
}

@property (nonatomic, retain) NSTimer *defrostTimer;
@property (nonatomic) <SASHeaterDelegate> *delegate;
@property (nonatomic) bool predictedRecordRouteIsZLL;
@property (nonatomic, retain) NSTimer *preheatTimer;
@property (getter=_preparationStartTime, setter=_setPreparationStartTime:, nonatomic) double preparationStartTime;

- (void).cxx_destruct;
- (void)_cancelPreparation;
- (double)_preparationStartTime;
- (void)_setPreparationStartTime:(double)arg1;
- (void)_suggestDefrost;
- (void)_suggestPreheat;
- (void)_updatePredictedRouteIsZLL;
- (void)cancelPreparation;
- (id)defrostTimer;
- (id)delegate;
- (bool)predictedRecordRouteIsZLL;
- (id)preheatTimer;
- (void)prepareForUseAfterTimeInterval:(double)arg1;
- (void)setDefrostTimer:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setPredictedRecordRouteIsZLL:(bool)arg1;
- (void)setPreheatTimer:(id)arg1;

@end
