/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ScreenTimeSettingsUI.framework/ScreenTimeSettingsUI
 */

@interface STWeeklyReportAppUsageTableViewCell : UITableViewCell

- (id)initWithUsageReport:(id)arg1;

@end
