/* Generated by EzioChiu
   Image: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

@interface MFListUnsubscribeMessageGenerator_iOS : EMListUnsubscribeMessageGenerator

+ (id)deliveryForCommand:(id)arg1;
+ (id)senderForCommand:(id)arg1;

@end
