/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Photos.framework/Photos
 */

@interface PHAssetCreationRequestPlaceholderSupportCrashRecovery : NSObject

+ (void)restartPendingPlaceholderDownloadsForLibrary:(id)arg1;

@end
