/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Photos.framework/Photos
 */

@interface PHMediaRequestContext : NSObject <PHAdjustmentDataRequestDelegate, PHImageRequestDelegate, PHResourceRepairRequestDelegate, PHVideoRequestDelegate, PLTrackableRequestDelegate> {
    PHAsset * _asset;
    <PHMediaRequestContextDelegate> * _delegate;
    PHImageDisplaySpec * _displaySpec;
    PHImageResourceChooser * _imageResourceChooser;
    NSMutableSet * _inflightRequestIdentifiers;
    bool  _isCancelled;
    NSMutableArray * _jobs;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
    unsigned long long  _managerID;
    _Atomic unsigned long long  _nextID;
    NSMutableDictionary * _progressByTaskIdentifier;
    _Atomic int  _repairAttemptCount;
    int  _requestID;
    NSMutableDictionary * _requestedResourcesByTaskIdentifier;
    NSMutableArray * _requests;
    id /* block */  _resultHandler;
    unsigned long long  _signpostID;
    unsigned long long  _signpostLayoutID;
    NSProgress * _totalProgress;
}

@property (nonatomic, readonly) PHAsset *asset;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <PHMediaRequestContextDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) PHImageDisplaySpec *displaySpec;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) PHImageResourceChooser *imageResourceChooser;
@property (nonatomic, readonly) unsigned long long managerID;
@property (nonatomic, readonly) int requestID;
@property (nonatomic) unsigned long long signpostID;
@property (nonatomic) unsigned long long signpostLayoutID;
@property (readonly) Class superclass;
@property (nonatomic, readonly) long long type;

+ (id)chooserQueue;
+ (id)contentEditingInputRequestContextWithRequestID:(int)arg1 managerID:(unsigned long long)arg2 asset:(id)arg3 options:(id)arg4 useRAWAsUnadjustedBase:(bool)arg5 resultHandler:(id /* block */)arg6;
+ (id)imageRequestContextWithRequestID:(int)arg1 managerID:(unsigned long long)arg2 asset:(id)arg3 imageRequestOptions:(id)arg4 displaySpec:(id)arg5 resultHandler:(id /* block */)arg6;
+ (void)initialize;
+ (id)livePhotoRequestContextWithRequestID:(int)arg1 managerID:(unsigned long long)arg2 asset:(id)arg3 livePhotoRequestOptions:(id)arg4 displaySpec:(id)arg5 resultHandler:(id /* block */)arg6;
+ (id)videoRequestContextWithRequestID:(int)arg1 managerID:(unsigned long long)arg2 asset:(id)arg3 videoRequestOptions:(id)arg4 intent:(long long)arg5 resultHandler:(id /* block */)arg6;

- (void).cxx_destruct;
- (bool)_makeAvailabilityRequest:(id)arg1 forResource:(id)arg2;
- (id)_produceChildRequestsForRequest:(id)arg1 reportingIsLocallyAvailable:(bool)arg2 isDegraded:(bool)arg3;
- (id)_produceChildRequestsForRequest:(id)arg1 withResult:(id)arg2;
- (void)_registerAndStartRequests:(id)arg1;
- (id)_requestWithIdentifier:(id)arg1;
- (void)_setupProgressIfNeeded;
- (void)adjustmentDataRequest:(id)arg1 didReportProgress:(double)arg2 completed:(bool)arg3 error:(id)arg4;
- (id)asset;
- (void)cancel;
- (id)delegate;
- (id)displaySpec;
- (void)imageRequest:(id)arg1 isQueryingCacheAndDidWait:(bool*)arg2 didFindImage:(bool*)arg3 resultHandler:(id /* block */)arg4;
- (bool)imageRequest:(id)arg1 isRequestingRepairAndRetryForDataStoreKey:(id)arg2 inStore:(id)arg3 assetObjectID:(id)arg4 forValidationErrors:(id)arg5;
- (void)imageRequest:(id)arg1 isRequestingScheduledWorkBlock:(id /* block */)arg2;
- (id)imageResourceChooser;
- (id)initWithRequestID:(int)arg1 managerID:(unsigned long long)arg2 asset:(id)arg3 displaySpec:(id)arg4 resultHandler:(id /* block */)arg5;
- (id)initialRequests;
- (bool)isCancelled;
- (bool)isNetworkAccessAllowed;
- (bool)isSynchronous;
- (unsigned long long)managerID;
- (void)mediaRequest:(id)arg1 didFindLocallyAvailableResult:(bool)arg2 isDegraded:(bool)arg3;
- (void)mediaRequest:(id)arg1 didFinishWithResult:(id)arg2;
- (bool)mediaRequest:(id)arg1 didStartLocalAvailabilityChangeRequestForResource:(id)arg2;
- (unsigned long long)nextRequestIndex;
- (void)processMediaResult:(id)arg1 forRequest:(id)arg2;
- (id)produceChildRequestsForRequest:(id)arg1 reportingIsLocallyAvailable:(bool)arg2 isDegraded:(bool)arg3 result:(id)arg4;
- (id /* block */)progressHandler;
- (id)progresses;
- (bool)representsShareableHighQualityResource;
- (int)requestID;
- (void)requestWithIdentifier:(id)arg1 didReportProgress:(double)arg2 completed:(bool)arg3 error:(id)arg4;
- (void)resourceAvailabilityChangeRequest:(id)arg1 didFinishWithSuccess:(bool)arg2 url:(id)arg3 data:(id)arg4 info:(id)arg5 error:(id)arg6;
- (void)resourceAvailabilityChangeRequest:(id)arg1 didLoadData:(id)arg2;
- (void)resourceAvailabilityChangeRequest:(id)arg1 didReportProgress:(double)arg2 completed:(bool)arg3 error:(id)arg4;
- (void)resourceRepairRequest:(id)arg1 didFinishWithSuccess:(bool)arg2;
- (void)setDelegate:(id)arg1;
- (void)setDisplaySpec:(id)arg1;
- (void)setImageResourceChooser:(id)arg1;
- (void)setProgress:(id)arg1 forRequestIdentifier:(id)arg2;
- (void)setSignpostID:(unsigned long long)arg1;
- (void)setSignpostLayoutID:(unsigned long long)arg1;
- (bool)shouldReportProgress;
- (unsigned long long)signpostID;
- (unsigned long long)signpostLayoutID;
- (void)start;
- (double)totalProgressFraction;
- (void)trackableDownloadRequest:(id)arg1 didFinishWithSuccess:(bool)arg2 url:(id)arg3 data:(id)arg4 info:(id)arg5 error:(id)arg6;
- (void)trackableRequest:(id)arg1 didReportProgress:(double)arg2 completed:(bool)arg3 error:(id)arg4;
- (void)trackableResourceRepairRequest:(id)arg1 didFinishWithSuccess:(bool)arg2;
- (void)trackableVideoChoosingAndAvailabilityRequest:(id)arg1 didFinishWithVideoURL:(id)arg2 info:(id)arg3 error:(id)arg4;
- (long long)type;
- (bool)videoRequest:(id)arg1 didStartVideoChoosingRequestForSize:(struct CGSize { double x1; double x2; })arg2;

@end
