/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Photos.framework/Photos
 */

@interface PHPhotosHighlightChangeRequest : PHChangeRequest <PGHighlightModelChangeRequest, PHInsertChangeRequest, PHUpdateChangeRequest> {
    NSDictionary * _curationHelpersByCurationType;
    PHRelationshipChangeRequestHelper * _dayGroupKeyAssetHelper;
    PHRelationshipChangeRequestHelper * _dayKeyAssetHelper;
    PHRelationshipChangeRequestHelper * _monthKeyAssetHelper;
    PHPhotosHighlight * _originalHighlight;
    PHRelationshipChangeRequestHelper * _yearKeyAssetHelper;
}

@property (nonatomic) unsigned short category;
@property (getter=isClientEntitled, nonatomic, readonly) bool clientEntitled;
@property (nonatomic, readonly) NSString *clientName;
@property (nonatomic, readonly) id /* block */ concurrentWorkBlock;
@property (nonatomic, readonly) NSDictionary *curationHelpersByCurationType;
@property (nonatomic, retain) NSString *dateDescription;
@property (nonatomic, readonly) PHRelationshipChangeRequestHelper *dayGroupKeyAssetHelper;
@property (nonatomic, readonly) PHRelationshipChangeRequestHelper *dayKeyAssetHelper;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSDate *endDate;
@property (nonatomic) long long endTimeZoneOffset;
@property (nonatomic) unsigned short enrichmentState;
@property (readonly) unsigned long long hash;
@property (readonly) bool isNewRequest;
@property (nonatomic) unsigned short kind;
@property (nonatomic, readonly) NSString *managedEntityName;
@property (nonatomic, readonly) PHRelationshipChangeRequestHelper *monthKeyAssetHelper;
@property (nonatomic) unsigned long long mood;
@property (getter=isMutated, readonly) bool mutated;
@property (nonatomic, readonly) NSManagedObjectID *objectID;
@property (nonatomic, retain) PHPhotosHighlight *originalHighlight;
@property (nonatomic, readonly) PHObjectPlaceholder *placeholderForCreatedPhotosHighlight;
@property (nonatomic) double promotionScore;
@property (nonatomic, retain) NSString *smartDescription;
@property (nonatomic, retain) NSDate *startDate;
@property (nonatomic) long long startTimeZoneOffset;
@property (readonly) Class superclass;
@property (nonatomic) unsigned short type;
@property (nonatomic, retain) NSString *verboseSmartDescription;
@property (nonatomic) unsigned short visibilityState;
@property (nonatomic, readonly) PHRelationshipChangeRequestHelper *yearKeyAssetHelper;

// Image: /System/Library/Frameworks/Photos.framework/Photos

+ (bool)canGenerateUUIDWithoutEntitlements;
+ (id)changeRequestForPhotosHighlight:(id)arg1;
+ (id)creationRequestForPhotosHighlight;
+ (void)deletePhotosHighlights:(id)arg1;

- (void).cxx_destruct;
- (id)_existentAssetObjectIDs;
- (id)_existentCuratedAssetObjectIDsForCurationType:(unsigned short)arg1;
- (unsigned short)_externalCurationTypeForInternalCurationType:(unsigned short)arg1;
- (void)_initializeCurationHelpersWithHelper:(id)arg1 xpcDict:(id)arg2;
- (unsigned short)_internalCurationTypeForExternalCurationType:(unsigned short)arg1;
- (id)_mutableAssetObjectIDsAndUUIDsForCurationType:(unsigned short)arg1;
- (id)_mutableKeyAssetObjectIDsAndUUIDs;
- (bool)applyMutationsToManagedObject:(id)arg1 photoLibrary:(id)arg2 error:(id*)arg3;
- (unsigned short)category;
- (void)clearCurationWithType:(unsigned short)arg1;
- (id)createManagedObjectForInsertIntoPhotoLibrary:(id)arg1 error:(id*)arg2;
- (id)curationHelpersByCurationType;
- (id)dateDescription;
- (id)dayGroupKeyAssetHelper;
- (id)dayKeyAssetHelper;
- (void)didEnrichHighlight;
- (void)encodeToXPCDict:(id)arg1;
- (id)endDate;
- (long long)endTimeZoneOffset;
- (unsigned short)enrichmentState;
- (short)enrichmentVersion;
- (id)initForNewObject;
- (id)initWithUUID:(id)arg1 objectID:(id)arg2;
- (id)initWithXPCDict:(id)arg1 request:(id)arg2 clientAuthorization:(id)arg3;
- (unsigned short)kind;
- (id)managedEntityName;
- (id)monthKeyAssetHelper;
- (unsigned long long)mood;
- (id)originalHighlight;
- (id)placeholderForCreatedPhotosHighlight;
- (bool)prepareForPhotoLibraryCheck:(id)arg1 error:(id*)arg2;
- (bool)prepareForServicePreflightCheck:(id*)arg1;
- (double)promotionScore;
- (void)setAssets:(id)arg1 forCurationType:(unsigned short)arg2;
- (void)setCategory:(unsigned short)arg1;
- (void)setDateDescription:(id)arg1;
- (void)setEndDate:(id)arg1;
- (void)setEndTimeZoneOffset:(long long)arg1;
- (void)setEnrichmentState:(unsigned short)arg1;
- (void)setEnrichmentVersion:(short)arg1;
- (void)setKeyAsset:(id)arg1;
- (void)setKind:(unsigned short)arg1;
- (void)setMood:(unsigned long long)arg1;
- (void)setOriginalHighlight:(id)arg1;
- (void)setPromotionScore:(double)arg1;
- (void)setSmartDescription:(id)arg1;
- (void)setStartDate:(id)arg1;
- (void)setStartTimeZoneOffset:(long long)arg1;
- (void)setType:(unsigned short)arg1;
- (void)setVerboseSmartDescription:(id)arg1;
- (void)setVisibilityState:(unsigned short)arg1;
- (id)smartDescription;
- (id)startDate;
- (long long)startTimeZoneOffset;
- (unsigned short)type;
- (id)verboseSmartDescription;
- (unsigned short)visibilityState;
- (id)yearKeyAssetHelper;

// Image: /System/Library/PrivateFrameworks/PhotosGraph.framework/PhotosGraph

- (void)clearCurations;
- (void)enumerateMomentChangeRequestsForUUIDs:(id)arg1 inPhotoLibrary:(id)arg2 usingBlock:(id /* block */)arg3;

@end
