/* Generated by EzioChiu
   Image: /System/Library/Frameworks/HomeKit.framework/HomeKit
 */

@interface HMCameraProfile : HMAccessoryProfile <HFUserNotificationServiceSettingsProviding, HMFLogging> {
    HMCameraAudioControl * _microphoneControl;
    HMCameraSettingsControl * _settingsControl;
    HMCameraSnapshotControl * _snapshotControl;
    HMCameraAudioControl * _speakerControl;
    HMCameraStreamControl * _streamControl;
    <HMCameraProfileUserSettingsDelegate> * _userSettingsDelegate;
}

@property (nonatomic, readonly) _HMCameraProfile *cameraProfile;
@property (readonly) HMCameraClipManager *clipManager;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool hf_cameraIsNotSetToRecord;
@property (nonatomic, readonly) HFCameraManager *hf_cameraManager;
@property (nonatomic, readonly) bool hf_cameraSupportsBidirectionalAudio;
@property (nonatomic, readonly) bool hf_cameraSupportsRecording;
@property (nonatomic, readonly) bool hf_shouldDisableLiveStream;
@property (nonatomic, readonly, copy) HFUserNotificationServiceSettings *hf_userNotificationSettings;
@property (nonatomic, retain) HMCameraAudioControl *microphoneControl;
@property (nonatomic, retain) HMCameraSettingsControl *settingsControl;
@property (nonatomic, retain) HMCameraSnapshotControl *snapshotControl;
@property (nonatomic, retain) HMCameraAudioControl *speakerControl;
@property (nonatomic, retain) HMCameraStreamControl *streamControl;
@property (readonly) Class superclass;
@property (nonatomic, readonly, copy) NSUUID *uniqueIdentifier;
@property (readonly) HMCameraUserSettings *userSettings;
@property <HMCameraProfileUserSettingsDelegate> *userSettingsDelegate;

// Image: /System/Library/Frameworks/HomeKit.framework/HomeKit

+ (id)logCategory;

- (void).cxx_destruct;
- (bool)_mergeWithNewObject:(id)arg1 operations:(id)arg2;
- (id)cameraProfile;
- (id)clipManager;
- (void)deleteAllClipsWithCompletionHandler:(id /* block */)arg1;
- (id)initWithCameraProfile:(id)arg1;
- (id)logIdentifier;
- (id)microphoneControl;
- (id)services;
- (void)setMicrophoneControl:(id)arg1;
- (void)setSettingsControl:(id)arg1;
- (void)setSnapshotControl:(id)arg1;
- (void)setSpeakerControl:(id)arg1;
- (void)setStreamControl:(id)arg1;
- (void)setUserSettingsDelegate:(id)arg1;
- (id)settingsControl;
- (id)snapshotControl;
- (id)speakerControl;
- (id)streamControl;
- (id)userSettings;
- (id)userSettingsDelegate;

// Image: /System/Library/PrivateFrameworks/Home.framework/Home

+ (unsigned long long)hf_cameraAccessModeSelectedOptionForCameraProfiles:(id)arg1 presenceType:(unsigned long long)arg2;
+ (unsigned long long)hf_cameraMotionDetectionSettingsForCameraProfiles:(id)arg1;
+ (unsigned long long)hf_cameraNotificationMotionDetectionSettingsForCameraProfiles:(id)arg1;
+ (unsigned long long)notificationEventTriggersForPredicate:(id)arg1;

- (id)_hf_doorbellBulletinNotification;
- (id)_hf_legacyMotionSensorBulletinNotification;
- (id)_hf_smartDetectionBulletinNotification;
- (id)hf_bulletinNotifications;
- (bool)hf_cameraIsNotSetToRecord;
- (id)hf_cameraManager;
- (bool)hf_cameraSupportsBidirectionalAudio;
- (bool)hf_cameraSupportsRecording;
- (bool)hf_shouldDisableLiveStream;
- (id)hf_updateUserNotificationSettings:(id)arg1;
- (id)hf_userNotificationSettings;

@end
