/* Generated by EzioChiu.
 */

@protocol _UISearchBarContainerSublayoutDelegate <NSObject>

@required

- (void)containerLayoutWillUpdateLayout:(_UISearchBarLayoutBase *)arg1;
- (bool)isHostingNavBarTransitionActive;
- (bool)isProspective;
- (void)setHostingNavBarTransitionActive:(bool)arg1;

@end
