/* Generated by EzioChiu.
 */

@protocol ATXLocationManagerGPS

@required

- (<ATXLocationManagerGPSDelegate> *)delegate;
- (CLLocation *)location;
- (bool)locationEnabled;
- (void)setDelegate:(id <ATXLocationManagerGPSDelegate>)arg1;
- (CLLocation *)updateLocationWithTimeout:(double)arg1;

@end
