/* Generated by EzioChiu.
 */

@protocol BCUBookCoverEffectsFilter <NSObject>

@required

- (CALayer *)coverLayerWithImage:(struct CGImage { }*)arg1 size:(struct CGSize { double x1; double x2; })arg2 contentsScale:(double)arg3;
- (NSString *)identifier;
- (<BCUOperation> *)newOperationWithImage:(void *)arg1 size:(void *)arg2 contentsScale:(void *)arg3 priority:(void *)arg4 options:(void *)arg5 completion:(void *)arg6; // needs 6 arg types, found 14: struct CGImage { }*, struct CGSize { double x1; double x2; }, double, float, NSDictionary *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, <BCUOperation> *, <BCUPurgeableImage> *, struct UIEdgeInsets { double x1; double x2; double x3; double x4; }, id, void*
- (CALayer *)shadowLayerWithImage:(struct CGImage { }*)arg1 size:(struct CGSize { double x1; double x2; })arg2 contentsScale:(double)arg3 kind:(unsigned long long)arg4;

@end
