/* Generated by EzioChiu.
 */

@protocol CALNTriggeredEventNotificationBodyDescriptionProvider <NSObject>

@required

- (NSString *)bodyForSourceClientIdentifier:(NSString *)arg1 sourceNotificationInfo:(CALNTriggeredEventNotificationSourceNotificationInfo *)arg2;

@end
