/* Generated by EzioChiu.
 */

@protocol CNSharingProfileOnboardingPhotoSelectionViewControllerDelegate <NSObject>

@required

- (void)photoSelectionViewControllerDidFinishWithResult:(CNSharingProfileOnboardingPhotoSelectionResult *)arg1;

@end
