/* Generated by EzioChiu.
 */

@protocol CNSharingProfilePhotoPickerViewControllerDelegate <NSObject>

@required

- (void)sharingPhotoPickerDidSelectAddItem:(CNSharingProfilePhotoPickerViewController *)arg1;

@end
