/* Generated by EzioChiu.
 */

@protocol CSCoverSheetViewControllerDelegate <NSObject>

@required

- (void)coverSheetViewController:(CSCoverSheetViewController *)arg1 requestsTouchIDDisabled:(bool)arg2 forReason:(NSString *)arg3;
- (void)coverSheetViewController:(void *)arg1 unlockWithRequest:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 8: CSCoverSheetViewController *, SBLockScreenUnlockRequest *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, bool, void*
- (void)coverSheetViewControllerIrisPlayingDidFinish:(CSCoverSheetViewController *)arg1;

@end
