/* Generated by EzioChiu.
 */

@protocol CSNotificationClearingTriggerDelegate <NSObject>

@required

- (void)coverSheetNotificationClearingTriggerDidFire:(CSNotificationClearingTrigger *)arg1;

@end
