/* Generated by EzioChiu.
 */

@protocol CWFXPCEventProtocol

@required

- (void)receivedAcknowledgedXPCEvent:(void *)arg1 reply:(void *)arg2; // needs 2 arg types, found 6: CWFXPCEvent *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, void*
- (void)receivedXPCEvent:(CWFXPCEvent *)arg1;

@end
