/* Generated by EzioChiu.
 */

@protocol FCAppActivityObserving <NSObject>

@optional

- (void)activityObservingApplicationDidBecomeActive;
- (void)activityObservingApplicationDidEnterBackground;
- (void)activityObservingApplicationDidFinishLaunching;
- (void)activityObservingApplicationWillEnterForeground;
- (void)activityObservingApplicationWindowDidBecomeBackground;
- (void)activityObservingApplicationWindowDidBecomeForeground;
- (void)activityObservingApplicationWindowWillBecomeForeground;

@end
