/* Generated by EzioChiu.
 */

@protocol FCForYouBridgedFeedGroupConfig <NFCopying>

@required

- (NSString *)backingTagID;
- (long long)bridgedGroupType;
- (NSString *)channelID;
- (NSString *)identifier;

@end
