/* Generated by EzioChiu.
 */

@protocol GEOLogContextDelegate <NSObject>

@optional

- (int)currentMapViewTargetForAnalytics;
- (int)currentUITargetForAnalytics;
- (int)searchFieldTypeForAnalytics;

@end
