/* Generated by EzioChiu.
 */

@protocol HKDisplayTypeContextTableViewCellDelegate <NSObject>

@required

- (void)contextCell:(HKDisplayTypeContextTableViewCell *)arg1 didSelectItemAtIndex:(long long)arg2;

@optional

- (void)contextCell:(HKDisplayTypeContextTableViewCell *)arg1 didTapOnInfoButtonForItemAtIndex:(long long)arg2;

@end
