/* Generated by EzioChiu.
 */

@protocol HKHealthRecordsStoreHealthRecordsSupportedStateChangeListener <NSObject>

@required

- (void)healthRecordsStore:(HKHealthRecordsStore *)arg1 healthRecordsSupportedDidChangeTo:(bool)arg2;
- (void)healthRecordsStore:(HKHealthRecordsStore *)arg1 healthRecordsSupportedDidChangeTo:(bool)arg2;

@end
