/* Generated by EzioChiu.
 */

@protocol HMDCameraRecordingUploaderFactory <NSObject>

@required

- (HMDCameraClipCreateOperation *)createClipOperationForLocalZone:(HMBLocalZone *)arg1 targetFragmentDuration:(double)arg2 startDate:(NSDate *)arg3 dataSource:(id <HMDCameraRecordingUploaderDataSource>)arg4;
- (HMDCameraClipFinalizeOperation *)createFinalizeOperationForModelID:(NSUUID *)arg1 localZone:(HMBLocalZone *)arg2 encryptionManager:(HMCameraClipEncryptionManager *)arg3 dataSource:(id <HMDCameraRecordingUploaderDataSource>)arg4;
- (HMDCameraClipPosterFrameUploadOperation *)createPosterFrameUploadOperationForModelID:(NSUUID *)arg1 localZone:(HMBLocalZone *)arg2 encryptionManager:(HMCameraClipEncryptionManager *)arg3 segmentData:(NSData *)arg4 segmentMetadata:(HMDCameraClipSegmentMetadata *)arg5 dataSource:(id <HMDCameraRecordingUploaderDataSource>)arg6;
- (HMDCameraSignificantEventNotificationOperation *)createSignificantEventOperationForModelID:(NSUUID *)arg1 localZone:(HMBLocalZone *)arg2 encryptionManager:(HMCameraClipEncryptionManager *)arg3 dateOfOccurrence:(NSDate *)arg4 significantEventReason:(unsigned long long)arg5 confidenceLevel:(unsigned long long)arg6 heroFrameData:(NSData *)arg7 offset:(double)arg8 homePresenceByPairingIdentity:(NSDictionary *)arg9 dataSource:(id <HMDCameraRecordingUploaderDataSource>)arg10;
- (HMDCameraClipVideoSegmentUploadOperation *)createVideoSegmentUploadOperationForModelID:(NSUUID *)arg1 localZone:(HMBLocalZone *)arg2 encryptionManager:(HMCameraClipEncryptionManager *)arg3 segmentData:(NSData *)arg4 segmentMetadata:(HMDCameraClipSegmentMetadata *)arg5 dataSource:(id <HMDCameraRecordingUploaderDataSource>)arg6;
- (<HMDCameraRecordingUploaderDataSource> *)dataSource;

@end
