/* Generated by EzioChiu.
 */

@protocol IAMApplicationContextProvider <NSObject>

@required

- (id)contextPropertyWithName:(NSString *)arg1;

@optional

- (bool)allowsModalMessageDisplay;
- (double)lastMessageDisplayTime;
- (void)messageCoordinator:(IAMMessageCoordinator *)arg1 didRequestAction:(NSDictionary *)arg2;
- (IAMPresentationPolicy *)presentationPolicyForPolicyGroup:(long long)arg1;
- (void)setLastMessageDisplayTime:(double)arg1;
- (UIViewController *)viewControllerForModalPresentation;

@end
