/* Generated by EzioChiu.
 */

@protocol MapsSuggestionsFlightRequester <MapsSuggestionsObject>

@required

- (bool)requestFlightsWithNumber:(void *)arg1 airlineCode:(void *)arg2 departureDate:(void *)arg3 handler:(void *)arg4; // needs 4 arg types, found 10: unsigned long long, NSString *, NSDate *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*

@end
