/* Generated by EzioChiu.
 */

@protocol MTIDStorage <NSObject>

@required

- (MTPromise *)deleteNamespace:(NSString *)arg1;
- (MTPromise *)optionsForNamespace:(NSString *)arg1 cachePolicy:(long long)arg2;
- (MTPromise *)updateNamespace:(NSString *)arg1 options:(NSDictionary *)arg2 resetSeed:(bool)arg3;

@end
