/* Generated by EzioChiu.
 */

@protocol NUJSRAWImagePropertiesExport <JSExport>

@required

- (NSString *)decoderVersion;
- (NUJSRAWNoiseReductionProperties *)noiseReductionProperties;
- (double)temperature;
- (double)tint;

@end
