/* Generated by EzioChiu.
 */

@protocol PHThumbnailAsset <NSCopying, NSObject>

@required

- (long long)cloudPlaceholderKind;
- (bool)complete;
- (NSManagedObjectID *)objectID;
- (PHPhotoLibrary *)photoLibrary;
- (unsigned long long)thumbnailIndex;

@end
