/* Generated by EzioChiu.
 */

@protocol PKSubcredentialPairingRemoteAlertInterface <NSObject>

@required

- (void)dismissWithCompletion:(void *)arg1; // needs 1 arg types, found 5: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, void*

@end
