/* Generated by EzioChiu.
 */

@protocol PLResource <PLResourceIdentity>

@required

- (<PLAssetID> *)assetID;
- (<PLCodecIdentity> *)codecID;
- (unsigned long long)cplType;
- (long long)dataLength;
- (<PLResourceDataStore> *)dataStore;
- (<PLResourceDataStoreKey> *)dataStoreKey;
- (long long)dataStoreSubtype;
- (long long)estimatedDataLength;
- (bool)isDefaultOrientation;
- (bool)isDerivative;
- (bool)isPlayableVideo;
- (short)localAvailability;
- (short)localAvailabilityTarget;
- (unsigned int)orientation;
- (long long)orientedHeight;
- (long long)orientedWidth;
- (int)qualitySortValue;
- (unsigned int)recipeID;
- (short)remoteAvailability;
- (short)remoteAvailabilityTarget;
- (float)scale;
- (NSDate *)trashedDate;
- (short)trashedState;
- (long long)unorientedHeight;
- (long long)unorientedWidth;

@end
