/* Generated by EzioChiu.
 */

@protocol PLTrackableRequest

@required

- (void)cancel;
- (NSXPCConnection *)clientConnection;
- (<PLTrackableRequestDelegate> *)delegate;
- (void)runDaemonSide;
- (void)setDelegate:(id <PLTrackableRequestDelegate>)arg1;
- (void)setSignpostID:(unsigned long long)arg1;
- (unsigned long long)signpostID;
- (NSString *)taskIdentifier;

@end
