/* Generated by EzioChiu.
 */

@protocol PREQuickTypeProtocol

@required

- (void)proactiveTriggersForContext:(void *)arg1 maximumTriggers:(void *)arg2 withCompletion:(void *)arg3; // needs 3 arg types, found 9: NSString *, unsigned long long, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*

@end
