/* Generated by EzioChiu.
 */

@protocol PUPhotosGridViewSupplementalToolbarDataSource <NSObject>

@required

- (bool)isAnyAssetSelected;
- (NSArray *)selectedAssets;
- (PUSessionInfo *)sessionInfo;

@optional

- (bool)isAnyAssetDownloading;

@end
