/* Generated by EzioChiu.
 */

@protocol PXMutablePhotosLibraryViewModel <NSObject>

@required

- (void)addPresenter:(id <PXCuratedLibraryViewModelPresenter>)arg1;
- (void)addView:(PXGView *)arg1;
- (bool)allPhotosAspectFit;
- (bool)allPhotosCaptionsVisible;
- (<PXFilterState> *)allPhotosFilterState;
- (bool)allPhotosLayoutIsAnimating;
- (PXCPLServiceUI *)cplServiceUI;
- (double)daysMarginScale;
- (NSSet *)draggedAssetReferences;
- (void)endAnimationToToggleChromeVisibility;
- (bool)isAppearing;
- (bool)isInteractiveZooming;
- (bool)isPinching;
- (bool)isSelecting;
- (UIBarButtonItem *)navigationDisplayModeButtonItem;
- (void)removePresenter:(id <PXCuratedLibraryViewModelPresenter>)arg1;
- (void)removeView:(PXGView *)arg1;
- (void)resetAllPhotosColumns;
- (void)setAllPhotosAspectFit:(bool)arg1;
- (void)setAllPhotosCaptionsVisible:(bool)arg1;
- (void)setAllPhotosFilterState:(id <PXFilterState>)arg1;
- (void)setAllPhotosLayoutIsAnimating:(bool)arg1;
- (void)setCplServiceUI:(PXCPLServiceUI *)arg1;
- (void)setDaysMarginScale:(double)arg1;
- (void)setDraggedAssetReferences:(NSSet *)arg1;
- (void)setInteractiveZoomColumnIndex:(double)arg1 withAnchorAssetReference:(PXAssetReference *)arg2;
- (void)setIsAppearing:(bool)arg1;
- (void)setIsInteractiveZooming:(bool)arg1;
- (void)setIsPinching:(bool)arg1;
- (void)setIsSelecting:(bool)arg1;
- (void)setNavigationDisplayModeButtonItem:(UIBarButtonItem *)arg1;
- (void)setPinchState:(struct { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; double x2; struct CGPoint { double x_3_1_1; double x_3_1_2; } x3; double x4; double x5; double x6; long long x7; double x8; })arg1 withAnchorAssetReference:(PXAssetReference *)arg2;
- (void)setSkimmingInfo:(PXCuratedLibraryAssetCollectionSkimmingInfo *)arg1;
- (void)setViewBasedDecorationsEnabled:(bool)arg1;
- (void)setWantsDarkStatusBar:(bool)arg1;
- (void)setZoomLevel:(long long)arg1;
- (void)setZoomLevelTransitionPhase:(long long)arg1;
- (PXCuratedLibraryAssetCollectionSkimmingInfo *)skimmingInfo;
- (void)startAnimationToToggleChromeVisibility;
- (void)toggleSelectionForAssetCollectionReference:(PXAssetCollectionReference *)arg1;
- (void)toggleSelectionForAssetReference:(PXAssetReference *)arg1;
- (void)toggleSelectionForIndexPath:(struct PXSimpleIndexPath { unsigned long long x1; long long x2; long long x3; long long x4; })arg1;
- (bool)viewBasedDecorationsEnabled;
- (NSMutableSet *)visibleAssetCollections;
- (bool)wantsDarkStatusBar;
- (void)zoomAllPhotosToColumnIndex:(long long)arg1 withAnchorAssetReference:(PXAssetReference *)arg2 animated:(bool)arg3;
- (void)zoomInAllPhotosToLastRememberedWithAnchorAssetReference:(PXAssetReference *)arg1 animated:(bool)arg2;
- (long long)zoomLevel;
- (long long)zoomLevelTransitionPhase;

@end
