/* Generated by EzioChiu.
 */

@protocol QLItemViewControllerPresentingDelegate

@required

- (NSString *)hostApplicationBundleIdentifier;
- (QLItemPresenterViewController *)itemPresenterViewController;
- (void)previewItemViewController:(QLItemViewController *)arg1 didFailWithError:(NSError *)arg2;

@end
