/* Generated by EzioChiu.
 */

@protocol SBDeviceApplicationSceneStatusBarBreadcrumbProviderObserver <NSObject>

@optional

- (void)statusBarBreadcrumbProviderDidUpdateDisplayProperties:(SBDeviceApplicationSceneStatusBarBreadcrumbProvider *)arg1;

@end
