/* Generated by EzioChiu.
 */

@protocol SBElasticAudioVolumeViewControllerDelegate <NSObject>

@required

- (void)elasticVolumeViewControllerNeedsDismissal:(SBElasticVolumeViewController *)arg1;

@end
