/* Generated by EzioChiu.
 */

@protocol SBFTodayOverlayControlling

@required

- (void)addTodayOverlayObserver:(id <SBFTodayOverlayObserving>)arg1;
- (double)contentWidth;
- (void)dismissAnimated:(bool)arg1;
- (double)finalPresentationProgressForPresentationProgress:(double)arg1 gestureVelocity:(double)arg2;
- (bool)isPresented;
- (void)presentAnimated:(bool)arg1;
- (double)presentationProgress;
- (void)removeTodayOverlayObserver:(id <SBFTodayOverlayObserving>)arg1;
- (void)setPresentationProgress:(double)arg1;
- (void)setPresentationProgress:(void *)arg1 interactive:(void *)arg2 animated:(void *)arg3 completionHandler:(void *)arg4; // needs 4 arg types, found 9: double, bool, bool, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, bool, void*

@end
