/* Generated by EzioChiu.
 */

@protocol SBHomeButtonSuppressAfterUnlockRecognizerDelegate <NSObject>

@required

- (void)homeButtonSuppressAfterUnlockRecognizerRequestsEndOfSuppression:(id <SBHomeButtonSuppressAfterUnlockRecognizer>)arg1;

@end
