/* Generated by EzioChiu.
 */

@protocol SearchUIFeedbackDelegateInternal <SearchUIFeedbackDelegate>

@optional

- (void)dismissIfNecessaryForIconDrag;
- (void)removeRowModel:(SearchUIRowModel *)arg1;
- (void)resignTextField;

@end
