/* Generated by EzioChiu.
 */

@protocol UIApplicationTestingDelegate <UIApplicationDelegate>

@optional

- (bool)application:(UIApplication *)arg1 runTest:(NSString *)arg2 options:(NSDictionary *)arg3;

@end
