/* Generated by EzioChiu.
 */

@protocol VKNotificationObserverDelegate <NSObject>

@optional

- (void)didReceiveFlushTileCaches;
- (void)didReceiveLocalChanged;
- (void)didReceiveMemoryWarning;

@end
