/* Generated by EzioChiu.
 */

@protocol WFForecastDataParser <NSObject>

@required

- (WFParsedForecastData *)parseForecastData:(NSData *)arg1 types:(unsigned long long)arg2 location:(WFLocation *)arg3 locale:(NSLocale *)arg4 date:(NSDateComponents *)arg5 error:(id*)arg6;
- (WFParsedForecastData *)parseForecastData:(NSData *)arg1 types:(unsigned long long)arg2 location:(WFLocation *)arg3 locale:(NSLocale *)arg4 date:(NSDateComponents *)arg5 error:(id*)arg6 rules:(WFResponseParsingRules *)arg7;

@end
