/* Generated by EzioChiu.
 */

@protocol WFModulesCollectionViewDelegate <NSObject>

@required

- (bool)collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 shouldHideItemAtIndexPath:(NSIndexPath *)arg3;
- (void)collectionView:(UICollectionView *)arg1 willDisplayCell:(UICollectionViewCell *)arg2 forItemAtIndexPath:(NSIndexPath *)arg3;

@end
