/* Generated by EzioChiu.
 */

@protocol WFWorkflowWizardNameCellDelegate <NSObject>

@required

- (void)workflowWizardNameCell:(WFWorkflowWizardNameCell *)arg1 didUpdateName:(NSString *)arg2;
- (void)workflowWizardNameCellDidSelectEditIcon:(WFWorkflowWizardNameCell *)arg1;

@optional

- (void)workflowWizardNameCellDidFinishEditing:(WFWorkflowWizardNameCell *)arg1;

@end
