/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TelephonyUtilities.framework/TelephonyUtilities
 */

@interface TUGeoLocationMetadataWorker : NSObject

+ (id)lookUpLocationsForDestinationIDs:(id)arg1;
+ (void)lookUpLocationsForDestinationIDs:(id)arg1 completion:(id /* block */)arg2;

@end
