/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AVConference.framework/AVConference
 */

@interface VCNWConnectionCongestionDetector : NSObject {
    unsigned int  _averagePacketDelayMs;
    unsigned int  _averageThroughputBps;
    bool  _didSendCongestionEvent;
    unsigned int  _lastTimestampWithPacketDrop;
    void * _logNWDump;
    unsigned int  _maxAveragePacketDelayMs;
    unsigned int  _packetDropCount;
    unsigned int  _packetDropCountPerFrame;
    struct { 
        int type; 
        double arrivalTime; 
        bool isVCRCInternal; 
        bool shouldDrainAndProcess; 
        union { 
            struct { 
                unsigned int queueDepth1; 
                unsigned int queueDepth2; 
                unsigned int txBitrate; 
                unsigned int averageBitrate; 
                unsigned int averageBitrateLong; 
                double expectedQueuingDelay; 
                double bdcd; 
                double normalizedBDCD; 
                double normalizedDelay; 
                BOOL bbString[64]; 
            } baseband; 
            struct { 
                unsigned int sendTimestamp; 
                unsigned int queuingDelay; 
                unsigned int remoteBWEstimation; 
                unsigned int maxVideoBurstyLoss; 
                unsigned int audioConsecutiveLoss; 
                unsigned int mostBurstyLoss; 
                unsigned int audioReceivedPackets; 
                unsigned int videoReceivedPackets; 
                unsigned int totalSentPackets; 
                unsigned int echoedSendTimestamp; 
                unsigned int owrd; 
                double packetLossRate; 
                unsigned int actualBitrate; 
                unsigned int instantBitrate; 
                double roundTripTime; 
                unsigned int receiveQueueTarget; 
            } feedback; 
            struct { 
                double packetLossPercentage; 
                double packetLossPercentageVideo; 
                unsigned int burstPacketLoss; 
                unsigned int roundTripTimeMilliseconds; 
                unsigned int isNetworkCongested; 
                unsigned int owrd; 
                unsigned int targetBitrate; 
                unsigned long long statisticsID; 
            } network; 
            struct { 
                unsigned int estimatorID; 
                bool deregisterEstimator; 
                bool isProbingSequence; 
                bool isEndOfProbingSequence; 
                unsigned int probingSequenceID; 
                unsigned int messageLength; 
                double arrivalTime; 
                unsigned int mediaTimestamp; 
            } probing; 
            struct { 
                unsigned char linkID; 
                unsigned int sendTimestamp; 
                unsigned int receiveTimestamp; 
                unsigned int totalPacketSent; 
                unsigned int totalPacketReceived; 
                unsigned int totalByteSent; 
                unsigned int totalByteReceived; 
                unsigned int serverStatsByteUsed; 
                unsigned int bandwidthSample; 
                unsigned int bandwidthEstimation; 
                double roundTripTime; 
                double owrd; 
                double packetLossRate; 
                unsigned int actualBitrate; 
                unsigned int serverStatsBitrate; 
                unsigned int expectedBitrate; 
            } serverStats; 
            struct { 
                unsigned int packetId; 
                unsigned int totalPacketsSent; 
                unsigned int totalBytesSent; 
                double sendTimestamp; 
                unsigned int afrcVideoBitrate; 
            } packetSent; 
            struct { 
                int packetType; 
                unsigned int packetId; 
                unsigned int sampleRate; 
                unsigned int totalPacketsReceived; 
                double receiveTimestamp; 
                double owrd; 
                double targetJitterQueueSize; 
                unsigned int bandwidthEstimation; 
                unsigned int localBurstyLoss; 
            } packetReceived; 
            struct { 
                unsigned int ssrc; 
                unsigned int packetLossPercentage; 
                unsigned int lastSequenceNumber; 
                unsigned int roundTripTimeMilliseconds; 
            } rtcpRR; 
            struct { 
                unsigned int mode; 
                unsigned int remoteRadioAccessTechnology; 
                unsigned int localRadioAccessTechnology; 
                unsigned int maxBitrate; 
                unsigned int minBitrate; 
            } config; 
            struct { 
                unsigned int mediaEventType; 
                unsigned int additionalFlushCount; 
                unsigned int transactionID; 
                unsigned int audioStallBitrate; 
                bool isKeyFrame; 
                unsigned int refreshFrameTimestamp; 
                unsigned int refreshFramePayloadType; 
                unsigned int refreshFramePacketCount; 
            } mediaEvent; 
            struct { 
                unsigned char version; 
                unsigned char direction; 
                unsigned long long timestamp; 
                unsigned long long maxThroughputBps; 
                unsigned long long totalByteCount; 
                unsigned int flushableQueueSize; 
                unsigned int nonFlushableQueueSize; 
                unsigned int averageDelayMillisecond; 
                unsigned long long averageThroughputBps; 
                int rateTrendSuggestion; 
            } nwConnection; 
        } ; 
    }  _previousStatistics;
    AVCStatisticsCollector * _statisticsCollector;
}

@property (readonly) unsigned int averagePacketDelayMs;
@property (readonly) unsigned int averageThroughputBps;
@property unsigned int maxAveragePacketDelayMs;
@property (readonly) unsigned int packetDropCount;
@property (nonatomic, retain) AVCStatisticsCollector *statisticsCollector;

- (unsigned int)averagePacketDelayMs;
- (unsigned int)averageThroughputBps;
- (void)dealloc;
- (void)enableNWLogDump:(void*)arg1;
- (unsigned int)maxAveragePacketDelayMs;
- (unsigned int)packetDropCount;
- (bool)processNWConnectionNotification:(struct ifnet_interface_advisory { unsigned char x1; unsigned char x2; unsigned short x3; int x4; unsigned long long x5; unsigned long long x6; unsigned long long x7; unsigned long long x8; unsigned int x9; unsigned int x10; unsigned int x11; }*)arg1;
- (bool)processNWConnectionPacketEvent:(struct packet_id { unsigned char x1; unsigned char x2; unsigned short x3; unsigned int x4; unsigned int x5; unsigned int x6; }*)arg1 eventType:(int)arg2;
- (void)sendCongestionEventWithTimestamp:(unsigned int)arg1;
- (void)setMaxAveragePacketDelayMs:(unsigned int)arg1;
- (void)setStatisticsCollector:(id)arg1;
- (id)statisticsCollector;

@end
