/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TrialProto.framework/TrialProto
 */

@interface TRISystemDimensions : PBCodable <NSCopying> {
    NSString * _deviceClass;
    struct { 
        unsigned int isBetaUser : 1; 
        unsigned int isInternalBuild : 1; 
    }  _has;
    bool  _isBetaUser;
    bool  _isInternalBuild;
    NSString * _versionTag;
}

@property (nonatomic, retain) NSString *deviceClass;
@property (nonatomic, readonly) bool hasDeviceClass;
@property (nonatomic) bool hasIsBetaUser;
@property (nonatomic) bool hasIsInternalBuild;
@property (nonatomic, readonly) bool hasVersionTag;
@property (nonatomic) bool isBetaUser;
@property (nonatomic) bool isInternalBuild;
@property (nonatomic, retain) NSString *versionTag;

// Image: /System/Library/PrivateFrameworks/TrialProto.framework/TrialProto

- (void).cxx_destruct;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)deviceClass;
- (id)dictionaryRepresentation;
- (bool)hasDeviceClass;
- (bool)hasIsBetaUser;
- (bool)hasIsInternalBuild;
- (bool)hasVersionTag;
- (unsigned long long)hash;
- (bool)isBetaUser;
- (bool)isEqual:(id)arg1;
- (bool)isInternalBuild;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)setDeviceClass:(id)arg1;
- (void)setHasIsBetaUser:(bool)arg1;
- (void)setHasIsInternalBuild:(bool)arg1;
- (void)setIsBetaUser:(bool)arg1;
- (void)setIsInternalBuild:(bool)arg1;
- (void)setVersionTag:(id)arg1;
- (id)versionTag;
- (void)writeTo:(id)arg1;

// Image: /System/Library/PrivateFrameworks/Trial.framework/Trial

+ (id)systemDimensions;

@end
