/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/IntentsCore.framework/IntentsCore
 */

@interface INCExecutionCounterpartMapper : NSObject {
    bool  _filled;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
    NSMutableDictionary * _mapping;
    LSApplicationWorkspace * _workspace;
}

@property (nonatomic, readonly) bool _filled;
@property (nonatomic, readonly) struct os_unfair_lock_s { unsigned int x1; } _lock;
@property (nonatomic, readonly, copy) NSMutableDictionary *_mapping;
@property (nonatomic, readonly) LSApplicationWorkspace *workspace;

- (void).cxx_destruct;
- (bool)_filled;
- (struct os_unfair_lock_s { unsigned int x1; })_lock;
- (id)_mapping;
- (id)counterpartBundleIdentifiersForBundleIdentifier:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithWorkspace:(id)arg1;
- (void)installedApplicationsDidChange:(id)arg1;
- (void)reset;
- (id)workspace;

@end
