/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/IntentsCore.framework/IntentsCore
 */

@interface INCIntentExecutionInfoResolver : INCExecutionInfoResolver

// Image: /System/Library/PrivateFrameworks/IntentsCore.framework/IntentsCore

- (id)resolveExecutionInfo:(id)arg1;

// Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit

+ (id)wf_sharedResolver;

@end
