/* Generated by EzioChiu
   Image: /System/Library/Frameworks/CoreNFC.framework/CoreNFC
 */

@interface NFCVASResponse : NSObject <NSCopying> {
    NSData * _mobileToken;
    long long  _status;
    NSData * _vasData;
}

@property (nonatomic, readonly, retain) NSData *mobileToken;
@property (nonatomic, readonly) long long status;
@property (nonatomic, readonly, retain) NSData *vasData;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithStatus:(long long)arg1 data:(id)arg2 mobileToken:(id)arg3;
- (id)mobileToken;
- (long long)status;
- (id)vasData;

@end
