/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/DeviceManagement.framework/DeviceManagement
 */

@interface DMFPolicyMonitor : NSObject {
    NSMutableDictionary * _notificationTokensByPolicyMonitorIdentifier;
    NSObject<OS_dispatch_queue> * _registrationCallbackQueue;
    NSXPCConnection * _xpcConnection;
}

@property (nonatomic, readonly) NSMutableDictionary *notificationTokensByPolicyMonitorIdentifier;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *registrationCallbackQueue;
@property (nonatomic, readonly) NSXPCConnection *xpcConnection;

+ (id)policyMonitor;
+ (id)remoteInterface;

- (void).cxx_destruct;
- (void)addRegistration:(id)arg1 forPolicyMonitorIdentifier:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)dealloc;
- (id)init;
- (id)initWithXPCConnection:(id)arg1;
- (void)invalidatePolicyMonitor:(id)arg1;
- (id)notificationTokensByPolicyMonitorIdentifier;
- (id)registrationCallbackQueue;
- (void)requestPoliciesForTypes:(id)arg1 completionHandler:(id /* block */)arg2;
- (id)requestPoliciesForTypes:(id)arg1 withError:(id*)arg2;
- (id)xpcConnection;

@end
