/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpotlightUI.framework/SpotlightUI
 */

@interface SPUISearchViewSceneSpecification : UIApplicationSceneSpecification

- (Class)clientSettingsClass;
- (Class)settingsClass;
- (Class)transitionContextClass;

@end
