/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDCameraRecordingManagerDependencyFactory : HMFObject

- (id)createBulkSendSessionInitiatorWithWorkQueue:(id)arg1 accessory:(id)arg2;
- (id)createRecordingSessionRetryContextWithWorkQueue:(id)arg1 homePresenceByPairingIdentity:(id)arg2;
- (id)createRecordingSessionWithWorkQueue:(id)arg1 camera:(id)arg2 configuredFragmentDuration:(double)arg3 timelineManager:(id)arg4;
- (id)createSessionNotificationTrigger:(id)arg1 workQueue:(id)arg2;
- (id)createSettingsControl:(id)arg1 accessory:(id)arg2 managementService:(id)arg3;
- (id)createTimerWithTimeInterval:(double)arg1;

@end
