/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDUserDataModel : HMBModel

@property (retain) NSUUID *settingsRootUUID;

+ (id)hmbProperties;

@end
