/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CameraEffectsKit.framework/CameraEffectsKit
 */

@interface JTEffectAnimationView : UIView <CAAnimationDelegate> {
    id /* block */  _animationCompletedBlock;
    bool  _animationDidBegin;
    bool  _animationDidEnd;
    JTEffectFrame * _effectFrame;
    JTEffectFrame * _fromEffectFrame;
    PCMatrix44Double * _fromTransform;
    JTEffectFrame * _toEffectFrame;
    PCMatrix44Double * _toTransform;
}

@property (nonatomic, readonly) struct CATransform3D { double x1; double x2; double x3; double x4; double x5; double x6; double x7; double x8; double x9; double x10; double x11; double x12; double x13; double x14; double x15; double x16; } animatedTransform;
@property (nonatomic, copy) id /* block */ animationCompletedBlock;
@property (nonatomic) bool animationDidBegin;
@property (nonatomic) bool animationDidEnd;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) JTEffectFrame *effectFrame;
@property (nonatomic, readonly) double fractionComplete;
@property (nonatomic, retain) JTEffectFrame *fromEffectFrame;
@property (nonatomic, retain) PCMatrix44Double *fromTransform;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, retain) JTEffectFrame *toEffectFrame;
@property (nonatomic, retain) PCMatrix44Double *toTransform;

- (void).cxx_destruct;
- (void)animateTransform:(id)arg1 completion:(id /* block */)arg2;
- (struct CATransform3D { double x1; double x2; double x3; double x4; double x5; double x6; double x7; double x8; double x9; double x10; double x11; double x12; double x13; double x14; double x15; double x16; })animatedTransform;
- (id /* block */)animationCompletedBlock;
- (bool)animationDidBegin;
- (bool)animationDidEnd;
- (void)animationDidStop:(id)arg1 finished:(bool)arg2;
- (id)effectFrame;
- (double)fractionComplete;
- (id)fromEffectFrame;
- (id)fromTransform;
- (id)initWithEffectFrame:(id)arg1 toEffectFrame:(id)arg2 fromTransform:(id)arg3 toTransform:(id)arg4;
- (void)setAnimationCompletedBlock:(id /* block */)arg1;
- (void)setAnimationDidBegin:(bool)arg1;
- (void)setAnimationDidEnd:(bool)arg1;
- (void)setFromEffectFrame:(id)arg1;
- (void)setFromTransform:(id)arg1;
- (void)setToEffectFrame:(id)arg1;
- (void)setToTransform:(id)arg1;
- (id)toEffectFrame;
- (id)toTransform;

@end
