/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TeaCharts.framework/TeaCharts
 */

@interface TeaCharts.LineImageGenerator : _TtCs12_SwiftObject {
    void pathGenerator;
}

@end
