/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TeaCharts.framework/TeaCharts
 */

@interface TeaCharts.LinePathGenerator : _TtCs12_SwiftObject {
    void coordinateProvider;
}

@end
