/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TeaCharts.framework/TeaCharts
 */

@interface TeaCharts.ChartLayoutAttributesFactory : _TtCs12_SwiftObject {
    void gridLayoutAttributesFactory;
}

@end
