/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsAnalytics.framework/NewsAnalytics
 */

@interface NewsAnalytics.FeldsparEventProcessor : _TtCs12_SwiftObject {
    void configurationManager;
    void eventStreamObserver;
    void eventTranslators;
    void jsonDecoder;
    void session;
}

@end
