/* Generated by EzioChiu
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@interface MPModelForYouRecommendationsMusicKitRequestOperation : MPStoreModelRequestOperation {
    NSDictionary * _storeBagDictionary;
}

- (void).cxx_destruct;
- (id)_produceResponseWithRecommendationsArray:(id)arg1 recentlyPlayedArray:(id)arg2 storeItemMetadataResults:(id)arg3 completion:(id /* block */)arg4;
- (id)configurationForLoadingModelDataWithStoreBagDictionary:(id)arg1 error:(id*)arg2;
- (void)produceResponseWithLoadedOutput:(id)arg1 completion:(id /* block */)arg2;
- (id)recentlyPlayedURLWithStoreBagDictionary:(id)arg1;
- (id)recommendationsURLWithStoreBagDictionary:(id)arg1;

@end
