/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PersonalizationPortrait.framework/PersonalizationPortrait
 */

@interface PPSentimentScoreEncoder : NSObject

+ (double)decodeSentimentScore:(BOOL)arg1;
+ (BOOL)encodeSentimentScore:(double)arg1;

@end
