/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKBundleComplicationDataSourceLoader : NSObject <NSCopying> {
    NSArray * _cachedDataSources;
}

+ (id)aggregateComplicationLoaderWithComplicationLoaders:(id)arg1;
+ (id)complicationDataSourceLoaderWithBlock:(id /* block */)arg1;
+ (id)complicationDataSourceLoaderWithDirectories:(id)arg1;
+ (id)complicationDataSourceLoaderWithDirectory:(id)arg1;
+ (id)defaultComplicationDataSourceLoader;
+ (id)disabledComplicationDataSourceLoader;

- (void).cxx_destruct;
- (void)_loadClassesUsingBlock:(id /* block */)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)enumerationComplicationClassesWithBlock:(id /* block */)arg1;

@end
