/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKBatteryCircularMediumComplicationView : NTKBatteryCircularSmallComplicationView

+ (bool)handlesComplicationTemplate:(id)arg1;

- (bool)usesMediumLayout;

@end
