/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKOlympusAnalogBackgroundPalette : NSObject <NTKVictoryAnalogBackgroundColorPalette> {
    NTKOlympusColorPalette * _olympusPalette;
}

@property (nonatomic, readonly) UIColor *analogDotColor;
@property (nonatomic, readonly) UIColor *backgroundColor;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) bool hasWhiteElements;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) UIColor *logoColor;
@property (nonatomic, readonly) UIColor *numbersColor;
@property (nonatomic, retain) NTKOlympusColorPalette *olympusPalette;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)analogDotColor;
- (id)backgroundColor;
- (id)colorForDotVictoryAnalogTimeElement:(unsigned long long)arg1;
- (id)colorForLogoWithStyle:(unsigned long long)arg1;
- (id)colorForNumberVictoryAnalogTimeElement:(unsigned long long)arg1;
- (bool)hasWhiteElements;
- (id)initWithOlympusPalette:(id)arg1;
- (id)initWithOlympusPalette:(id)arg1 alternatePalette:(id)arg2;
- (id)logoColor;
- (id)numbersColor;
- (id)olympusPalette;
- (void)setOlympusPalette:(id)arg1;

@end
