/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKSiderealWaypoint : NSObject {
    double  _degree;
    long long  _type;
}

@property (nonatomic) double degree;
@property (nonatomic) long long type;

+ (long long)_waypointTypeFromSolarEventType:(long long)arg1;
+ (id)waypointFromSolarEvent:(id)arg1;
+ (id)waypointWithType:(long long)arg1 degree:(double)arg2;

- (id)debugDescription;
- (double)degree;
- (id)description;
- (id)initWithType:(long long)arg1 degree:(double)arg2;
- (id)localizedName;
- (void)setDegree:(double)arg1;
- (void)setType:(long long)arg1;
- (long long)type;

@end
