/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKWorldClockRichComplicationHandsView : NTKAnalogHandsView <CLKMonochromeComplicationView> {
    <CLKMonochromeFilterProvider> * _filterProvider;
    CALayer * _pegDot;
    UIColor * _pegDotColor;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) <CLKMonochromeFilterProvider> *filterProvider;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) UIColor *pegDotColor;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (double)_timeAnimationFramesPerSecondForDevice:(id)arg1;
- (long long)displayedHour;
- (id)filterProvider;
- (id)initForDevice:(id)arg1;
- (void)layoutSubviews;
- (id)pegDotColor;
- (void)setFilterProvider:(id)arg1;
- (void)setPegDotColor:(id)arg1;
- (void)transitionToMonochromeWithFraction:(double)arg1;
- (void)updateMonochromeColor;

@end
