/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SettingsCellular.framework/SettingsCellular
 */

@interface PSAppDataUsagePolicyTernaryControlTableCell : PSReversedSubtitleDisclosureTableCell

+ (long long)cellStyle;

- (void)refreshCellContentsWithSpecifier:(id)arg1;

@end
