/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SettingsCellular.framework/SettingsCellular
 */

@interface PSFindMyDataUsagePolicyTernaryControlSpecifier : PSAppDataUsagePolicyTernaryControlSpecifier

- (void)setCellularUsagePolicy:(id)arg1;

@end
