/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MetricKitServices.framework/MetricKitServices
 */

@interface MXPowerlogService : MXService {
    NSObject<OS_os_log> * _MXPowerLogServiceLogHandle;
    NSMutableArray * _powerlogDataPaths;
    NSObject<OS_dispatch_queue> * _requestQueue;
    MXSourceXPCPayload * _unarchivedPowerlogData;
}

@property (retain) NSObject<OS_os_log> *MXPowerLogServiceLogHandle;
@property (retain) NSMutableArray *powerlogDataPaths;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *requestQueue;
@property (retain) MXSourceXPCPayload *unarchivedPowerlogData;

+ (id)sharedPowerlogService;

- (void).cxx_destruct;
- (id)MXPowerLogServiceLogHandle;
- (bool)_updateMetrics;
- (id)getMetricsForClient:(id)arg1 dateString:(id)arg2;
- (id)init;
- (bool)metricsAvailableForDate:(id)arg1;
- (id)powerlogDataPaths;
- (id)requestQueue;
- (void)setMXPowerLogServiceLogHandle:(id)arg1;
- (void)setPowerlogDataPaths:(id)arg1;
- (void)setRequestQueue:(id)arg1;
- (void)setUnarchivedPowerlogData:(id)arg1;
- (bool)startService;
- (bool)stopService;
- (id)unarchivedPowerlogData;

@end
