/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TeaSettings.framework/TeaSettings
 */

@interface TeaSettings.SettingGroup : _TtCs12_SwiftObject {
    void enabledSetting;
}

@end
