/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VoiceShortcutsUI.framework/VoiceShortcutsUI
 */

@interface VCUIActionDonationDetailsViewController : UIViewController <VCUIShortcutViewControllerDelegate> {
    <VCActionDonation> * _donation;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) <VCActionDonation> *donation;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, retain) UITextView *view;

+ (void)initialize;

- (void).cxx_destruct;
- (void)createVoiceShortcut;
- (id)donation;
- (id)initWithDonation:(id)arg1;
- (void)loadView;
- (void)shortcutViewController:(id)arg1 didCreateShortcut:(id)arg2;
- (void)shortcutViewControllerDidCancel:(id)arg1;

@end
