/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CloudKitCodeProtobuf.framework/CloudKitCodeProtobuf
 */

@interface _TtCV20CloudKitCodeProtobuf20Google_Protobuf_EnumP33_DA8D89B6A200B2A9AF93B9378395390013_StorageClass : _TtCs12_SwiftObject {
    void _enumvalue;
    void _name;
    void _options;
    void _sourceContext;
    void _syntax;
}

@end
