/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AvatarUI.framework/AvatarUI
 */

@interface AVTCoreModelPreset : NSObject {
    AVTPreset * _preset;
    NSDictionary * _tags;
}

@property (nonatomic, readonly, copy) NSString *identifier;
@property (nonatomic, readonly, copy) NSString *localizedName;
@property (nonatomic, readonly) AVTPreset *preset;
@property (nonatomic, readonly, copy) NSDictionary *tags;

+ (id)tagSetFromPreset:(id)arg1;

- (void).cxx_destruct;
- (id)copyForPairedCategory:(long long)arg1;
- (id)description;
- (unsigned long long)hash;
- (id)identifier;
- (id)initWithPreset:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)localizedName;
- (id)preset;
- (id)tags;

@end
