/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthExperience.framework/HealthExperience
 */

@interface _TtCE16HealthExperienceCSo14HKQuantityType9HeartRate : _TtCs12_SwiftObject

@end
