/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthExperience.framework/HealthExperience
 */

@interface HealthExperience.Feed : NSManagedObject

@property (nonatomic, copy) NSDate *dateUpdated;
@property (nonatomic, copy) NSString *kindRawValue;
@property (nonatomic, retain) NSOrderedSet *sections;

- (id)initWithEntity:(id)arg1 insertIntoManagedObjectContext:(id)arg2;

@end
