/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthExperience.framework/HealthExperience
 */

@interface HealthExperience.PluginBundleProviderPrecacheOperation : NSOperation {
    void pluginsToCache;
}

- (void).cxx_destruct;
- (id)init;
- (void)main;

@end
