/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthExperience.framework/HealthExperience
 */

@interface HealthExperience.Plugin : NSManagedObject

@property (nonatomic, copy) NSData *data;
@property (nonatomic, copy) NSString *package;

- (id)initWithEntity:(id)arg1 insertIntoManagedObjectContext:(id)arg2;

@end
