/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthExperience.framework/HealthExperience
 */

@interface HealthExperience.HKBloodPressureStatisticsDataSource : HealthExperience.MutableArrayDataSource {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  anchorDate;
    void diastolicQuery;
    void diastolicStatisticsCollection;
    void diastolicType;
    void healthStore;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  intervalComponents;
    void options;
    void predicate;
    void statisticsLock;
    void systolicQuery;
    void systolicStatisticsCollection;
    void systolicType;
}

@end
