/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleMediaServicesUI.framework/AppleMediaServicesUI
 */

@interface AMSUIWebOpenURLAction : NSObject <AMSUIWebActionRunnable> {
    NSURL * _URL;
    AMSUIWebClientContext * _context;
}

@property (nonatomic, retain) NSURL *URL;
@property (nonatomic, retain) AMSUIWebClientContext *context;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)URL;
- (id)context;
- (id)initWithJSObject:(id)arg1 context:(id)arg2;
- (id)runAction;
- (void)setContext:(id)arg1;
- (void)setURL:(id)arg1;

@end
