/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCSWCServiceUpdateFetchedValueDescriptor : FCFetchedValueDescriptor {
    NSURL * _mappingDirectoryFileURL;
}

@property (nonatomic, readonly, copy) NSURL *mappingDirectoryFileURL;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)fastCachedValue;
- (void)fetchValueWithCachePolicy:(unsigned long long)arg1 qualityOfService:(long long)arg2 completion:(id /* block */)arg3;
- (id)initWithMappingDirectoryFileURL:(id)arg1;
- (id)inputManagers;
- (bool)isValue:(id)arg1 equalToValue:(id)arg2;
- (id)mappingDirectoryFileURL;

@end
