/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MobileTimer.framework/MobileTimer
 */

@interface MTBedtimeDNDStateMachineOffState : MTBedtimeDNDStateMachineState

- (void)didEnterWithPreviousState:(id)arg1;

@end
