/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MobileTimer.framework/MobileTimer
 */

@interface MTSleepCoordinatorStateMachineAsleepState : MTSleepCoordinatorStateMachineState

- (void)didEnterWithPreviousState:(id)arg1;

@end
