/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/EmailDaemon.framework/EmailDaemon
 */

@interface EDMessageRepository : NSObject <EDAccountChangeHookResponder, EDThreadQueryHandlerDelegate, EFLoggable, EMMessageRepositoryInterface> {
    EDConversationPersistence * _conversationPersistence;
    EDFetchController * _fetchController;
    NSHashTable * _handlerTokens;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _handlersLock;
    EDPersistenceHookRegistry * _hookRegistry;
    EDMailboxPersistence * _mailboxPersistence;
    EDMailboxPredictionController * _mailboxPredictionController;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _mailboxPredictionControllerLock;
    EDMessageChangeManager * _messageChangeManager;
    EDMessagePersistence * _messagePersistence;
    <EDResumable> * _observerResumer;
    NSConditionLock * _performQueryOnSerializationQueue;
    NSMutableDictionary * _queryHandlers;
    <EDRemoteSearchProvider> * _remoteSearchProvider;
    NSObject<OS_dispatch_queue> * _serializationQueue;
    EDThreadPersistence * _threadPersistence;
    NSMutableDictionary * _threadQueryHandlers;
    <EMUserProfileProvider> * _userProfileProvider;
    EDVIPManager * _vipManager;
}

@property (nonatomic, readonly) EDConversationPersistence *conversationPersistence;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) EDFetchController *fetchController;
@property (nonatomic, retain) NSHashTable *handlerTokens;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) EDPersistenceHookRegistry *hookRegistry;
@property (nonatomic, readonly) EDMailboxPersistence *mailboxPersistence;
@property (nonatomic, retain) EDMessageChangeManager *messageChangeManager;
@property (nonatomic, retain) EDMessagePersistence *messagePersistence;
@property (nonatomic, readonly) <EDResumable> *observerResumer;
@property (nonatomic, readonly) NSConditionLock *performQueryOnSerializationQueue;
@property (nonatomic, retain) NSMutableDictionary *queryHandlers;
@property (nonatomic, readonly) <EDRemoteSearchProvider> *remoteSearchProvider;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *serializationQueue;
@property (readonly) Class superclass;
@property (nonatomic, retain) EDThreadPersistence *threadPersistence;
@property (nonatomic, retain) NSMutableDictionary *threadQueryHandlers;
@property (nonatomic, readonly) <EMUserProfileProvider> *userProfileProvider;
@property (nonatomic, readonly) EDVIPManager *vipManager;

+ (id)log;
+ (id)signpostLog;

- (void).cxx_destruct;
- (id)_changeFlagsForPersistedMessages:(id)arg1 flagChange:(id)arg2 returnUndoAction:(bool)arg3;
- (void)_enumerateThreadsByThreadObjectIDsByScope:(id)arg1 usingBlock:(id /* block */)arg2;
- (id)_partitionObjectIDs:(id)arg1;
- (void)_performMessageConversationFlagChangeAction:(id)arg1;
- (void)_performMessageDeleteAction:(id)arg1;
- (void)_performMessageDeleteAllAction:(id)arg1;
- (id)_performMessageFlagChangeAction:(id)arg1 returnUndoAction:(bool)arg2;
- (void)_performMessageFlagChangeAllAction:(id)arg1;
- (id)_performMessageTransferAction:(id)arg1 returnUndoAction:(bool)arg2;
- (id)_performMessageTransferActionToSpecialMailbox:(id)arg1 returnUndoAction:(bool)arg2;
- (void)_performMessageTransferAllAction:(id)arg1;
- (void)_performMessageTransferAllActionToSpecialMailbox:(id)arg1;
- (void)_performQuery:(id)arg1 withObserver:(id)arg2 observationIdentifier:(id)arg3 completionHandler:(id /* block */)arg4;
- (id)_performUndoAction:(id)arg1;
- (id)_persistedMessagesForMessageChangeAction:(id)arg1;
- (id)_persistedMessagesForObjectIDs:(id)arg1;
- (void)_resetUpdateThrottlersWithLogMessage:(id)arg1;
- (void)_triggerMigrationForThreadScopes:(id)arg1;
- (void)_triggerMigrationWithThreadScopesMatcher:(id /* block */)arg1;
- (id)_undoActionsForMovedMessages:(id)arg1;
- (void)accountBecameActive:(id)arg1;
- (void)accountBecameInactive:(id)arg1;
- (void)cancelAllHandlers;
- (id)conversationPersistence;
- (void)dealloc;
- (id)fetchController;
- (void)getCachedMetadataJSONForKey:(id)arg1 messageID:(id)arg2 completionHandler:(id /* block */)arg3;
- (id)handlerTokens;
- (id)hookRegistry;
- (id)initWithMessagePersistence:(id)arg1 conversationPersistence:(id)arg2 threadPersistence:(id)arg3 messageChangeManager:(id)arg4 hookRegistry:(id)arg5 mailboxPersistence:(id)arg6 remoteSearchProvider:(id)arg7 userProfileProvider:(id)arg8 vipManager:(id)arg9 fetchController:(id)arg10 observerResumer:(id)arg11;
- (void)loadOlderMessagesForMailboxes:(id)arg1;
- (id)mailboxPersistence;
- (id)mailboxPredictionController;
- (id)messageChangeManager;
- (void)messageListItemsForObjectIDs:(id)arg1 requestID:(unsigned long long)arg2 observationIdentifier:(id)arg3 loadSummaryForAdditionalObjectIDs:(id)arg4 completionHandler:(id /* block */)arg5;
- (id)messagePersistence;
- (id)observerResumer;
- (void)performCountQuery:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)performMessageChangeAction:(id)arg1 requestID:(unsigned long long)arg2 returnUndoAction:(bool)arg3 completionHandler:(id /* block */)arg4;
- (void)performQuery:(id)arg1 limit:(long long)arg2 completionHandler:(id /* block */)arg3;
- (void)performQuery:(id)arg1 withObserver:(id)arg2 observationIdentifier:(id)arg3 completionHandler:(id /* block */)arg4;
- (id)performQueryOnSerializationQueue;
- (void)predictMailboxForMovingMessages:(id)arg1 withObserver:(id)arg2 completionHandler:(id /* block */)arg3;
- (id)queryHandlers;
- (id)remoteSearchProvider;
- (id)requestRepresentationForMessageWithID:(id)arg1 requestID:(unsigned long long)arg2 options:(id)arg3 delegate:(id)arg4 completionHandler:(id /* block */)arg5;
- (void)resetPrecomputedThreadScopesForMailboxScope:(id)arg1;
- (id)serializationQueue;
- (void)setCachedMetadataJSON:(id)arg1 forKey:(id)arg2 messageID:(id)arg3;
- (void)setHandlerTokens:(id)arg1;
- (void)setHookRegistry:(id)arg1;
- (void)setMessageChangeManager:(id)arg1;
- (void)setMessagePersistence:(id)arg1;
- (void)setQueryHandlers:(id)arg1;
- (void)setThreadPersistence:(id)arg1;
- (void)setThreadQueryHandlers:(id)arg1;
- (unsigned long long)signpostID;
- (void)startCountingQuery:(id)arg1 includingServerCountsForMailboxScope:(id)arg2 withObserver:(id)arg3 completionHandler:(id /* block */)arg4;
- (void)test_tearDown;
- (id)threadPersistence;
- (void)threadQueryHandlerStateDidChange:(id)arg1;
- (id)threadQueryHandlers;
- (id)userProfileProvider;
- (id)vipManager;

@end
