/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/EmailDaemon.framework/EmailDaemon
 */

@interface EDMigrateBlockedSenderEnabledToBlockedSenderActionEnumUpgradeStep : NSObject

+ (bool)run;

@end
