/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SensorKit.framework/SensorKit
 */

@interface SRFrameStore : NSObject <NSFastEnumeration> {
    NSFileHandle * _backingFile;
    unsigned int  _datastoreVersion;
    SRMemoryMapping * _frames;
    SRMemoryMapping * _header;
    double  _lastAbsoluteTimestamp;
    unsigned long long  _permission;
    NSString * _segmentName;
}

@property (retain) NSFileHandle *backingFile;
@property (nonatomic, readonly) unsigned long long freeSpace;
@property (nonatomic, copy) NSString *segmentName;
@property (nonatomic, readonly) unsigned long long used;

+ (void)initialize;
+ (struct { BOOL x1[4]; unsigned long long x2; double x3; unsigned int x4; BOOL x5[32]; })segmentHeaderFromFile:(id)arg1 withVersion:(unsigned int)arg2;

- (id)backingFile;
- (unsigned long long)countByEnumeratingWithState:(struct { unsigned long long x1; id *x2; unsigned long long *x3; unsigned long long x4[5]; }*)arg1 objects:(id*)arg2 count:(unsigned long long)arg3;
- (void)dealloc;
- (id)enumerateFromOffset:(unsigned long long)arg1;
- (void*)frameAtOffset:(unsigned long long)arg1;
- (unsigned long long)freeSpace;
- (id)initWithFileHandle:(id)arg1 maxSize:(unsigned long long)arg2 permission:(unsigned long long)arg3 defaults:(id)arg4;
- (bool)isValidFrame:(void*)arg1;
- (void)markFrameAsRemoved:(void*)arg1;
- (void*)nextFrame:(void*)arg1;
- (bool)resizeBackingFileTo:(unsigned long long)arg1;
- (bool)resizeMappedRegionTo:(unsigned long long)arg1;
- (id)segmentName;
- (void)setBackingFile:(id)arg1;
- (void)setSegmentName:(id)arg1;
- (void)sync;
- (void)updateHeader;
- (unsigned long long)used;
- (void)writeFrameForBytes:(const void*)arg1 length:(unsigned long long)arg2 timestamp:(double)arg3;

@end
