/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard
 */

@interface BSMachPortTransferableSendRight : BSMachPortSendRight

+ (id)_rightDescription;

- (id)_lock_encodePort:(unsigned int)arg1;

@end
