/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface _TtCC8NewsFeed11PlayerLayerP33_E281AE8D3CE2A6E682C97B2411BE03D920NonAnimatingDelegate : NSObject <CALayerDelegate>

- (id)actionForLayer:(id)arg1 forKey:(id)arg2;
- (id)init;

@end
