/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.StubThumbnailProcessor : NSObject <TSImageProcessorType>

- (id)init;
- (id)process:(id)arg1;

@end
