/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.AssetHandleFactory : _TtCs12_SwiftObject {
    void assetManager;
    void contentContext;
}

@end
