/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.HeadlineViewRenderer : _TtCs12_SwiftObject {
    void publisherLogoImageCache;
    void rendererTool;
    void thumbnailImageCache;
    void traitCollection;
}

@end
