/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.FormatImageProcessorRequest : NSObject <TSProcessedImageRequestType> {
    void assetHandle;
    void assetHandles;
    void focalFrame;
    void inventory;
    void renderingMode;
    void scale;
    void size;
    void style;
}

@property (nonatomic, readonly) NSDictionary *assetHandles;
@property (nonatomic, readonly) NSString *cacheIdentifier;

- (void).cxx_destruct;
- (id)assetHandles;
- (id)cacheIdentifier;
- (id)init;

@end
