/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.FeedLayoutContextFactory : _TtCs12_SwiftObject {
    void colorPaletteProvider;
    void fontBookFactory;
    void layoutAttributesFactoryProvider;
}

@end
