/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.LayeredMediaImageVariantSelector : _TtCs12_SwiftObject {
    void layeredMediaSelector;
}

@end
