/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.PaidBundleConfigManager : _TtCs12_SwiftObject {
    void configurationManager;
}

@end
