/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKAppletSubcredentialSharingExplanationViewController : PKExplanationViewController <PKExplanationViewDelegate, PKViewControllerPreflightable> {
    PKHeroCardExplainationHeaderView * _heroCardView;
    PKAppletSubcredentialSharingRequest * _sharingRequest;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_openMessagesToPresentAction;
- (void)explanationViewDidSelectContinue:(id)arg1;
- (void)explanationViewDidSelectSetupLater:(id)arg1;
- (id)initWithSharingRequest:(id)arg1;
- (void)preflightWithCompletion:(id /* block */)arg1;
- (void)viewDidLoad;

@end
