/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKCompactNavigationContainerControllerPresentationController : UIPresentationController

- (void)containerViewWillLayoutSubviews;

@end
