/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKSubcredentialInvitationMessage : NSObject {
    PKProtobufSubcredentialInvitationMessage * _protoMessage;
    MSMessage * _underlyingMessage;
}

@property (nonatomic, copy) NSString *dataString;
@property (nonatomic, copy) PKAppletSubcredentialSharingInvitation *invitation;
@property (nonatomic) unsigned long long status;
@property (nonatomic, readonly) MSMessage *underlyingMessage;

- (void).cxx_destruct;
- (id)_subcredentialInvitationMessageDataURLWithData:(id)arg1;
- (id)_subcredentialInvitationMessageDataWithDataURL:(id)arg1;
- (void)_updateDataURL;
- (void)_updateLayoutContents;
- (id)dataString;
- (id)description;
- (id)init;
- (id)initWithUnderlyingMessage:(id)arg1;
- (id)invitation;
- (void)setDataString:(id)arg1;
- (void)setInvitation:(id)arg1;
- (void)setStatus:(unsigned long long)arg1;
- (unsigned long long)status;
- (id)underlyingMessage;

@end
