/* Generated by EzioChiu
   Image: /System/Library/Frameworks/Intents.framework/Intents
 */

@interface INCodableMeasurementAttributeMetadata : INCodableAttributeMetadata {
    NSOrderedSet * _defaultUnits;
    double  _defaultValue;
    bool  _supportsNegativeNumbers;
    NSUnit * _unit;
}

@property (nonatomic, retain) NSOrderedSet *defaultUnits;
@property (nonatomic) double defaultValue;
@property (nonatomic) bool supportsNegativeNumbers;
@property (nonatomic, retain) NSUnit *unit;
@property (nonatomic, readonly) NSString *wf_measurementType;

// Image: /System/Library/Frameworks/Intents.framework/Intents

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_defaultUnitWithNames:(id)arg1;
- (Class)_unitClass;
- (id)_unitWithUnitName:(id)arg1;
- (id)defaultUnits;
- (double)defaultValue;
- (id)dictionaryRepresentationWithLocalizer:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)setDefaultUnits:(id)arg1;
- (void)setDefaultValue:(double)arg1;
- (void)setSupportsNegativeNumbers:(bool)arg1;
- (void)setUnit:(id)arg1;
- (bool)supportsNegativeNumbers;
- (id)unit;
- (void)updateWithDictionary:(id)arg1;

// Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit

- (id)wf_measurementType;
- (Class)wf_objectClass;
- (Class)wf_parameterClass;
- (id)wf_parameterStateForIntentValue:(id)arg1 parameterDefinition:(id)arg2;
- (bool)wf_processParameterValue:(id)arg1 forParameter:(id)arg2 codableAttribute:(id)arg3 completionHandler:(id /* block */)arg4;
- (void)wf_updateParameterDictionary:(id)arg1 forCodableAttribute:(id)arg2;
- (void)wf_updateWithParameterState:(id)arg1;
- (void)wf_updateWithParameterValue:(id)arg1;

@end
