/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/RemoteUI.framework/RemoteUI
 */

@interface RUIMultiChoiceElement : RUIElement <RUIMultiChoiceActionHandler> {
    RUIObjectModel * _objectModel;
    RUIMultiChoiceView * _view;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) RUIObjectModel *objectModel;
@property (readonly) Class superclass;
@property (nonatomic, retain) RUIMultiChoiceView *view;

- (void).cxx_destruct;
- (void)addChoice:(id)arg1;
- (void)didTapChoice:(id)arg1;
- (double)estimatedViewHeight;
- (id)initWithAttributes:(id)arg1 parent:(id)arg2;
- (id)objectModel;
- (void)setObjectModel:(id)arg1;
- (void)setView:(id)arg1;
- (id)view;

@end
