/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIFallbackPeekViewController : UIViewController

- (id)initWithDetailedRowModel:(id)arg1;

@end
