/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosGraph.framework/PhotosGraph
 */

@interface PGGraphHolidayNode : PGGraphNode <PGGraphLocalizable>

@property (nonatomic, readonly) unsigned long long category;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSString *localizedName;
@property (readonly) Class superclass;

- (unsigned long long)category;
- (void)enumerateCelebratingHighlightNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateCelebratingMomentNodesUsingBlock:(id /* block */)arg1;
- (id)localizedName;

@end
