/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosGraph.framework/PhotosGraph
 */

@interface PGGraphBusinessEdge : PGGraphEdge

@property (nonatomic, readonly) bool hasRoutineInfo;
@property (nonatomic, readonly) NSDate *universalEndDate;
@property (nonatomic, readonly) NSDate *universalStartDate;

- (bool)hasRoutineInfo;
- (id)universalEndDate;
- (id)universalStartDate;

@end
