/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosGraph.framework/PhotosGraph
 */

@interface PGGraphBabyNode : PGGraphNode

@property (nonatomic, readonly) NSSet *caretakerNodes;
@property (nonatomic, readonly) NSSet *momentNodes;

- (id)caretakerNodes;
- (void)enumerateCaretakerNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateMomentNodesUsingBlock:(id /* block */)arg1;
- (id)momentNodes;

@end
