/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosGraph.framework/PhotosGraph
 */

@interface PGMoodSourceGraphContext : PGMoodSource

+ (id)_plistName;

- (id)_plistMoodIdentifiers;
- (double)weight;

@end
