/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosGraph.framework/PhotosGraph
 */

@interface PGPeopleVisitingMemoryGenerator : PGFeaturedMemoryGenerator

- (void)_enumeratePotentialMemoriesUsingBlock:(id /* block */)arg1;
- (void)_postProcessMemory:(id)arg1 withPotentialMemory:(id)arg2;
- (id)_potentialMemoriesForDryTesting;
- (id)consolidatedDateIntervalsFromDateIntervals:(id)arg1;
- (void)enumeratePeopleAndVisitsUsingBlock:(id /* block */)arg1;
- (void)enumerateVerifiedPeopleNodesUsingBlock:(id /* block */)arg1;

@end
