/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosGraph.framework/PhotosGraph
 */

@interface PGPotentialRegionMemory : PGPotentialMemory {
    NSDate * _endDate;
    NSMutableSet * _mutableMomentNodes;
    PGGraphNode * _regionNode;
    NSArray * _scenedAssets;
    NSDate * _startDate;
    long long  _year;
}

@property (retain) NSDate *endDate;
@property (readonly) NSString *region;
@property (readonly) PGGraphNode *regionNode;
@property (retain) NSArray *scenedAssets;
@property (retain) NSDate *startDate;
@property (readonly) long long year;

- (void).cxx_destruct;
- (void)addMomentNode:(id)arg1;
- (id)endDate;
- (id)initWithRegionNode:(id)arg1 year:(long long)arg2;
- (id)region;
- (id)regionNode;
- (id)scenedAssets;
- (void)setEndDate:(id)arg1;
- (void)setScenedAssets:(id)arg1;
- (void)setStartDate:(id)arg1;
- (id)startDate;
- (long long)year;

@end
