/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosGraph.framework/PhotosGraph
 */

@interface PGSurveyQuestionFactory : NSObject <PGQuestionFactory> {
    NSDictionary * _existingQuestionsByEntityIdentifier;
    PGManager * _manager;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSDictionary *existingQuestionsByEntityIdentifier;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) PGManager *manager;
@property (nonatomic, readonly) long long questionOptions;
@property (nonatomic, readonly) unsigned short questionType;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_questionsByEntityIdentifierFromQuestions:(id)arg1;
- (id)curatedAssetsFromMomentNode:(id)arg1;
- (id)existingQuestionsByEntityIdentifier;
- (id)fetchExistingQuestions;
- (id)generateQuestionsWithLimit:(unsigned long long)arg1 progressBlock:(id /* block */)arg2;
- (id)initWithManager:(id)arg1;
- (id)keyAssetFromMomentNode:(id)arg1;
- (id)manager;
- (bool)questionAlreadyExists:(id)arg1;
- (long long)questionOptions;
- (unsigned short)questionType;
- (id)representativeCuratedAssetsFromMomentNode:(id)arg1;
- (void)setExistingQuestionsByEntityIdentifier:(id)arg1;
- (void)setManager:(id)arg1;
- (bool)shouldAddQuestion:(id)arg1 toAlreadyGeneratedQuestions:(id)arg2;

@end
