/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/GameCenterUI.framework/GameCenterUI
 */

@interface GKMultiplayerFooterView : UICollectionReusableView {
    GKMultiplayerActivityView * _activityView;
    GKMultiplayerBubbleView * _bubbleView;
}

@property (nonatomic, retain) GKMultiplayerActivityView *activityView;
@property (nonatomic, retain) GKMultiplayerBubbleView *bubbleView;

+ (id)footerView;

- (id)activityView;
- (id)bubbleView;
- (void)configureForMatchRequest:(id)arg1;
- (void)dealloc;
- (void)floatInBubbles;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)removeAllAnimationsFromBubbles;
- (void)scatterOutBubblesWithCompletion:(id /* block */)arg1;
- (void)setActivityView:(id)arg1;
- (void)setBubbleFooterHidden:(bool)arg1 animated:(bool)arg2;
- (void)setBubbleView:(id)arg1;
- (void)setBubblesHidden:(bool)arg1;
- (void)setStatusFooterHidden:(bool)arg1 animated:(bool)arg2;
- (void)showFooterStatus:(id)arg1;

@end
