/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MediaConversionService.framework/MediaConversionService
 */

@interface PAMediaConversionServiceiCloudPhotoLibraryImageMetadataPolicy : PAMediaConversionServiceDefaultImageMetadataPolicy

+ (id)standardPolicy;

- (id)processMetadata:(id)arg1;

@end
