/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PowerUI.framework/PowerUI
 */

@interface PowerUIMLRegressorModelPredictor : NSObject <PowerUIPredictor> {
    double  _adjustedDuration;
    <_CDUserContext> * _context;
    NSObject<OS_os_log> * _log;
    MLModel * _model;
    long long  _pluginBatteryLevel;
    NSDate * _pluginDate;
    <_DKKnowledgeQuerying> * _store;
}

@property (nonatomic) double adjustedDuration;
@property (nonatomic, retain) <_CDUserContext> *context;
@property (nonatomic, retain) NSObject<OS_os_log> *log;
@property (nonatomic, readonly) MLModel *model;
@property (nonatomic) long long pluginBatteryLevel;
@property (nonatomic, retain) NSDate *pluginDate;
@property (nonatomic, retain) <_DKKnowledgeQuerying> *store;

- (void).cxx_destruct;
- (double)adjustedChargingDecision:(unsigned long long)arg1 withPluginDate:(id)arg2 withPluginBatteryLevel:(unsigned long long)arg3 forDate:(id)arg4;
- (double)adjustedDuration;
- (id)averageDurationAndCountWithPluginDate:(id)arg1;
- (unsigned long long)batteryLevelAtDate:(id)arg1;
- (double)chargingDecision:(unsigned long long)arg1 withPluginDate:(id)arg2 withPluginBatteryLevel:(unsigned long long)arg3 forDate:(id)arg4;
- (id)context;
- (unsigned long long)currentBatteryLevel;
- (double)getHourBinID:(id)arg1;
- (id)getPluginEventsBefore:(id)arg1 withMinimumDuration:(double)arg2;
- (id)init;
- (id)log;
- (id)model;
- (long long)pluginBatteryLevel;
- (id)pluginDate;
- (id)predictFullChargeDateWithBatteryLevel:(unsigned long long)arg1;
- (void)setAdjustedDuration:(double)arg1;
- (void)setContext:(id)arg1;
- (void)setLog:(id)arg1;
- (void)setPluginBatteryLevel:(long long)arg1;
- (void)setPluginDate:(id)arg1;
- (void)setStore:(id)arg1;
- (id)store;
- (id)timeStringFromDate:(id)arg1;

@end
