/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PowerUI.framework/PowerUI
 */

@interface PowerUIHistogramPredictor : NSObject <PowerUIPredictor> {
    _DKPredictionTimeline * _deviceActivityTimeline;
    _DKPredictionTimeline * _devicePluginTimeline;
    NSObject<OS_os_log> * _log;
    int  _pluginToken;
    NSDateInterval * _predictedInactivity;
    NSDateInterval * _predictedLengthyPlugin;
    NSObject<OS_dispatch_queue> * _queue;
}

@property (nonatomic, retain) _DKPredictionTimeline *deviceActivityTimeline;
@property (nonatomic, retain) _DKPredictionTimeline *devicePluginTimeline;
@property (nonatomic, retain) NSObject<OS_os_log> *log;
@property (nonatomic) int pluginToken;
@property (nonatomic, retain) NSDateInterval *predictedInactivity;
@property (nonatomic, retain) NSDateInterval *predictedLengthyPlugin;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *queue;

+ (id)deviceActivityLikelihoodQueryPredicate;
+ (id)monitor;

- (void).cxx_destruct;
- (id)adjustedPeriodFromInterval:(id)arg1 atDate:(id)arg2;
- (id)chargeLikelihoodTimeline;
- (id)currentInactivityPrediction;
- (id)currentPluginPrediction;
- (void)dealloc;
- (id)deviceActivityLikelihoodTimeline;
- (id)deviceActivityTimeline;
- (id)devicePluginTimeline;
- (id)init;
- (void)loadChargePrediction;
- (void)loadDeviceActivityPrediction;
- (id)log;
- (unsigned long long)modelVersion;
- (int)pluginToken;
- (id)predictFullChargeDateWithBatteryLevel:(unsigned long long)arg1;
- (id)predictedInactivity;
- (id)predictedLengthyPlugin;
- (id)queue;
- (id)readNumberForPreferenceKey:(id)arg1;
- (void)setDeviceActivityTimeline:(id)arg1;
- (void)setDevicePluginTimeline:(id)arg1;
- (void)setLog:(id)arg1;
- (void)setPluginToken:(int)arg1;
- (void)setPredictedInactivity:(id)arg1;
- (void)setPredictedLengthyPlugin:(id)arg1;
- (void)setQueue:(id)arg1;
- (id)shortenIntervalWithInterval:(id)arg1;
- (id)stringFromInterval:(id)arg1;

@end
