/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/WallpaperKit.framework/WallpaperKit
 */

@interface WKDefaultWallpaperManager : NSObject {
    WKWallpaperBundleImporter * __defaultWallpaperBundleImporter;
    NSDictionary * __defaultWallpaperLookup;
}

@property (nonatomic, retain) WKWallpaperBundleImporter *_defaultWallpaperBundleImporter;
@property (nonatomic, retain) NSDictionary *_defaultWallpaperLookup;

+ (id)_pathForStillWallpapers;
+ (id)defaultWallpaperLookupURL;
+ (id)defaultWallpaperManager;
+ (id)deviceColor;
+ (id)deviceEnclosureColor;
+ (id)deviceLogicalScreenClass;
+ (id)deviceProductType;

- (void).cxx_destruct;
- (id)_defaultWallpaperBundleImporter;
- (id)_defaultWallpaperLookup;
- (void)_loadDefaultWallpaperFile;
- (id)defaultWallpaperBundle;
- (id)init;
- (void)set_defaultWallpaperBundleImporter:(id)arg1;
- (void)set_defaultWallpaperLookup:(id)arg1;

@end
