/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices
 */

@interface SBSApplicationUserQuitMonitorSessionSpecification : NSObject

+ (id)identifier;
+ (id)interface;
+ (id)serviceQuality;

@end
