/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SensorKit.framework/SensorKit
 */

@interface SRError : NSObject

+ (id)authorizationError;
+ (id)authorizationErrorWithStatus:(long long)arg1;
+ (id)connectionNotFoundError;
+ (id)errorWithCode:(long long)arg1;
+ (id)errorWithCode:(long long)arg1 description:(id)arg2 recoverySuggestion:(id)arg3;
+ (id)errorWithCode:(long long)arg1 description:(id)arg2 recoverySuggestion:(id)arg3 underlyingError:(id)arg4;
+ (id)invalidEntitlementError;

@end
