/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SensorKitUI.framework/SensorKitUI
 */

@interface SRSampleViewController : UITableViewController {
    NSArray * _items;
    NSString * _note;
}

@property (nonatomic, retain) NSArray *items;
@property (nonatomic, retain) NSString *note;

- (void)dealloc;
- (id)init;
- (id)items;
- (id)note;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)prepareEndRowWithText:(id)arg1 detailText:(id)arg2;
- (id)prepareExtendedRowWithText:(id)arg1;
- (void)setItems:(id)arg1;
- (void)setNote:(id)arg1;
- (id)sortedKeysForDictionary:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;

@end
