/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/IconServices.framework/IconServices
 */

@interface ISTrailingStatusBadgeRecipe : NSObject <ISCompositorRecipe>

- (id)layerTreeForSize:(struct CGSize { double x1; double x2; })arg1 scale:(double)arg2;
- (id)trailingBottomBadgeRect;

@end
