/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MessageProtection.framework/MessageProtection
 */

@interface RegisteredPreKey : NSManagedObject

@property (nonatomic, retain) NSSet *senders;
@property (nonatomic, copy) NSString *tag;

+ (id)fetchRequest;

@end
