/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewDeviceOutreachUI.framework/NewDeviceOutreachUI
 */

@interface NDOACController : NSObject {
    NDOSpecifierDataSource * _ndoSpecifierDataSource;
    PSListController * _parentViewController;
}

@property (nonatomic, retain) NDOSpecifierDataSource *ndoSpecifierDataSource;
@property (retain) PSListController *parentViewController;
@property (readonly) NSArray *specifiers;

+ (id)sharedController;

- (void).cxx_destruct;
- (id)init;
- (id)ndoSpecifierDataSource;
- (id)parentViewController;
- (void)setNdoSpecifierDataSource:(id)arg1;
- (void)setParentViewController:(id)arg1;
- (id)specifiers;
- (void)updateSpecifiersWithCompletionHandler:(id /* block */)arg1;

@end
