/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CalendarUIKit.framework/CalendarUIKit
 */

@interface CUIKEditingManager : NSObject {
    NSMutableDictionary * _changeHistory;
    NSMutableDictionary * _changedObjectMap;
    NSMutableSet * _editingContextGroups;
    EKEventStore * _eventStore;
}

@property (retain) NSMutableDictionary *changeHistory;
@property (retain) NSMutableDictionary *changedObjectMap;
@property (retain) NSMutableSet *editingContextGroups;
@property EKEventStore *eventStore;

- (void).cxx_destruct;
- (id)changeHistory;
- (id)changedObjectMap;
- (id)editingContextGroups;
- (id)eventStore;
- (void)setChangeHistory:(id)arg1;
- (void)setChangedObjectMap:(id)arg1;
- (void)setEditingContextGroups:(id)arg1;
- (void)setEventStore:(id)arg1;

@end
