/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CalendarUIKit.framework/CalendarUIKit
 */

@interface CUIKIconSizeMetrics : NSObject {
    double  _bestRepresentedSideLength;
    double  _dateNameBaselineVerticalInset;
    double  _dateNameDefaultFontSize;
    double  _dateNameFontWeight;
    double  _dateNameHorizontalInset;
    double  _dateNameLetterSpacing;
    double  _dateNameLongStringFontSize;
    double  _dayNumberBaselineVerticalInset;
    double  _dayNumberFontSize;
    double  _dayNumberTrackingValue;
    double  _minDateNameFontScale;
    double  _minDateNameLetterSpacing;
    double  _minFullDateNameFontScale;
    unsigned long long  _type;
}

@property (nonatomic, readonly) double bestRepresentedSideLength;
@property (nonatomic, readonly) double dateNameBaselineVerticalInset;
@property (nonatomic, readonly) double dateNameDefaultFontSize;
@property (nonatomic, readonly) double dateNameFontWeight;
@property (nonatomic, readonly) double dateNameHorizontalInset;
@property (nonatomic, readonly) double dateNameLetterSpacing;
@property (nonatomic, readonly) double dateNameLongStringFontSize;
@property (nonatomic, readonly) double dayNumberBaselineVerticalInset;
@property (nonatomic, readonly) double dayNumberFontSize;
@property (nonatomic, readonly) double dayNumberTrackingValue;
@property (nonatomic, readonly) double minDateNameFontScale;
@property (nonatomic, readonly) double minDateNameLetterSpacing;
@property (nonatomic, readonly) double minFullDateNameFontScale;
@property (nonatomic, readonly) unsigned long long type;

- (double)bestRepresentedSideLength;
- (double)dateNameBaselineVerticalInset;
- (double)dateNameDefaultFontSize;
- (double)dateNameFontWeight;
- (double)dateNameHorizontalInset;
- (double)dateNameLetterSpacing;
- (double)dateNameLongStringFontSize;
- (double)dayNumberBaselineVerticalInset;
- (double)dayNumberFontSize;
- (double)dayNumberTrackingValue;
- (id)initWithType:(unsigned long long)arg1 bestRepresentedSideLength:(double)arg2 dayNumberFontSize:(double)arg3 dayNumberBaselineVerticalInset:(double)arg4 dayNumberTrackingValue:(double)arg5 dateNameBaselineVerticalInset:(double)arg6 dateNameHorizontalInset:(double)arg7 dateNameDefaultFontSize:(double)arg8 dateNameLongStringFontSize:(double)arg9 minFullDateNameFontScale:(double)arg10 minDateNameFontScale:(double)arg11 minDateNameLetterSpacing:(double)arg12 dateNameLetterSpacing:(double)arg13 dateNameFontWeight:(double)arg14;
- (double)minDateNameFontScale;
- (double)minDateNameLetterSpacing;
- (double)minFullDateNameFontScale;
- (unsigned long long)type;

@end
