/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoPassKit.framework/NanoPassKit
 */

@interface NPKProtoListSubcredentialInvitationsResponse : PBCodable <NSCopying> {
    NSData * _subcredentialInvitationsData;
}

@property (nonatomic, readonly) bool hasSubcredentialInvitationsData;
@property (nonatomic, retain) NSData *subcredentialInvitationsData;

- (void).cxx_destruct;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasSubcredentialInvitationsData;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)setSubcredentialInvitationsData:(id)arg1;
- (id)subcredentialInvitationsData;
- (void)writeTo:(id)arg1;

@end
