/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NotesShared.framework/NotesShared
 */

@interface ICSearchResultRanker : NSObject

+ (bool)bitAtPosition:(long long)arg1 isTrueInValue:(unsigned long long)arg2;
+ (id /* block */)bodyOfNoteOrAttachmentMatchingRule;
+ (unsigned long long)bucketOfTimeInterval:(double)arg1;
+ (id)initializeScoreArrayOfLength:(unsigned long long)arg1 setAllZeros:(bool)arg2;
+ (id)modificationDateBucketForSearchableItems:(id)arg1;
+ (id /* block */)participantNameOrEmailMatchingRule;
+ (id)rankingRulesByMatchedField;
+ (id)rankingScoresForSearchableItems:(id)arg1 withRankingQueryBitDictionary:(id)arg2 matchedFields:(id*)arg3 isPrefixMatch:(id*)arg4;
+ (id)relevanceBitFieldForSearchableItems:(id)arg1;
+ (id /* block */)titleOfNoteOrAttachmentMatchingRule;

@end
