/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/MediaMiningKit.framework/MediaMiningKit
 */

@interface CLSInvestigationPhotoKitFeeder : CLSInvestigationFeeder {
    NSArray * _allItems;
    PHAssetCollection * _assetCollection;
    PHFetchOptions * _assetFetchOptions;
    unsigned long long  _assetPrefetchOptions;
    PHFetchResult * _fetchResult;
    unsigned long long  _numberOfAllPeople;
    CLSFeederPrefetchOptions * _prefetchOptions;
}

@property (nonatomic, readonly) PHAssetCollection *assetCollection;
@property (nonatomic, readonly, copy) PHFetchOptions *assetFetchOptions;
@property (nonatomic, readonly) double behavioralScore;
@property (nonatomic, readonly) bool hasBestScoringAssets;
@property (nonatomic, readonly) bool hasFavoritedAssets;
@property (nonatomic, readonly) bool hasNonJunkAssets;
@property (nonatomic, readonly) bool hasPeople;
@property (nonatomic, readonly) unsigned long long numberOfAllPeople;
@property (nonatomic, readonly) unsigned long long numberOfRegularGemItems;
@property (nonatomic, readonly) unsigned long long numberOfShinyGemItems;
@property (nonatomic, readonly, copy) CLSFeederPrefetchOptions *prefetchOptions;

+ (id)feederForAssetCollection:(id)arg1 options:(id)arg2 feederPrefetchOptions:(id)arg3;

- (void).cxx_destruct;
- (bool)_shouldPrefetchCurationInformation;
- (id)allItems;
- (id)approximateLocation;
- (id)assetCollection;
- (id)assetFetchOptions;
- (double)behavioralScore;
- (void)enumerateItemsUsingBlock:(id /* block */)arg1;
- (void)enumerateItemsWithOptions:(unsigned long long)arg1 usingBlock:(id /* block */)arg2;
- (bool)hasBestScoringAssets;
- (bool)hasFavoritedAssets;
- (bool)hasNonJunkAssets;
- (bool)hasPeople;
- (id)initWithFeederWithAssetCollection:(id)arg1 assetFetchOptions:(id)arg2 feederPrefetchOptions:(id)arg3;
- (id)itemAtIndex:(unsigned long long)arg1;
- (struct CGImage { }*)itemThumbnailAtIndex:(unsigned long long)arg1 withResolution:(unsigned long long)arg2;
- (id)localEndDate;
- (id)localEndDateComponents;
- (id)localStartDate;
- (id)localStartDateComponents;
- (unsigned long long)numberOfAllPeople;
- (unsigned long long)numberOfItems;
- (unsigned long long)numberOfRegularGemItems;
- (unsigned long long)numberOfShinyGemItems;
- (id)prefetchOptions;
- (id)universalEndDate;
- (id)universalStartDate;

@end
