/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PUTemporaryImageTable : PLTemporaryImageTable {
    _Atomic int  _indexCounter;
}

- (int)nextCacheIndex;

@end
