/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXGAccessibilityContentInfoManager : PXObservable <PXGMutableAccessibilityContentInfoManager> {
    NSArray * _extendedAccessibilityContentInfos;
    NSArray * _extendedAccessibilityGroupContentInfos;
    NSArray * _visibleAccessibilityContentInfos;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSArray *extendedAccessibilityContentInfos;
@property (nonatomic, readonly) NSArray *extendedAccessibilityGroupContentInfos;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSArray *visibleAccessibilityContentInfos;

- (void).cxx_destruct;
- (id)extendedAccessibilityContentInfos;
- (id)extendedAccessibilityGroupContentInfos;
- (id)init;
- (void)performChanges:(id /* block */)arg1;
- (void)setExtendedAccessibilityContentInfos:(id)arg1;
- (void)setExtendedAccessibilityGroupContentInfos:(id)arg1;
- (void)setVisibleAccessibilityContentInfos:(id)arg1;
- (id)visibleAccessibilityContentInfos;

@end
