/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXGSplitLayout : PXGLayout {
    struct { 
        unsigned long long needsUpdate; 
        unsigned long long updated; 
        bool isPerformingUpdate; 
    }  _additionalUpdateFlags;
    PXGLayout * _firstSublayout;
    double  _interlayoutSpacing;
    bool  _isPerformingAdditionalUpdate;
    bool  _isUpdatingSublayouts;
    long long  _mode;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _padding;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _presentedPadding;
    PXGLayout * _secondSublayout;
    bool  _settingSublayouts;
    bool  _shouldExcludeTopAndBottomPaddingFromReferenceSize;
    struct { 
        unsigned long long needsUpdate; 
        unsigned long long updated; 
        bool isPerformingUpdate; 
    }  _updateFlags;
}

@property (nonatomic, retain) PXGLayout *firstSublayout;
@property (nonatomic) double interlayoutSpacing;
@property (nonatomic) long long mode;
@property (nonatomic) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } padding;
@property (nonatomic, readonly) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } presentedPadding;
@property (nonatomic, retain) PXGLayout *secondSublayout;
@property (nonatomic) bool shouldExcludeTopAndBottomPaddingFromReferenceSize;

- (void).cxx_destruct;
- (void)_replaceSublayout:(id)arg1 withSublayout:(id)arg2 atIndex:(long long)arg3;
- (void)_updateSublayoutGeometries;
- (void)containingScrollViewDidScroll:(struct CGPoint { double x1; double x2; })arg1;
- (void)didAddSublayout:(id)arg1 atIndex:(long long)arg2 flags:(unsigned long long)arg3;
- (void)didChangeSublayoutOrigins;
- (id)firstSublayout;
- (double)interlayoutSpacing;
- (long long)mode;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })padding;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })presentedPadding;
- (void)referenceSizeDidChange;
- (void)safeAreaInsetsDidChange;
- (void)screenScaleDidChange;
- (id)secondSublayout;
- (void)setFirstSublayout:(id)arg1;
- (void)setInterlayoutSpacing:(double)arg1;
- (void)setMode:(long long)arg1;
- (void)setPadding:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setSecondSublayout:(id)arg1;
- (void)setShouldExcludeTopAndBottomPaddingFromReferenceSize:(bool)arg1;
- (bool)shouldExcludeTopAndBottomPaddingFromReferenceSize;
- (void)sublayoutDidChangeContentSize:(id)arg1;
- (void)sublayoutDidChangeLastBaseline:(id)arg1;
- (void)sublayoutNeedsUpdate:(id)arg1;
- (void)update;
- (void)userInterfaceDirectionDidChange;
- (void)viewEnvironmentDidChange;
- (void)visibleRectDidChange;
- (void)willRemoveSublayout:(id)arg1 atIndex:(long long)arg2 flags:(unsigned long long)arg3;

@end
