/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXNavigationListItemDataSectionManager : PXDataSectionManager <PXCollectionFetchOperationDelegate, PXPhotoLibraryUIChangeObserver> {
    PHCollection * _collection;
    bool  _enabled;
    PHFetchResult * _fetchResult;
    bool  _hiddenWhenEmpty;
    NSOperationQueue * _workQueue;
}

@property (nonatomic, readonly) PHCollection *collection;
@property (getter=isCollectionEmpty, nonatomic, readonly) bool collectionEmpty;
@property (getter=isCollectionVisible, nonatomic, readonly) bool collectionVisible;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (getter=isEnabled, nonatomic) bool enabled;
@property (nonatomic, retain) PHFetchResult *fetchResult;
@property (readonly) unsigned long long hash;
@property (getter=isHiddenWhenEmpty, nonatomic) bool hiddenWhenEmpty;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSOperationQueue *workQueue;

- (void).cxx_destruct;
- (id)collection;
- (void)collectionFetchOperationDidComplete:(id)arg1;
- (id)createDataSection;
- (id)description;
- (id)fetchResult;
- (id)initWithChildDataSectionManagers:(id)arg1;
- (id)initWithCollection:(id)arg1 workQueue:(id)arg2;
- (bool)isCollectionEmpty;
- (bool)isCollectionVisible;
- (bool)isEnabled;
- (bool)isHiddenWhenEmpty;
- (void)photoLibraryDidChangeOnMainQueue:(id)arg1;
- (void)setEnabled:(bool)arg1;
- (void)setFetchResult:(id)arg1;
- (void)setHiddenWhenEmpty:(bool)arg1;
- (void)updateDataSectionIfNecessary;
- (id)workQueue;

@end
