/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXSmartAlbumStringValueCondition : PXSmartAlbumCondition

@property (nonatomic, retain) NSString *stringValue;

- (void)setStringValue:(id)arg1;
- (id)stringValue;

@end
