/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXSmartAlbumDescriptionCondition : PXSmartAlbumStringValueCondition

+ (id)defaultSingleQueryForEditingContext:(id)arg1;

@end
