/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXYearCardSectionBodyLayoutSpec : PXCuratedLibraryCardSectionBodyLayoutSpec

- (id)initWithExtendedTraitCollection:(id)arg1 options:(unsigned long long)arg2;

@end
