/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AXMediaUtilities.framework/AXMediaUtilities
 */

@interface AXMReplacementTag : AXMTag {
    struct _NSRange { 
        unsigned long long location; 
        unsigned long long length; 
    }  _overrideRange;
    NSString * _overrideSpeakableText;
}

+ (id)replacementTagWithSpeakableText:(id)arg1 range:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg2;

- (void).cxx_destruct;
- (id)originalText;
- (struct _NSRange { unsigned long long x1; unsigned long long x2; })range;
- (id)speakableText;

@end
