/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIWindowSceneUserInterfaceStyleAnimationSnapshotWindow : UIWindow

- (bool)_ignoresHitTest;

@end
