/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIKeyboardCandidateViewConfigurationHandwritingPad : UIKeyboardCandidateViewConfigurationHandwriting

- (id)initialState;

@end
