/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/BehaviorMiner.framework/BehaviorMiner
 */

@interface BMRule : NSObject {
    NSSet * _antecedent;
    double  _confidence;
    NSSet * _consequent;
    double  _support;
}

@property (nonatomic, retain) NSSet *antecedent;
@property (nonatomic) double confidence;
@property (nonatomic, retain) NSSet *consequent;
@property (nonatomic) double support;

- (void).cxx_destruct;
- (id)antecedent;
- (double)confidence;
- (id)consequent;
- (id)description;
- (unsigned long long)hash;
- (id)initWithAntecedent:(id)arg1 consequent:(id)arg2 support:(double)arg3 confidence:(double)arg4;
- (bool)isEqual:(id)arg1;
- (void)setAntecedent:(id)arg1;
- (void)setConfidence:(double)arg1;
- (void)setConsequent:(id)arg1;
- (void)setSupport:(double)arg1;
- (double)support;

@end
