/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AACCore.framework/AACCore
 */

@interface AEConcretePerformancePrimitives : NSObject <AEPerformancePrimitives> {
    NSString * _subsystem;
}

@property (nonatomic, readonly, copy) NSString *subsystem;

- (void).cxx_destruct;
- (id)beginIntervalWithCategory:(id)arg1 name:(id)arg2;
- (id)initWithSubsystem:(id)arg1;
- (id)subsystem;

@end
