/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AACCore.framework/AACCore
 */

@interface AEInvalidationRouter : NSObject {
    <AEInvalidationRouterDelegate> * _delegate;
    bool  _forwardError;
    long long  _mode;
    bool  _processedInvalidation;
    NSObject<OS_dispatch_queue> * _queue;
    NSError * _storedError;
}

@property (nonatomic) <AEInvalidationRouterDelegate> *delegate;
@property (getter=didForwardError, nonatomic) bool forwardError;
@property (nonatomic, readonly) id /* block */ invalidationHandler;
@property (nonatomic) long long mode;
@property (getter=hasProcessedInvalidation, nonatomic) bool processedInvalidation;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *queue;
@property (nonatomic, retain) NSError *storedError;

- (void).cxx_destruct;
- (id)delegate;
- (bool)didForwardError;
- (void)fetchCapturedErrorWithCompletion:(id /* block */)arg1;
- (void)forwardError;
- (bool)hasProcessedInvalidation;
- (id)init;
- (id /* block */)invalidationHandler;
- (long long)mode;
- (id)queue;
- (void)setDelegate:(id)arg1;
- (void)setForwardError:(bool)arg1;
- (void)setMode:(long long)arg1;
- (void)setProcessedInvalidation:(bool)arg1;
- (void)setRouterDelegate:(id)arg1;
- (void)setRouterMode:(long long)arg1;
- (void)setStoredError:(id)arg1;
- (id)storedError;

@end
