/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech
 */

@interface CSSpeakerIdRecognizerFactory : NSObject

- (id)init;
- (id)speakerIdRecognizerWithContext:(id)arg1 delegate:(id)arg2;

@end
