/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FrontBoard.framework/FrontBoard
 */

@interface FBSystemShellInitializationContext : NSObject <NSCopying> {
    bool  _bootedDark;
    FBSystemShellInitializationOptions * _options;
}

@property (getter=wasBootedDark, nonatomic, readonly) bool bootedDark;
@property (nonatomic, readonly) unsigned long long lastExitReason;
@property (nonatomic, readonly) FBSystemShellInitializationOptions *options;

- (void).cxx_destruct;
- (bool)_disablesUIKitWindowImplicitScenes;
- (id)_initWithOptions:(id)arg1;
- (bool)_optsIntoUIKitWindowHosting;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned long long)lastExitReason;
- (id)options;
- (bool)wasBootedDark;

@end
