/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FrontBoard.framework/FrontBoard
 */

@interface FBSystemShellInitializationOptions : NSObject <NSCopying, NSMutableCopying> {
    bool  _initializeReadyForInteraction;
    bool  _isLegacyFBSystemApp;
    id /* block */  _registerLegacyPostInitCallbackBlock;
    id /* block */  _registerPostCheckInPreServiceInitializationCallbackBlock;
    id /* block */  _registerServicesBlock;
    bool  _resetDarkBootState;
    bool  _shouldWaitForMigrator;
    double  _systemSleepInterval;
}

@property (nonatomic, readonly) bool _isLegacyFBSystemApp;
@property (nonatomic, readonly, copy) id /* block */ _registerLegacyPostInitCallbackBlock;
@property (nonatomic, readonly, copy) id /* block */ _registerPostCheckInPreServiceInitializationCallbackBlock;
@property (nonatomic, readonly) bool initializeReadyForInteraction;
@property (nonatomic, readonly, copy) id /* block */ registerAdditionalServicesBlock;
@property (nonatomic, readonly) bool resetDarkBootState;
@property (nonatomic, readonly) bool shouldWaitForMigrator;
@property (nonatomic, readonly) double systemSleepInterval;

- (void).cxx_destruct;
- (id)_initWithOptions:(id)arg1;
- (bool)_isLegacyFBSystemApp;
- (id /* block */)_registerLegacyPostInitCallbackBlock;
- (id /* block */)_registerPostCheckInPreServiceInitializationCallbackBlock;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned long long)hash;
- (id)init;
- (bool)initializeReadyForInteraction;
- (bool)isEqual:(id)arg1;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (id /* block */)registerAdditionalServicesBlock;
- (bool)resetDarkBootState;
- (bool)shouldWaitForMigrator;
- (double)systemSleepInterval;

@end
