/* Generated by EzioChiu
   Image: /System/Library/Frameworks/GameController.framework/GameController
 */

@interface GCAnalytics : NSObject {
    NSString * _bundleID;
    NSMutableDictionary * _controllersData;
    NSTimer * _eventPollTimer;
}

+ (id)instance;

- (void).cxx_destruct;
- (void)checkMultipleControllers;
- (void)dealloc;
- (id)getBundleID;
- (id)init;
- (void)onSiriMotionEnabled;
- (void)publishController:(id)arg1;
- (void)runInputPollTimer;
- (void)sendInputsPressedEvent:(const struct { int x1; int x2; int x3; int x4; int x5; int x6; int x7; int x8; int x9; int x10; int x11; int x12; int x13; int x14; int x15; }*)arg1;
- (void)unpublishController:(id)arg1;

@end
