/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VideoProcessing.framework/VideoProcessing
 */

@interface VCPCNNHandKeypointsDetectorEspresso : VCPCNNHandKeypointsDetector {
    float * _inputData;
    VCPCNNModelEspresso * _modelEspresso;
}

- (void).cxx_destruct;
- (void)dealloc;
- (int)generateHandKeypoints:(struct CGPoint { double x1; double x2; }*)arg1;
- (float*)getInputBuffer:(int)arg1 srcWidth:(int)arg2 cnnInputHeight:(int*)arg3 cnnInputWidth:(int*)arg4;
- (id)init;

@end
