/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VideoProcessing.framework/VideoProcessing
 */

@interface VCPCNNFastGestureRecognition : NSObject

+ (id)detector;

- (int)copyImage:(struct __CVBuffer { }*)arg1 toData:(float*)arg2 withChunk:(int)arg3;
- (int)createInput:(float*)arg1 withBuffer:(struct __CVBuffer { }*)arg2 cnnInputHeight:(int)arg3 cnnInputWidth:(int)arg4;
- (int)createModel:(int)arg1 srcWidth:(int)arg2;
- (int)gestureDetection:(struct __CVBuffer { }*)arg1 score:(float*)arg2;
- (int)getDetectionScore:(float*)arg1;
- (float*)getInputBuffer:(int)arg1 srcWidth:(int)arg2 cnnInputHeight:(int*)arg3 cnnInputWidth:(int*)arg4;
- (int)planDestroy;

@end
