/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VideoProcessing.framework/VideoProcessing
 */

@interface VCPDefaultPhotoLibraryManager : NSObject

+ (id)sharedManager;

- (id)defaultPhotoLibrary;
- (id)init;

@end
