/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VideoProcessing.framework/VideoProcessing
 */

@interface VCPMediaAnalyzer : NSObject {
    NSObject<OS_dispatch_queue> * _analysisQueue;
    NSXPCConnection * _connection;
    bool  _noResultStrip;
    NSMutableDictionary * _sandboxHandles;
    NSObject<OS_dispatch_queue> * _sandboxQueue;
    bool  _standalone;
    NSObject<OS_dispatch_group> * _storageGroup;
    NSObject<OS_dispatch_queue> * _storageQueue;
}

+ (Class)_getDistanceDescriptorClass;
+ (id)sharedMediaAnalyzer;

- (void).cxx_destruct;
- (id)_addClassificationResults:(id)arg1 analysis:(id)arg2;
- (id)_analyzeOndemand:(id)arg1 forAnalysisTypes:(unsigned long long)arg2 withExistingAnalysis:(id)arg3 storeAnalysis:(bool)arg4;
- (void)_checkDuplicate:(id)arg1 withAsset:(id)arg2 duplicate:(long long*)arg3;
- (id)_databaseForPhotoLibrary:(id)arg1;
- (long long)_getDatabaseSandboxExtensionForPhotoLibraryURL:(id)arg1;
- (void)_getSceneDescriptors:(id)arg1 asDescriptorClass:(Class)arg2 withSceneRange:(struct { struct { long long x_1_1_1; int x_1_1_2; unsigned int x_1_1_3; long long x_1_1_4; } x1; struct { long long x_2_1_1; int x_2_1_2; unsigned int x_2_1_3; long long x_2_1_4; } x2; })arg3 andAnalysisResults:(id)arg4;
- (unsigned long long)_metaAnalysisTypesForAsset:(id)arg1;
- (id)_queryDistanceDescriptor:(Class)arg1 ofAsset:(id)arg2 withExistingAnalysis:(id)arg3 andDatabase:(id)arg4 timeRange:(struct { struct { long long x_1_1_1; int x_1_1_2; unsigned int x_1_1_3; long long x_1_1_4; } x1; struct { long long x_2_1_1; int x_2_1_2; unsigned int x_2_1_3; long long x_2_1_4; } x2; })arg5 lastFeature:(bool)arg6 isDegraded:(bool*)arg7;
- (unsigned long long)_typesToRemove:(unsigned long long)arg1 requested:(unsigned long long)arg2;
- (void)assetsAnalyzedSinceDate:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)assetsFromPhotoLibrary:(id)arg1 analyzedSinceDate:(id)arg2 completionHandler:(id /* block */)arg3;
- (bool)cancelAnalysisWithRequestID:(int)arg1;
- (void)completeStorage;
- (id)connection;
- (id)curateMovieAssetsForCollection:(id)arg1 withAlreadyCuratedAssets:(id)arg2 andDesiredCount:(unsigned long long)arg3 allowOnDemand:(bool)arg4;
- (void)dealloc;
- (void)distanceFromAsset:(id)arg1 timeRange:(struct { struct { long long x_1_1_1; int x_1_1_2; unsigned int x_1_1_3; long long x_1_1_4; } x1; struct { long long x_2_1_1; int x_2_1_2; unsigned int x_2_1_3; long long x_2_1_4; } x2; })arg2 toAsset:(id)arg3 timeRange:(struct { struct { long long x_1_1_1; int x_1_1_2; unsigned int x_1_1_3; long long x_1_1_4; } x1; struct { long long x_2_1_1; int x_2_1_2; unsigned int x_2_1_3; long long x_2_1_4; } x2; })arg4 duplicate:(long long*)arg5 distance:(float*)arg6;
- (void)distanceFromAsset:(id)arg1 toAsset:(id)arg2 duplicate:(long long*)arg3 distance:(float*)arg4;
- (id)init;
- (int)requestAnalysesForAssets:(id)arg1 analysisTypes:(unsigned long long)arg2 allowOndemand:(bool)arg3 progressHandler:(id /* block */)arg4 completionHandler:(id /* block */)arg5;
- (int)requestAnalysisForAsset:(id)arg1 analysisTypes:(unsigned long long)arg2 progressHandler:(id /* block */)arg3 completionHandler:(id /* block */)arg4;
- (id)requestAnalysisForAsset:(id)arg1 withExistingAnalysis:(id)arg2 andDatabase:(id)arg3 analysisTypes:(unsigned long long)arg4 allowOndemand:(bool)arg5;
- (int)requestAnalysisTypes:(unsigned long long)arg1 forAssets:(id)arg2 allowOndemand:(bool)arg3 progressHandler:(id /* block */)arg4 analyses:(id)arg5;
- (id)requestAnalysisTypes:(unsigned long long)arg1 forAssets:(id)arg2 allowOndemand:(bool)arg3 progressHandler:(id /* block */)arg4 error:(id*)arg5;
- (id)requestCallerIdentificationForFaces:(id)arg1;
- (id)requestLivePhotoEffectsForAssets:(id)arg1 allowOnDemand:(bool)arg2 flags:(unsigned long long)arg3;
- (id)requestMovieHighlightsForAssets:(id)arg1;

@end
