/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreWiFi.framework/CoreWiFi
 */

@interface CWFInterface : NSObject {
    CWFClient * _client;
    NSString * _interfaceName;
}

@property (nonatomic, retain) CWFClient *client;
@property (nonatomic, copy) NSString *interfaceName;

+ (id)interfaceWithClient:(id)arg1 interfaceName:(id)arg2;

- (void).cxx_destruct;
- (id)APSTAInterface;
- (id)AWDLElectionID;
- (id)AWDLElectionParameters;
- (id)AWDLElectionRSSIThresholds;
- (id)AWDLInterface;
- (id)AWDLMasterChannel;
- (id)AWDLOpMode;
- (id)AWDLPeerDatabase;
- (id)AWDLPreferredChannels;
- (id)AWDLSecondaryMasterChannel;
- (id)AWDLSidecarDiagnostics;
- (id)AWDLSocialTimeSlots;
- (id)AWDLStatistics;
- (id)AWDLStrategy;
- (id)AWDLSyncChannelSequence;
- (id)AWDLSyncEnabled;
- (id)AWDLSyncParameters;
- (id)AWDLSyncState;
- (id)BSSID;
- (id)BSSIDHash;
- (id)DHCPLeaseExpiresAt;
- (id)DHCPLeaseStartedAt;
- (id)DNSServerAddresses;
- (unsigned long long)DTIMInterval;
- (int)EAP8021XClientStatus;
- (unsigned int)EAP8021XControlMode;
- (unsigned int)EAP8021XControlState;
- (unsigned int)EAP8021XSupplicantState;
- (id)IO80211ControllerInfo;
- (id)IO80211InterfaceInfo;
- (id)IPv4Addresses;
- (id)IPv4RouterAddress;
- (id)IPv6Addresses;
- (id)IPv6RouterAddress;
- (id)MACAddress;
- (unsigned long long)MCSIndex;
- (int)PHYMode;
- (long long)RSSI;
- (id)SSID;
- (id)SSIDHash;
- (long long)WAPISubtype;
- (long long)WEPSubtype;
- (id)__authDataFromClient;
- (int)__flagsForChannelWidth:(int)arg1;
- (bool)associateWithParameters:(id)arg1 error:(id*)arg2;
- (id)associateWithParameters:(id)arg1 reply:(id /* block */)arg2;
- (id)authType;
- (id)autoJoinStatus;
- (id)capabilities;
- (id)channel;
- (id)client;
- (id)countryCode;
- (id)currentKnownNetworkProfile;
- (id)currentScanResult;
- (void)disassociateWithReason:(long long)arg1;
- (unsigned long long)guardInterval;
- (id)interfaceName;
- (bool)isNetworkServiceEnabled;
- (id)joinStatus;
- (id)linkDownStatus;
- (id)networkName;
- (id)networkServiceID;
- (id)networkServiceName;
- (long long)noise;
- (unsigned long long)numberOfSpatialStreams;
- (int)opMode;
- (id)parentInterfaceName;
- (id)performANQPWithParameters:(id)arg1 error:(id*)arg2;
- (id)performANQPWithParameters:(id)arg1 reply:(id /* block */)arg2;
- (id)performRangingWithPeerList:(id)arg1 timeout:(unsigned long long)arg2 error:(id*)arg3;
- (id)performRangingWithPeerList:(id)arg1 timeout:(unsigned long long)arg2 reply:(id /* block */)arg3;
- (id)performScanWithParameters:(id)arg1 error:(id*)arg2;
- (id)performScanWithParameters:(id)arg1 reply:(id /* block */)arg2;
- (bool)powerOn;
- (id)rangingCapabilities;
- (id)roamStatus;
- (unsigned long long)securityType;
- (bool)setAWDLPeerTrafficRegistration:(id)arg1 error:(id*)arg2;
- (bool)setChannel:(id)arg1 error:(id*)arg2;
- (void)setClient:(id)arg1;
- (void)setInterfaceName:(id)arg1;
- (bool)setPower:(bool)arg1 error:(id*)arg2;
- (bool)setRangeable:(bool)arg1 peerList:(id)arg2 error:(id*)arg3;
- (bool)startAWDLPeerAssistedDiscoveryWithParameters:(id)arg1 error:(id*)arg2;
- (void)stopAWDLPeerAssistedDiscovery;
- (id)supportedChannel:(unsigned long long)arg1 width:(int)arg2 countryCode:(id)arg3;
- (id)supportedChannelsWithCountryCode:(id)arg1;
- (int)supportedPHYModes;
- (id)systemAWDLPeerTrafficRegistrations;
- (double)txPower;
- (double)txRate;
- (id)virtualInterfaceNames;
- (int)virtualInterfaceRole;
- (id)virtualInterfaceWithRole:(int)arg1;
- (bool)wakeOnWirelessEnabled;

@end
