/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/KnowledgeMonitor.framework/KnowledgeMonitor
 */

@interface _DKWiFiConnectionMonitor : _DKMonitor {
    NSString * _currentWirelessSSID;
    NWPathEvaluator * _pathEvaluator;
}

@property (nonatomic, copy) NSString *currentWirelessSSID;
@property (nonatomic, retain) NWPathEvaluator *pathEvaluator;

- (void).cxx_destruct;
- (id)currentWirelessSSID;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (id)pathEvaluator;
- (void)setCurrentWirelessSSID:(id)arg1;
- (void)setPathEvaluator:(id)arg1;
- (void)start;
- (void)stop;

@end
