/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface HKSelectedRangeData : NSObject {
    NSAttributedString * _attributedString;
    long long  _dataType;
    long long  _statisticsType;
    NSNumber * _valueAsNumber;
}

@property (nonatomic, retain) NSAttributedString *attributedString;
@property (nonatomic) long long dataType;
@property (nonatomic) long long statisticsType;
@property (nonatomic, retain) NSNumber *valueAsNumber;

- (void).cxx_destruct;
- (id)attributedString;
- (long long)dataType;
- (id)initWithStatisticsType:(long long)arg1;
- (void)setAttributedString:(id)arg1;
- (void)setDataType:(long long)arg1;
- (void)setStatisticsType:(long long)arg1;
- (void)setValueAsNumber:(id)arg1;
- (long long)statisticsType;
- (id)valueAsNumber;

@end
