/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PodcastsKit.framework/PodcastsKit
 */

@interface IMExpandingLabelAccessibility : IMExpandingLabelAccessibility_super

+ (void)_initializeSafeCategory;

- (id)_accessibilityHitTest:(struct CGPoint { double x1; double x2; })arg1 withEvent:(id)arg2;
- (id)_accessiblityChildren;
- (id)accessibilityElementAtIndex:(long long)arg1;
- (long long)accessibilityElementCount;
- (id)accessibilityLabel;
- (void)dealloc;
- (long long)indexOfAccessibilityElement:(id)arg1;
- (bool)isAccessibilityElement;

@end
