/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PodcastsKit.framework/PodcastsKit
 */

@interface IMFetchPushNotificationSettingsService : IMPushNotificationSettingsService

- (id)init;
- (id)urlRequestWithError:(id*)arg1;

@end
