/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PodcastsKit.framework/PodcastsKit
 */

@interface IMIgnoreRedirectURLAction : AMSURLAction

+ (id)ignoreRedirectAction;

- (long long)actionType;
- (id)redirectURL;

@end
