/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PodcastsKit.framework/PodcastsKit
 */

@interface IMJSONUtil : NSObject

+ (id)fromJSONData:(id)arg1;
+ (id)fromJSONString:(id)arg1;
+ (id)toJSONString:(id)arg1;

@end
