/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PodcastsKit.framework/PodcastsKit
 */

@interface MTMediaTask : NSObject {
    AMSMediaTask * _mediaTask;
}

@property (nonatomic, retain) NSArray *identifiers;
@property (nonatomic, retain) AMSMediaTask *mediaTask;

- (void).cxx_destruct;
- (id)identifiers;
- (id)initWithType:(long long)arg1;
- (id)mediaTask;
- (void)perform:(id /* block */)arg1;
- (void)setIdentifiers:(id)arg1;
- (void)setMediaTask:(id)arg1;

@end
