/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PodcastsKit.framework/PodcastsKit
 */

@interface MTUTIUtil : NSObject

+ (id)convertUti:(id)arg1;
+ (bool)isAudio:(id)arg1;
+ (bool)isVideo:(id)arg1;

@end
