/* Generated by EzioChiu
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@interface WKBrowsingContextHandle : NSObject <NSSecureCoding> {
    struct ObjectIdentifier<WebKit::WebPageProxyIdentifierType> { 
        unsigned long long m_identifier; 
    }  _pageProxyID;
    struct ObjectIdentifier<WebCore::PageIdentifierType> { 
        unsigned long long m_identifier; 
    }  _webPageID;
}

@property (getter=_pageProxyID, nonatomic, readonly) struct ObjectIdentifier<WebKit::WebPageProxyIdentifierType> { unsigned long long x1; } pageProxyID;
@property (getter=_webPageID, nonatomic, readonly) struct ObjectIdentifier<WebCore::PageIdentifierType> { unsigned long long x1; } webPageID;

+ (bool)supportsSecureCoding;

- (id).cxx_construct;
- (id)_initWithPage:(struct WebPage { int (**x1)(); id x2; int (**x3)(); int (**x4)(); struct WeakPtrFactory<WebKit::WebPage> { struct RefPtr<WTF::WeakPtrImpl, WTF::DumbPtrTraits<WTF::WeakPtrImpl> > { struct WeakPtrImpl {} *x_1_2_1; } x_5_1_1; } x5; struct ObjectIdentifier<WebCore::PageIdentifierType> { unsigned long long x_6_1_1; } x6; struct unique_ptr<WebCore::Page, std::__1::default_delete<WebCore::Page> > { struct __compressed_pair<WebCore::Page *, std::__1::default_delete<WebCore::Page> > { struct Page {} *x_1_2_1; } x_7_1_1; } x7; struct RefPtr<WebKit::WebFrame, WTF::DumbPtrTraits<WebKit::WebFrame> > { struct WebFrame {} *x_8_1_1; } x8; struct RefPtr<WebKit::WebPageGroupProxy, WTF::DumbPtrTraits<WebKit::WebPageGroupProxy> > { struct WebPageGroupProxy {} *x_9_1_1; } x9; struct String { struct RefPtr<WTF::StringImpl, WTF::DumbPtrTraits<WTF::StringImpl> > { struct StringImpl {} *x_1_2_1; } x_10_1_1; } x10; struct IntSize { int x_11_1_1; int x_11_1_2; } x11; struct unique_ptr<WebKit::DrawingArea, std::__1::default_delete<WebKit::DrawingArea> > { struct __compressed_pair<WebKit::DrawingArea *, std::__1::default_delete<WebKit::DrawingArea> > { struct DrawingArea {} *x_1_2_1; } x_12_1_1; } x12; }*)arg1;
- (id)_initWithPageProxy:(struct WebPageProxy { int (**x1)(); id x2; int (**x3)(); int (**x4)(); int (**x5)(); int (**x6)(); int (**x7)(); int (**x8)(); struct WeakPtrFactory<WebKit::WebPageProxy> { struct RefPtr<WTF::WeakPtrImpl, WTF::DumbPtrTraits<WTF::WeakPtrImpl> > { struct WeakPtrImpl {} *x_1_2_1; } x_9_1_1; } x9; struct RetainPtr<NSArray> { void *x_10_1_1; } x10; struct ObjectIdentifier<WebKit::WebPageProxyIdentifierType> { unsigned long long x_11_1_1; } x11; struct ObjectIdentifier<WebCore::PageIdentifierType> { unsigned long long x_12_1_1; } x12; struct WeakPtr<WebKit::PageClient> { struct RefPtr<WTF::WeakPtrImpl, WTF::DumbPtrTraits<WTF::WeakPtrImpl> > { struct WeakPtrImpl {} *x_1_2_1; } x_13_1_1; } x13; struct Ref<API::PageConfiguration, WTF::DumbPtrTraits<API::PageConfiguration> > { struct PageConfiguration {} *x_14_1_1; } x14; struct unique_ptr<API::LoaderClient, std::__1::default_delete<API::LoaderClient> > { struct __compressed_pair<API::LoaderClient *, std::__1::default_delete<API::LoaderClient> > { struct LoaderClient {} *x_1_2_1; } x_15_1_1; } x15; }*)arg1;
- (id)_initWithPageProxyID:(struct ObjectIdentifier<WebKit::WebPageProxyIdentifierType> { unsigned long long x1; })arg1 andWebPageID:(struct ObjectIdentifier<WebCore::PageIdentifierType> { unsigned long long x1; })arg2;
- (struct ObjectIdentifier<WebKit::WebPageProxyIdentifierType> { unsigned long long x1; })_pageProxyID;
- (struct ObjectIdentifier<WebCore::PageIdentifierType> { unsigned long long x1; })_webPageID;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (bool)isEqual:(id)arg1;

@end
