/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/JetEngine.framework/JetEngine
 */

@interface JetEngine.InMemoryMetricsEventRecorder : _TtCs12_SwiftObject {
    void events;
    void historySize;
    void onEventRecorded;
    void stateLock;
}

@end
