/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/EmailFoundation.framework/EmailFoundation
 */

@interface _EFSQLDistinctExpression : NSObject <EFSQLExpressable> {
    <EFSQLExpressable> * _expression;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSString *ef_SQLExpression;
@property (nonatomic, readonly) <EFSQLExpressable> *expression;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)ef_SQLExpression;
- (id)expression;
- (id)initWithExpression:(id)arg1;

@end
