/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CalendarNotification.framework/CalendarNotification
 */

@interface CALNEventRepresentationDataSourceUtils : NSObject

+ (id)_userActivityUserInfoForEvent:(id)arg1;
+ (void)updateEventRepresentation:(id)arg1 forEvent:(id)arg2;

@end
