/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ShazamKit.framework/ShazamKit
 */

@interface SHMediaItem : NSObject <NSSecureCoding> {
    NSDictionary * _resultDictionary;
}

@property (nonatomic, readonly) NSDictionary *resultDictionary;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)debugDescription;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithResultDictionary:(id)arg1;
- (id)objectForKeyedSubscript:(id)arg1;
- (id)resultDictionary;
- (id)valueForProperty:(id)arg1;

@end
