/* Generated by EzioChiu
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface _PUEditActionPluginApplicationExtensionActivity : UIApplicationExtensionActivity

+ (long long)activityCategory;

@end
