/* Generated by EzioChiu
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUSearchDataUtility : NSObject

+ (id)oneYearAgoSearchToken;
+ (id)searchTokenFromZeroKeyword:(id)arg1;
+ (id)searchTokensFromRecentSearch:(id)arg1;

@end
