/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface _TtCC8VideosUI19VerticalStackLayout16HangerViewLayout : VideosUI.ViewLayout {
    void imageLayout;
}

@end
