/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface VideosUI.RelationalLayout : _TtCs12_SwiftObject <NSCopying> {
    void relations;
}

- (id)copyWithZone:(void*)arg1;

@end
