/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface VUILabelFactory : NSObject

+ (id)labelWithElement:(id)arg1 textLayout:(id)arg2 existingLabel:(id)arg3;

@end
