/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/RunningBoard.framework/RunningBoard
 */

@interface RBComplexConcreteTarget : RBConcreteTarget {
    NSString * _description;
    NSString * _environment;
    RBSProcessIdentity * _identity;
    RBProcess * _process;
}

- (void).cxx_destruct;
- (id)_initWithProcess:(id)arg1 identity:(id)arg2 environment:(id)arg3;
- (id)createRBSTarget;
- (id)description;
- (id)environment;
- (unsigned long long)hash;
- (id)identity;
- (bool)isEqual:(id)arg1;
- (bool)isSystem;
- (id)process;

@end
