/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CoreKnowledge.ScrubOldRecords : CoreKnowledge.DeferrableXPCOperation {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  cutoffDate;
}

- (void).cxx_destruct;
- (id)init;
- (void)main;

@end
