/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CrashSimulator : NSObject

+ (void)simulateCrashForErrorType:(id)arg1 description:(id)arg2 code:(id)arg3;

@end
