/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface SRBackgroundQueue : NSOperationQueue {
    void lock;
}

+ (id)shared;

- (void).cxx_destruct;
- (id)init;

@end
