/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PersonalizationPortraitInternals.framework/PersonalizationPortraitInternals
 */

@interface PPSQLKVStore : NSObject

+ (id)loadBlobForKey:(id)arg1 transaction:(id)arg2;
+ (void)removeBlobForKey:(id)arg1 transaction:(id)arg2;
+ (void)storeBlob:(id)arg1 forKey:(id)arg2 transaction:(id)arg3;

@end
