/* Generated by EzioChiu
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface _HKSampleQueryConfiguration : HKQueryServerConfiguration {
    bool  _includeAutomaticTimeZones;
    unsigned long long  _limit;
    NSArray * _sortDescriptors;
}

@property (nonatomic) bool includeAutomaticTimeZones;
@property (nonatomic) unsigned long long limit;
@property (nonatomic, copy) NSArray *sortDescriptors;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)encodeWithCoder:(id)arg1;
- (bool)includeAutomaticTimeZones;
- (id)initWithCoder:(id)arg1;
- (unsigned long long)limit;
- (void)setIncludeAutomaticTimeZones:(bool)arg1;
- (void)setLimit:(unsigned long long)arg1;
- (void)setSortDescriptors:(id)arg1;
- (id)sortDescriptors;

@end
