/* Generated by EzioChiu
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKFeatureAvailabilityWatchCompanionDevicePlatformEqualsRule : HKFeatureAvailabilityBaseRule <HKFeatureAvailabilityRule> {
    NSString * _devicePlatform;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSString *devicePlatform;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)ruleIdentifier;

- (void).cxx_destruct;
- (id)devicePlatform;
- (bool)evaluate;
- (void)processUserInfo:(id)arg1;
- (void)setDevicePlatform:(id)arg1;

@end
