/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoWeatherComplicationsCompanion.framework/NanoWeatherComplicationsCompanion
 */

@interface NWCConditionsTemplateFormatter : NSObject <NWCTemplateFormattable> {
    CLKTextProvider * _noDataTextProvider;
    NWMTemperatureFormatter * _temperatureFormatter;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) CLKTextProvider *noDataTextProvider;
@property (readonly) Class superclass;
@property (nonatomic, retain) NWMTemperatureFormatter *temperatureFormatter;

+ (id)sharedFormatter;

- (void).cxx_destruct;
- (id)_graphicRectangularTemplateWithTextProvider:(id)arg1 hourlyForecastedConditions:(id)arg2 timeZone:(id)arg3;
- (bool)acceptsComplicationFamily:(long long)arg1 forDevice:(id)arg2;
- (id)circularMediumTemplateForConditions:(id)arg1;
- (id)circularSmallTemplateForConditions:(id)arg1;
- (id)extraLargeTemplateForConditions:(id)arg1;
- (id)graphicBezelTemplateForConditions:(id)arg1 dailyForecastedConditions:(id)arg2;
- (id)graphicCircularTemplateForConditions:(id)arg1;
- (id)graphicCornerTemplateForConditions:(id)arg1;
- (id)graphicRectangularTemplateForLocalLocation:(bool)arg1 timeZone:(id)arg2 conditions:(id)arg3 dailyForecastedConditions:(id)arg4 hourlyForecastedConditions:(id)arg5;
- (id)modularSmallTemplateForConditions:(id)arg1;
- (id)noDataTextProvider;
- (void)setNoDataTextProvider:(id)arg1;
- (void)setTemperatureFormatter:(id)arg1;
- (id)switcherTemplateWithFamily:(long long)arg1;
- (id)temperatureFormatter;
- (id)utilitarianSmallTemplateForConditions:(id)arg1;

@end
