/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeKitBackingStore.framework/HomeKitBackingStore
 */

@interface HMBModelFieldOptionExcludeFromCloudStorage : HMBModelFieldOption

- (void)applyTo:(id)arg1;

@end
