/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HearingUtilities.framework/HearingUtilities
 */

@interface AXHAAudioBufferData : NSObject {
    AVAudioPCMBuffer * _buffer;
    SNDetectionResult * _result;
    AVAudioTime * _when;
}

@property (nonatomic, retain) AVAudioPCMBuffer *buffer;
@property (nonatomic, retain) SNDetectionResult *result;
@property (nonatomic, retain) AVAudioTime *when;

- (void).cxx_destruct;
- (id)buffer;
- (id)initWithBuffer:(id)arg1 andTime:(id)arg2;
- (id)result;
- (void)setBuffer:(id)arg1;
- (void)setResult:(id)arg1;
- (void)setWhen:(id)arg1;
- (id)when;

@end
