/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HearingUtilities.framework/HearingUtilities
 */

@interface HUUtilities : NSObject {
    NSDictionary * _pickableRoutes;
    NSObject<OS_dispatch_queue> * _routingQueue;
    bool  _takingConnection;
    bool  _wirelessSplitterEnabled;
    int  _wirelessSplitterNotifyToken;
}

@property (nonatomic, retain) NSObject<OS_dispatch_queue> *routingQueue;
@property (nonatomic) bool takingConnection;

+ (id)XDCObjectFromObject:(id)arg1;
+ (id)objectFromXDCObject:(id)arg1;
+ (id)sharedUtilities;

- (void).cxx_destruct;
- (void)addHearingFeatureUsage:(unsigned long long)arg1;
- (void)checkAudioPlayingWithQueue:(id)arg1 andCompletion:(id /* block */)arg2;
- (void)clearAudioRoutes;
- (id)currentPickableAudioRoutes;
- (void)dealloc;
- (bool)hearingAidRouteAvailable;
- (bool)hearingAidStreamSelected;
- (id)init;
- (bool)liveListenRouteSelected;
- (void)mediaServerDied;
- (bool)oldRoutes:(id)arg1 equalToNewRoutes:(id)arg2;
- (void)pauseNowPlaying:(bool)arg1 withQueue:(id)arg2 andCompletion:(id /* block */)arg3;
- (void)pickableAudioRoutesDidChange:(id)arg1;
- (void)registerNotifications;
- (id)routingQueue;
- (void)setRoutingQueue:(id)arg1;
- (void)setTakingConnection:(bool)arg1;
- (bool)takingConnection;
- (void)updateHearingFeatureUsage;
- (void)updateWirelessSplitterState;

@end
