/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/Message.framework/Message
 */

@interface MFCertificateTrustInfoEMCertificateTrustInformationTransformer : NSObject

+ (id)certificateTrustInformationFromMFCertificateTrustInfo:(id)arg1;

@end
