/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXDuetDataProvider : NSObject {
    NSArray * _streamData;
}

@property (nonatomic, readonly) NSArray *streamData;

+ (id)duetHelperStreamTypeToDuetEventStream:(long long)arg1;
+ (long long)supportedCoreDuetStream;
+ (Class)supportedDuetEventClass;

- (void).cxx_destruct;
- (id)fetchEventIdentifierCountsBetweenStartDate:(id)arg1 andEndDate:(id)arg2 withPredicates:(id)arg3;
- (id)fetchEventsBetweenStartDate:(id)arg1 andEndDate:(id)arg2 withPredicates:(id)arg3;
- (id)filteredEventsWithPredicate:(id)arg1;
- (id)getUniqueValuesForPropertyKey:(id)arg1;
- (id)streamData;
- (void)tagEventsWithLocationsFromLocationVisitsArray:(id)arg1;

@end
