/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TeaUI.framework/TeaUI
 */

@interface _TtCC5TeaUI13CommandCenterP33_15CAAAE3F54018A7CB89109419CFFB4715CommandObserver : _TtCs12_SwiftObject {
    void closure;
    void keepAliveObject;
}

@end
