/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TeaUI.framework/TeaUI
 */

@interface TeaUI.BlueprintGutterViewManager : _TtCs12_SwiftObject {
    void isHidden;
    void leftGutterView;
    void rightGutterView;
    void viewController;
}

@end
