/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TeaUI.framework/TeaUI
 */

@interface TeaUI.CommandContextStore : _TtCs12_SwiftObject {
    void contexts;
    void onChange;
}

@end
