/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TeaUI.framework/TeaUI
 */

@interface TeaUI.KeyCommandUnownedProvider : _TtCs12_SwiftObject {
    void invalidator;
    void provider;
}

@end
