/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TeaUI.framework/TeaUI
 */

@interface TeaUI.CommandExecutionSource : _TtCs12_SwiftObject {
    void onExecuteBlock;
    void sourceView;
}

@end
