/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/OnBoardingKit.framework/OnBoardingKit
 */

@interface OBBoldTrayButton : OBTrayButton

+ (id)boldButton;

- (void)_setButtonBackgroundColor:(id)arg1;
- (void)tintColorDidChange;

@end
