/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CameraUI.framework/CameraUI
 */

@interface CAMDrawerLowLightButton : CAMControlDrawerCustomButton {
    bool  _disabled;
    bool  _on;
}

@property (getter=isDisabled, nonatomic) bool disabled;
@property (getter=isOn, nonatomic) bool on;

- (bool)adjustsImageWhenDisabled;
- (long long)controlType;
- (id)imageNameForCurrentState;
- (bool)isDisabled;
- (bool)isOn;
- (void)setDisabled:(bool)arg1;
- (void)setOn:(bool)arg1;
- (bool)shouldUseActiveTintForCurrentState;

@end
