/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/AppleDepth.framework/AppleDepth
 */

@interface ADMillimeterRadiusPairsLensDistortionModel : NSObject <ADLensDistortionModel> {
    NSData * _distortedRadii;
    struct CGPoint { 
        double x; 
        double y; 
    }  _distortionCenter;
    NSData * _undistortedRadii;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSData *distortedRadii;
@property (nonatomic, readonly) struct CGPoint { double x1; double x2; } distortionCenter;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSData *undistortedRadii;

- (void).cxx_destruct;
- (void)applyDistortionModelToPixels:(unsigned long long)arg1 inPixels:(const struct CGPoint { double x1; double x2; }*)arg2 intrinsicsMatrix:(struct { /* Warning: Unrecognized filer type: ']' using 'void*' */ void*x1[3]; })arg3 pixelSize:(double)arg4 distort:(bool)arg5 outPixels:(struct CGPoint { double x1; double x2; }*)arg6;
- (void)distortPixels:(unsigned long long)arg1 undistortedPixels:(const struct CGPoint { double x1; double x2; }*)arg2 withCameraCalibration:(id)arg3 outDistortedPixels:(struct CGPoint { double x1; double x2; }*)arg4;
- (id)distortedRadii;
- (struct CGPoint { double x1; double x2; })distortionCenter;
- (id)initWithDistortionCenter:(struct CGPoint { double x1; double x2; })arg1 distortedRadii:(id)arg2 undistortedRadii:(id)arg3;
- (void)undistortPixels:(unsigned long long)arg1 distortedPixels:(const struct CGPoint { double x1; double x2; }*)arg2 withCameraCalibration:(id)arg3 outUndistortedPixels:(struct CGPoint { double x1; double x2; }*)arg4;
- (id)undistortedRadii;

@end
