/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SettingsCellularUI.framework/SettingsCellularUI
 */

@interface PSUIDataUsageCategoryListController : PSListController {
    PSUIDataUsageCategorySpecifier * _parentSpecifier;
}

@property (nonatomic, retain) PSUIDataUsageCategorySpecifier *parentSpecifier;

- (void).cxx_destruct;
- (id)init;
- (id)parentSpecifier;
- (void)setParentSpecifier:(id)arg1;
- (bool)shouldReloadSpecifiersOnResume;
- (id)specifiers;

@end
