/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NotesUI.framework/NotesUI
 */

@interface ICCollapsibleContainerView : ICCollapsibleBaseView {
    UIView * _containedView;
}

@property (nonatomic, retain) UIView *containedView;

- (void).cxx_destruct;
- (id)containedView;
- (void)performSetup;
- (void)setContainedView:(id)arg1;

@end
