/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HMFoundation.framework/HMFoundation
 */

@interface HMFLogEventSession : NSObject <HMFLogging, NSSecureCoding> {
    id /* block */  _finalizeBlock;
    RTCReporting * _rtcSession;
    HMFUnfairLock * _sessionLock;
    unsigned long long  _signpostId;
    HMFLogEventSessionVoucher * _voucher;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, copy) id /* block */ finalizeBlock;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) RTCReporting *rtcSession;
@property (nonatomic, readonly) HMFUnfairLock *sessionLock;
@property (nonatomic) unsigned long long signpostId;
@property (readonly) Class superclass;
@property (nonatomic, readonly) HMFLogEventSessionVoucher *voucher;

+ (id)logCategory;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id /* block */)finalizeBlock;
- (void)finalizeSession;
- (id)initWithCoder:(id)arg1;
- (id)initWithVoucher:(id)arg1 finalizeBlock:(id /* block */)arg2;
- (id)initWithVoucher:(id)arg1 rtcFactory:(id)arg2 finalizeBlock:(id /* block */)arg3;
- (id)rtcSession;
- (id)sessionLock;
- (void)setFinalizeBlock:(id /* block */)arg1;
- (void)setRtcSession:(id)arg1;
- (void)setSignpostId:(unsigned long long)arg1;
- (unsigned long long)signpostId;
- (void)submitEventWithName:(id)arg1 payload:(id)arg2;
- (id)voucher;

@end
