/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HomeAI.framework/HomeAI
 */

@interface HMICameraVideoFrameResult : NSObject <NSSecureCoding> {
    NSDictionary * _annotationScores;
    NSArray * _detections;
    long long  _events;
    unsigned long long  _frameHeight;
    unsigned long long  _frameId;
    unsigned long long  _frameWidth;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _regionOfInterest;
}

@property (readonly) NSDictionary *annotationScores;
@property (readonly) NSArray *detections;
@property (readonly) long long events;
@property (readonly) unsigned long long frameHeight;
@property (readonly) unsigned long long frameId;
@property (readonly) unsigned long long frameWidth;
@property (readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } regionOfInterest;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)annotationScores;
- (id)detections;
- (void)encodeWithCoder:(id)arg1;
- (long long)events;
- (unsigned long long)frameHeight;
- (unsigned long long)frameId;
- (unsigned long long)frameWidth;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrameId:(unsigned long long)arg1 events:(long long)arg2 annotationScores:(id)arg3 detections:(id)arg4 regionOfInterest:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg5 frameWidth:(unsigned long long)arg6 frameHeight:(unsigned long long)arg7;
- (bool)isEqual:(id)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })regionOfInterest;

@end
