/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthExperienceUI.framework/HealthExperienceUI
 */

@interface HealthExperienceUI.HighlightsCategoryItem : _TtCs12_SwiftObject {
    void reuseIdentifier;
    void type;
}

@end
