/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthExperienceUI.framework/HealthExperienceUI
 */

@interface HealthExperienceUI.DataTypeDescriptionDataSource : HealthExperienceUI.DataTypeMutableDataSource {
    void objectType;
    void titleText;
}

@end
