/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthExperienceUI.framework/HealthExperienceUI
 */

@interface HealthExperienceUI.HKTypeGroupListDataSource : _TtCs12_SwiftObject {
    void $__lazy_storage_$_allGroupsMinusMe;
    void eventHandler;
    void numberOfSections;
}

@end
