/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoAnalysis.framework/PhotoAnalysis
 */

@interface PHAPrivateFederatedLearningPackager : NSObject {
    NSNumber * _clippingNorm;
    DESPFLEncryptor * _encryptor;
    NSNumber * _normBinCount;
}

@property (nonatomic, readonly) NSNumber *clippingNorm;
@property (nonatomic, retain) DESPFLEncryptor *encryptor;
@property (nonatomic, readonly) NSNumber *normBinCount;

- (void).cxx_destruct;
- (bool)_addNoiseToPrePackagedResults:(id)arg1 shouldAddNoise:(bool)arg2 error:(id*)arg3;
- (bool)_callPFLPrivatizeCustomNorm:(float*)arg1 elementsCount:(id)arg2 clippingNorm:(id)arg3 normBinCount:(id)arg4 privacyIdentifier:(id)arg5;
- (id)_encryptFlattenedTrainingResults:(id)arg1 withEncryptionKey:(id)arg2 shouldEncrypt:(bool)arg3 error:(id*)arg4;
- (id)_errorWithCode:(long long)arg1 withUnderlyingError:(id)arg2;
- (id)_flattenTrainingResults:(id)arg1;
- (id)clippingNorm;
- (id)dataPackageFromTrainingResults:(id)arg1 withEncryptionKey:(id)arg2 shouldAddNoise:(bool)arg3 shouldEncrypt:(bool)arg4 error:(id*)arg5;
- (id)encryptor;
- (id)initWithClippingNorm:(id)arg1 normBinCount:(id)arg2;
- (id)normBinCount;
- (void)setEncryptor:(id)arg1;

@end
