/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ScreenTimeCore.framework/ScreenTimeCore
 */

@interface STFamilyOrganization : STCoreOrganization

@property (nonatomic, retain) NSSet *settings;

+ (id)fetchOrCreateFamilyOrganizationWithContext:(id)arg1 error:(id*)arg2;

@end
