/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ScreenTimeCore.framework/ScreenTimeCore
 */

@interface STLog : NSObject

+ (id)accountState;
+ (id)apns;
+ (id)appInfo;
+ (id)appMonitor;
+ (id)ask;
+ (id)awd;
+ (id)blueprint;
+ (id)checkpoint;
+ (id)cloudkit;
+ (id)conduit;
+ (id)conversation;
+ (id)daemon;
+ (id)deviceState;
+ (id)family;
+ (id)familyScreenTimeManager;
+ (id)familySettingsManager;
+ (id)idsTransport;
+ (id)logCategories;
+ (id)managementStateObserver;
+ (id)mirroring;
+ (id)oneMoreMinuteManager;
+ (id)payload;
+ (id)payloadManager;
+ (id)payloadQueue;
+ (id)persistence;
+ (id)personal;
+ (id)pinController;
+ (id)pinService;
+ (id)requestManager;
+ (id)restrictionsMigrator;
+ (id)screenTimeOrganizationController;
+ (id)screentime;
+ (id)test;
+ (id)tool;
+ (id)transaction;
+ (id)usage;
+ (id)userNotifications;
+ (id)utility;
+ (id)versionVector;

@end
