/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoverSheet.framework/CoverSheet
 */

@interface CSBatteryChargingView : CSCoverSheetViewBase {
    double  _alignmentPercent;
    _UILegibilitySettings * _legibilitySettings;
}

@property (nonatomic) double alignmentPercent;
@property (nonatomic, readonly) long long batteryCount;
@property (nonatomic) bool batteryVisible;
@property (nonatomic, readonly) double desiredVisibilityDuration;
@property (nonatomic, retain) _UILegibilitySettings *legibilitySettings;

+ (id)batteryChargingViewWithDoubleBattery;
+ (id)batteryChargingViewWithSingleBattery;
+ (id)maskImageNameForChargingBattery;
+ (id)maskImageNameForExternalChargingBattery;
+ (id)maskImageNameForInternalChargingBattery;

- (void).cxx_destruct;
- (double)_batteryOriginYForBatteryHeight:(double)arg1;
- (id)_chargePercentFont;
- (id)_updateChargeString:(id)arg1 oldLabel:(id)arg2;
- (double)alignmentPercent;
- (long long)batteryCount;
- (bool)batteryVisible;
- (double)desiredVisibilityDuration;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)legibilitySettings;
- (void)setAlignmentPercent:(double)arg1;
- (void)setBatteryVisible:(bool)arg1;
- (void)setLegibilitySettings:(id)arg1;
- (void)setPrimaryBatteryText:(id)arg1 forBattery:(id)arg2;
- (void)setSecondaryBatteryText:(id)arg1 forBattery:(id)arg2;

@end
