/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ActivityRingsUI.framework/ActivityRingsUI
 */

@interface ARUICelebration : NSObject {
    void _bottomColor;
    void _contrastColor;
    float  _time;
    void _topColor;
}

@property (nonatomic, readonly) float time;

- (id)_init;
- (void)endWithCompletion:(id /* block */)arg1;
- (void)setBottomColor;
- (void)setContrastColor;
- (void)setTopColor;
- (void)storeCelebration:(id)arg1 withRing:(id)arg2;
- (float)time;
- (void*)timeBytes;
- (unsigned long long)type;
- (void)update:(double)arg1;

@end
