/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ActivityRingsUI.framework/ActivityRingsUI
 */

@interface ARUIBlurRenderState : NSObject {
    <MTLDevice> * _device;
    <MTLLibrary> * _library;
    NSMutableDictionary * _renderStates;
    NSArray * _supportedRadii;
}

- (void).cxx_destruct;
- (id)_renderPipelineStateForKey:(id)arg1;
- (id)initWithDevice:(id)arg1 library:(id)arg2;
- (id)renderPipelineDescriptorFromLibrary:(id)arg1 forRadius:(long long)arg2;
- (id)renderPipelineStateForBlurRadius:(long long)arg1 error:(long long*)arg2;

@end
