/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ActivityRingsUI.framework/ActivityRingsUI
 */

@interface ARUIWavesRenderState : ARUICelebrationRenderState

- (id)renderPipelineDescriptorFromLibrary:(id)arg1;

@end
