/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/ActivityRingsUI.framework/ActivityRingsUI
 */

@interface ARUISpriteRenderPipelineConfiguration : NSObject {
    bool  _shouldRenderSprites;
}

@property (nonatomic) bool shouldRenderSprites;

- (void)setShouldRenderSprites:(bool)arg1;
- (bool)shouldRenderSprites;

@end
