/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreHandwriting.framework/CoreHandwriting
 */

@interface CHBottomUpStrokeGroupingResult : CHStrokeGroupingResult {
    NSDictionary * _substrokePlacementsByStrokeIdentifier;
}

@property (nonatomic, readonly, retain) NSDictionary *substrokePlacementsByStrokeIdentifier;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)initWithStrokeGroups:(id)arg1 createdStrokeGroups:(id)arg2 deletedStrokeGroups:(id)arg3 substrokePlacementsByStrokeIdentifier:(id)arg4;
- (id)substrokePlacementsByStrokeIdentifier;

@end
