/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreHandwriting.framework/CoreHandwriting
 */

@interface CHMutableTokenizedTextResultColumn : CHTokenizedTextResultColumn

@property (nonatomic, copy) NSArray *tokenRows;

- (id)_mutableTokenRows;
- (long long)addTokenRowWithTokens:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)initWithTokenRows:(id)arg1;
- (void)removeTokenRowAtIndex:(long long)arg1;
- (void)setTokenRows:(id)arg1;
- (void)sortTokenRows;

@end
