/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreHandwriting.framework/CoreHandwriting
 */

@interface CHRemoteRecognitionRequest : NSObject <NSSecureCoding> {
    NSCharacterSet * _activeCharacterSet;
    int  _contentType;
    CHDrawing * _drawing;
    bool  _hasBeenSubmitted;
    NSLocale * _locale;
    unsigned long long  _maxRecognitionResultCount;
    struct CGSize { 
        double width; 
        double height; 
    }  _minimumDrawingSize;
    NSDictionary * _options;
    long long  _priority;
    int  _recognitionMode;
    bool  _shouldEnableCachingIfAvailable;
    bool  _shouldUseTextReplacements;
}

@property (nonatomic, copy) NSCharacterSet *activeCharacterSet;
@property (nonatomic) int contentType;
@property (nonatomic, copy) CHDrawing *drawing;
@property (nonatomic) bool hasBeenSubmitted;
@property (nonatomic, copy) NSLocale *locale;
@property (nonatomic) unsigned long long maxRecognitionResultCount;
@property (nonatomic) struct CGSize { double x1; double x2; } minimumDrawingSize;
@property (nonatomic, copy) NSDictionary *options;
@property (nonatomic) long long priority;
@property (nonatomic) int recognitionMode;
@property (nonatomic) bool shouldEnableCachingIfAvailable;
@property (nonatomic) bool shouldUseTextReplacements;

+ (bool)supportsSecureCoding;

- (id)activeCharacterSet;
- (int)contentType;
- (void)dealloc;
- (id)description;
- (id)drawing;
- (void)encodeWithCoder:(id)arg1;
- (bool)hasBeenSubmitted;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithLocale:(id)arg1 recognitionMode:(int)arg2 drawing:(id)arg3 options:(id)arg4 priority:(long long)arg5;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToRemoteRecognitionRequest:(id)arg1;
- (id)locale;
- (unsigned long long)maxRecognitionResultCount;
- (struct CGSize { double x1; double x2; })minimumDrawingSize;
- (id)options;
- (long long)priority;
- (int)recognitionMode;
- (id)recognizerConfigurationKey;
- (void)setActiveCharacterSet:(id)arg1;
- (void)setContentType:(int)arg1;
- (void)setDrawing:(id)arg1;
- (void)setHasBeenSubmitted:(bool)arg1;
- (void)setLocale:(id)arg1;
- (void)setMaxRecognitionResultCount:(unsigned long long)arg1;
- (void)setMinimumDrawingSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setOptions:(id)arg1;
- (void)setPriority:(long long)arg1;
- (void)setRecognitionMode:(int)arg1;
- (void)setShouldEnableCachingIfAvailable:(bool)arg1;
- (void)setShouldUseTextReplacements:(bool)arg1;
- (bool)shouldEnableCachingIfAvailable;
- (bool)shouldUseTextReplacements;

@end
