/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NAPageKind : NSObject {
    void kind;
}

+ (id)anf;
+ (id)pdf;

- (void).cxx_destruct;
- (id)init;

@end
