/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NAPDFReplicaViewerAssembly : NSObject <NFAssembly>

- (id)init;
- (void)loadInRegistry:(id)arg1;

@end
