/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.SubscribeActionHandler : NSObject <SXSubscribeActionHandler> {
    void $__lazy_storage_$_purchasingSpinnerViewController;
    void $__lazy_storage_$_verifyingSpinnerViewController;
    void actionModel;
    void bundleSubscriptionManager;
    void configurationManager;
    void familySharingLandingPageLauncher;
    void headline;
    void purchaseStarter;
    void purchasingSpinnerViewControllerFactory;
    void router;
}

- (void).cxx_destruct;
- (void)handleSubscribeActionOnPresenter:(id)arg1 completionBlock:(id /* block */)arg2;
- (id)init;

@end
