/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.ReportConcernDetailRouter : _TtCs12_SwiftObject {
    void controller;
    void resolver;
}

@end
