/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.TableOfContentsBlueprintViewSupplementaryViewProvider : _TtCs12_SwiftObject {
    void headerViewRenderer;
}

@end
