/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.InterstitialAdvertisementStyler : _TtCs12_SwiftObject {
    void baseStyler;
}

@end
