/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.IssueEmbeddableViewControllerFactory : _TtCs12_SwiftObject {
    void resolver;
    void tracker;
}

@end
