/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.ArticleViewerArticleFactory : _TtCs12_SwiftObject {
    void articleController;
}

@end
