/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.IssueViewerDataManager : _TtCs12_SwiftObject {
    void issueLoader;
}

@end
