/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.IssueTableOfContentsActionHandler : _TtCs12_SwiftObject {
    void closure;
}

@end
