/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
 */

@interface _DKDiskSubsystemIdentifier : NSObject

+ (id)type;
+ (id)withDiskSubsystem:(id)arg1;

@end
