/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsSubscription.framework/NewsSubscription
 */

@interface NewsSubscription.ContainerPurchaseObserver : _TtCs12_SwiftObject {
    void bridgedPurchaseObserver;
}

@end
