/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsSubscription.framework/NewsSubscription
 */

@interface NewsSubscription.ContainerPurchaseTransactionObserver : _TtCs12_SwiftObject {
    void bridgedPurchaseTransactionObserver;
}

@end
