/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsSubscription.framework/NewsSubscription
 */

@interface NewsSubscription.FinanceURLHandler : _TtCs12_SwiftObject {
    void baseHostName;
    void patterns;
    void router;
}

@end
