/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsSubscription.framework/NewsSubscription
 */

@interface NewsSubscription.PurchaseManager : _TtCs12_SwiftObject <FCPurchaseManagerDelegate> {
    void internalPurchaseManager;
    void purchaseContextEntriesManager;
    void purchaseController;
    void purchaseObservers;
    void transactionObservers;
}

- (void)purchaseFailedForInvalidPurchaseReceiptWithProductID:(id)arg1 ongoingPurchaseEntry:(id)arg2;
- (void)purchaseFailedWithProductID:(id)arg1 transactionState:(long long)arg2 transactionError:(id)arg3 ongoingPurchaseEntry:(id)arg4;
- (void)purchaseSuccessWithProductID:(id)arg1 purchaseReceipt:(id)arg2 chargeCurrencyCode:(id)arg3 ongoingPurchaseEntry:(id)arg4;

@end
