/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsSubscription.framework/NewsSubscription
 */

@interface NPSoftPaywallModule : NSObject <NPSoftPaywallModuleType> {
    void resolver;
    void tracker;
}

- (void).cxx_destruct;
- (id)createViewController;
- (id)init;

@end
