/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsSubscription.framework/NewsSubscription
 */

@interface NPSoftPaywallAssembly : NSObject <NFAssembly>

- (id)init;
- (void)loadInRegistry:(id)arg1;

@end
