/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLDataMigratorSupport : NSObject {
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
    PLPhotoLibraryPathManager * _pathManager;
}

@property (nonatomic, readonly) PLPhotoLibraryPathManager *pathManager;

- (void).cxx_destruct;
- (void)_removeAsidePhotosDatabase;
- (void)_removeInternalMemoriesRelatedSnapshotDirectory;
- (void)_removeLegacyMetadataFiles;
- (void)_removeModelInterestDatabase;
- (bool)hasCapturedOTARestoreStatus;
- (id)initWithPathManager:(id)arg1;
- (id)pathManager;
- (void)recordDataMigrationInfo:(id)arg1;
- (void)setCapturedOTARestoreStatus;
- (void)writeModelMigratorPostProcessingToken;

@end
