/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLMomentShareParticipantValueTransformer : NSSecureUnarchiveFromDataTransformer

+ (id)allowedTopLevelClasses;

@end
