/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/FMFCore.framework/FMFCore
 */

@interface FMFCore.FMFAskToFollowRequest : FMFCore.FMFBaseRequest {
    void emails;
    void friendIds;
}

@end
