/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthToolbox.framework/HealthToolbox
 */

@interface WDHealthDataCategoryNoDataTableViewCell : UITableViewCell {
    UILabel * _displayTypeLabel;
    NSString * _displayTypeText;
}

@property (nonatomic, copy) NSString *displayTypeText;

- (void).cxx_destruct;
- (void)_setupUI;
- (id)displayTypeText;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setDisplayTypeText:(id)arg1;

@end
