/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOClientRankingModelFeatureIdentifier : NSObject

@property (nonatomic, readonly) long long featureIdentifierType;

- (long long)featureIdentifierType;

@end
