/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TextInputCore.framework/TextInputCore
 */

@interface TIUserModelIndexedCounter : NSObject {
    NSMutableArray * _current;
    NSString * _name;
    NSMutableArray * _persisted;
}

@property (nonatomic, readonly) int bucketCount;
@property (nonatomic, readonly) NSNumber *count;
@property (nonatomic, readonly) NSArray *counts;
@property (nonatomic, readonly) NSArray *currentCounts;
@property (nonatomic, readonly) NSString *name;

- (void).cxx_destruct;
- (int)bucketCount;
- (id)count;
- (id)counts;
- (id)currentCounts;
- (void)doPersist:(id)arg1 forDate:(id)arg2 forInputMode:(id)arg3 forContext:(id)arg4;
- (id)initWithName:(id)arg1;
- (id)name;
- (void)setupBuckets;
- (void)update:(int)arg1 forIndex:(int)arg2;
- (void)updateWithLoadedNumber:(id)arg1 forIndex:(int)arg2;
- (void)updateWithLoadedValue:(int)arg1 forIndex:(int)arg2;
- (void)updateWithNumber:(id)arg1 forIndex:(int)arg2;

@end
