/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/TextRecognition.framework/TextRecognition
 */

@interface CRCtcMaxDecoding : NSObject

+ (void)maxDecodingForInput:(id)arg1 outputString:(id*)arg2 outputProb:(id*)arg3 outputWhitespaceRanges:(id*)arg4;

@end
