/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/RelevanceEngine.framework/RelevanceEngine
 */

@interface _RELargeSetFeatureValue : _RESetFeatureValue {
    NSSet * _values;
}

- (void).cxx_destruct;
- (id)initWithSet:(id)arg1;
- (id)setValue;

@end
