/* Generated by EzioChiu
   Image: /System/Library/Frameworks/CoreML.framework/CoreML
 */

@interface MLModelDescription : NSObject <NSSecureCoding> {
    NSDictionary * _inputDescriptionsByName;
    NSOrderedSet * _inputFeatureNames;
    bool  _isUpdatable;
    NSDictionary * _metadata;
    NSURL * _modelURL;
    NSDictionary * _outputDescriptionsByName;
    NSOrderedSet * _outputFeatureNames;
    NSDictionary * _parameterDescriptionsByKey;
    NSString * _predictedFeatureName;
    NSString * _predictedProbabilitiesName;
    NSDictionary * _trainingInputDescriptionsByName;
}

@property (nonatomic, readonly) NSDictionary *inputDescriptionsByName;
@property (retain) NSOrderedSet *inputFeatureNames;
@property (nonatomic) bool isUpdatable;
@property (nonatomic, readonly) NSDictionary *metadata;
@property (nonatomic, retain) NSURL *modelURL;
@property (nonatomic, readonly) NSDictionary *outputDescriptionsByName;
@property (retain) NSOrderedSet *outputFeatureNames;
@property (nonatomic, retain) NSDictionary *parameterDescriptionsByKey;
@property (nonatomic, readonly, copy) NSString *predictedFeatureName;
@property (nonatomic, readonly, copy) NSString *predictedProbabilitiesName;
@property (nonatomic, retain) NSDictionary *trainingInputDescriptionsByName;

+ (id)metadataWithFormat:(struct _MLModelMetadataSpecification { struct shared_ptr<CoreML::Specification::Metadata> { struct Metadata {} *x_1_1_1; struct __shared_weak_count {} *x_1_1_2; } x1; }*)arg1;
+ (id)metadataWithSpecification:(struct _MLModelSpecification { struct shared_ptr<CoreML::Specification::Model> { struct Model {} *x_1_1_1; struct __shared_weak_count {} *x_1_1_2; } x1; }*)arg1;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)debugQuickLookObject;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithInputDescriptions:(id)arg1 outputDescriptions:(id)arg2 predictedFeatureName:(id)arg3 predictedProbabilitiesName:(id)arg4 metadata:(id)arg5;
- (id)initWithInputDescriptions:(id)arg1 outputDescriptions:(id)arg2 predictedFeatureName:(id)arg3 predictedProbabilitiesName:(id)arg4 trainingInputDescriptions:(id)arg5 metadata:(id)arg6;
- (id)initWithModelDescriptionSpecification:(struct _MLModelDescriptionSpecification { struct shared_ptr<CoreML::Specification::ModelDescription> { struct ModelDescription {} *x_1_1_1; struct __shared_weak_count {} *x_1_1_2; } x1; }*)arg1 error:(id*)arg2;
- (id)inputDescriptionsByName;
- (id)inputFeatureNames;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToDescription:(id)arg1;
- (bool)isUpdatable;
- (id)metadata;
- (id)modelURL;
- (id)outputDescriptionsByName;
- (id)outputFeatureNames;
- (id)parameterDescriptionsByKey;
- (id)predictedFeatureName;
- (id)predictedProbabilitiesName;
- (void)setInputFeatureNames:(id)arg1;
- (void)setIsUpdatable:(bool)arg1;
- (void)setModelURL:(id)arg1;
- (void)setOutputFeatureNames:(id)arg1;
- (void)setParameterDescriptionsByKey:(id)arg1;
- (void)setTrainingInputDescriptionsByName:(id)arg1;
- (id)trainingInputDescriptionsByName;
- (bool)verifyInput:(id)arg1 error:(id*)arg2;

@end
