/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVAssetProxyInternal : NSObject {
    AVAssetInspectorLoader * loader;
    AVDispatchOnce * makeTracksArrayOnce;
    NSArray * tracks;
}

@end
