/* Generated by EzioChiu
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVRoutingSessionDestinationInternal : NSObject {
    struct __CFDictionary { } * figDestination;
}

@end
