/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SiriKitFlow.framework/SiriKitFlow
 */

@interface SiriKitFlow.AppConcept : _TtCs12_SwiftObject {
    void app;
    void conceptType;
}

@end
