/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SiriKitFlow.framework/SiriKitFlow
 */

@interface SiriKitFlow.DucTemplateExecutor : _TtCs12_SwiftObject {
    void ducTemplatingService;
}

@end
