/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SiriKitFlow.framework/SiriKitFlow
 */

@interface SiriKitFlow.SiriKitDisambiguationItem : _TtCs12_SwiftObject {
    void allowLineWrapForDisplayText;
    void components;
    void utterance;
}

@end
