/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SiriKitFlow.framework/SiriKitFlow
 */

@interface SiriKitFlow.TaskLoggingService : _TtCs12_SwiftObject {
    void metricsLogger;
    void metricsState;
}

@end
