/* Generated by EzioChiu
   Image: /System/Library/PrivateFrameworks/SiriKitFlow.framework/SiriKitFlow
 */

@interface SiriKitFlow.SiriKitDisambiguationItemComponent : _TtCs12_SwiftObject {
    void allowedOnLockScreen;
    void print;
    void printOnLockScreen;
    void speak;
    void speakOnLockScreen;
}

@end
